### ISSUE TITLE
How would I custom add email confirmation and password reset controllers?

### ISSUE THREAD

**Issue by dottjt** [danschultzer/pow#102]
Hi!

I've noticed that the guide provides instruction on how to do this with the session and registration controllers, but I can't seem to find any guides to do it for the extensions. Any idea on that?

Sorry if I'm asking for too much!

**Comment by danschultzer** [comment]
It's great you're asking, others may have these thoughts too, and will find this issue!

I would just extract the controller actions from the controllers in Pow:

https://github.com/danschultzer/pow/blob/9e0f82d6f8ca1a8b18c6b03cc7c63c3fd4320f7e/lib/extensions/email_confirmation/phoenix/controllers/confirmation_controller.ex

https://github.com/danschultzer/pow/blob/9e0f82d6f8ca1a8b18c6b03cc7c63c3fd4320f7e/lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex

Pow separates a controller action into two parts, `process_ACTION` and `respond_ACTION`, to make it easier to integrating extensions. When you make a custom controller you can just forego that, and put it all into the controller action.

Controller actions in Pow are made as lean as possible, and usually only consists of a single Plug method call. Let me know if this is sufficient.

I wonder why you need them as custom controllers?

**Comment by dottjt** [comment]
Thank you!

I think maybe it's just confusion over how to use the library correctly. Like, reading the guides, I still don't quite understand how to send different email templates depending on the extension, and with the swoosh guide you define one cast/process, and it's like, how can I put my custom templates in, if not through a custom controller?

**Comment by danschultzer** [comment]
If you only need to customize templates, then you won't need to create a custom controller at all. The guides are usually for more advanced modifications, while the readme contains most common use cases.

The information for setting up custom templates are right here:
https://github.com/danschultzer/pow#modify-templates
https://github.com/danschultzer/pow#modify-extension-templates

And for e-mail templates it's right here:
https://github.com/danschultzer/pow#modify-mailer-templates

**Comment by danschultzer** [comment]
Let me know if this was what you were looking for. If so, I'll update the custom controller guide with a note on custom templates 😄

**Comment by dottjt** [comment]
Oh, thank you very much! It's those email templates I didn't realise they were there! hehe silly me!
I think the primary reason why I wanted to access to those controllers, was so that I could for example, put a login/register form on say, the homepage. 

And that's not possible if I don't know what's happening in the controller so I know which data to pass. Although, I suppose that's not relevant to the post requests, just the get requests.

**Comment by danschultzer** [comment]
That's great! I'll add a section to the custom controllers guide.

I think I understand what you want to do. To keep things simple I would only add a custom registration form to the front page that posts to `Routes.pow_registration_path(conn, :create)` and then let Pow take care of the rest (e.g. the user will see the `/registration/new` page if there is errors in the input, and users can also sign up by going directly to `/registration/new`).

**Comment by sveredyuk** [comment]
Very strange but:
```elixir
params = %{
"id" => "token"
"user" => %{ "password" => "new_password", "password_confirmation" => "new_password" }
}

conn |> PowResetPassword.Plug.update_user_password(params)
```
raise the error:
```
Request: PUT /api/password/SFMyNTY.ZTMwNGQzMTgtOTUzZC00OTNiLTkzM2QtYTlkYWQ4OGE1MjA5.GVdVOfuTU6R8adiinWmjINrRMc76t1ZFyx74cpCnhnU
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in PowResetPassword.Ecto.Context.update_password/3
        (pow 1.0.19) lib/extensions/reset_password/ecto/context.ex:10: PowResetPassword.Ecto.Context.update_password(nil, %{"id" => "SFMyNTY.ZTMwNGQzMTgtOTUzZC00OTNiLTkzM2QtYTlkYWQ4OGE1MjA5.GVdVOfuTU6R8adiinWmjINrRMc76t1ZFyx74cpCnhnU", "user" => %{"password" => "new_password", "password_conformation" => "new_password"}}, [mod: HandshakeWeb.APIAuthPlug, plug: HandshakeWeb.APIAuthPlug, otp_app: :demo])
        (pow 1.0.19) lib/extensions/reset_password/plug.ex:142: PowResetPassword.Plug.update_user_password/2
        (demo 1.0.7) lib/demo_web/controllers/api/password_controller.ex:19: HandshakeWeb.API.PasswordController.update/2
        (demo 1.0.7) lib/demo_web/controllers/api/password_controller.ex:1: HandshakeWeb.API.PasswordController.action/2
        (demo 1.0.7) lib/demo_web/controllers/api/password_controller.ex:1: HandshakeWeb.API.PasswordController.phoenix_controller_pipeline/2
        (phoenix 1.4.16) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (demo 1.0.7) lib/plug/error_handler.ex:65: HandshakeWeb.Router.call/2
        (demo 1.0.7) lib/demo_web/endpoint.ex:1: HandshakeWeb.Endpoint.plug_builder_call/2
        (demo 1.0.7) lib/plug/debugger.ex:132: HandshakeWeb.Endpoint."call (overridable 3)"/2
```

I generated token for the existing user. Very strange.

**Comment by danschultzer** [comment]
It's described in the docs here: https://hexdocs.pm/pow/1.0.19/PowResetPassword.Plug.html#update_user_password/2

You have to assign the user first by loading it. This is how it could look:

```elixir
params = %{
"id" => "token"
"user" => %{ "password" => "new_password", "password_confirmation" => "new_password" }
}

case PowResetPassword.Plug.load_user_by_token(conn, params["id"]) do
  {:ok, conn} -> PowResetPassword.Plug.update_user_password(conn, params["user"])
  {:error, conn} -> # User not found
end
```

The next Pow release will have improved flow and better docs: https://github.com/danschultzer/pow/blob/c6161654b9df2dda983d22efbdc68f51bbe4afa3/lib/extensions/reset_password/plug.ex#L134-L143

**Comment by sveredyuk** [comment]
I see. nil user just confused me. Thanks.

**Comment by sveredyuk** [comment]
By the way, how I can test this update/2? I am trying to generate reset password:

```elixir
test "with valid token user", %{conn: conn} do
      {:ok, user} = Accounts.register_user(%{email: "user@example.com", password: "password"})
      token = PowResetPassword.Plug.create_reset_token(conn, %{"email" => user.email})
      conn = put(conn, Routes.api_password_path(conn, :update), %{"id" => token, "user" => @pswd_params })

      assert json = json_response(conn, 200)
      assert json["data"]["message"] == "Password has been successfully updated"
    end
```

but got the error:
```
** (Pow.Config.ConfigError) Pow configuration not found in connection. Please use a Pow plug that puts the Pow configuration in the plug connection.
    (pow 1.0.19) lib/pow/config.ex:56: Pow.Config.raise_error/1
    (pow 1.0.19) lib/extensions/reset_password/plug.ex:50: PowResetPassword.Plug.create_reset_token/2
```

I assume I need somehow pipeline plugs with config?

**Comment by danschultzer** [comment]
I recommend that you take a look at [the tests](https://github.com/danschultzer/pow/blob/v1.0.19/test/extensions/reset_password/phoenix/controllers/reset_password_controller_test.exs#L187-L194).

You could set it up like this:

```elixir
@pow_config [otp_app: :my_app]

test "with valid token user", %{conn: conn} do
  {:ok, user} = Accounts.register_user(%{email: "user@example.com", password: "password"})
  token = create_reset_token(conn, user.email)
  conn = put(conn, Routes.api_password_path(conn, :update), %{"id" => token, "user" => @pswd_params })

  assert json = json_response(conn, 200)
  assert json["data"]["message"] == "Password has been successfully updated"
end

defp create_reset_token(conn, email) do
  {:ok, %{token: token}, _conn} =
    conn
    |> Pow.Plug.put_config(@pow_config)
    |> PowResetPassword.Plug.create_reset_token(%{"email" => email})

  token
end
```

If you use the default ETS or Mnesia cache, then you also need to wait (e.g. `:timer.sleep(100)`) or listen for an insert message, since the write calls are asynchronous in the GenServer.

**Comment by sveredyuk** [comment]
Thanks, but now I missed something in test.exs ?

```elixir
 ** (ArgumentError) No conn.secret_key_base set
     code: token = create_reset_token(conn, user.email)
     stacktrace:
       (pow 1.0.19) lib/pow/plug/message_verifier.ex:49: Pow.Plug.MessageVerifier.validate_secret_key_base/1
       (pow 1.0.19) lib/pow/plug/message_verifier.ex:44: Pow.Plug.MessageVerifier.derive/3
       (pow 1.0.19) lib/pow/plug/message_verifier.ex:22: Pow.Plug.MessageVerifier.sign/4
       (pow 1.0.19) lib/extensions/reset_password/plug.ex:65: PowResetPassword.Plug.create_reset_token/2
```

**Comment by danschultzer** [comment]
Oh right, the conn needs a secret key base. AFAIK it's set when the endpoint is called.

For the tests, you can do this:

```elixir
defp create_reset_token(conn, email) do
  {:ok, %{token: token}, _conn} =
    %{conn | secret_key_base: MyAppWeb.Endpoint.config(:secret_key_base)}
    |> Pow.Plug.put_config(@pow_config)
    |> PowResetPassword.Plug.create_reset_token(%{"email" => email})

  token
end
```

I'm thinking of maybe refactoring all this so you can just use the endpoint itself when calling these methods, e.g.:

```elixir
PowResetPassword.Plug.create_reset_token(MyAppWeb.Endpoint, %{"email" => email})
```

This could be much cleaner, and fits with how a lot of method in Phoenix works though not sure if it fits within the the plug module group.

**Comment by sveredyuk** [comment]
I think all logic of token generation should be extracted from Plug. Now everything depends on Plug and HTTP connection.
