### ISSUE TITLE
question: placement of routes_backend

### ISSUE THREAD

**Issue by ebagdasa** [danschultzer/pow#109]
I wonder if I do something wrong when adding callbacks. I created new module in myweb called pow_routes.
the module looks like:
```
defmodule MyWeb.Pow.Routes do
  use Pow.Phoenix.Routes
  alias MyWeb.Router.Helpers, as: Routes

  def after_sign_out_path(conn) do
    IO.puts("AAAAAA")
    Routes.path(conn, :index)
  end

  def after_sign_in_path(conn) do
    IO.puts("BBBBBB")
    Routes.path(conn, :dashboard)
  end

end
```

this is my config.exs:
```
config :my, :pow,
  user: My.Users.User,
  repo: My.Repo,
  web_module: MyWeb,
  routes_backend: MyWeb.Pow.Routes
```
Somehow, I am never redirected correctly, neither I see any debug output.

thanks a lot!

**Comment by danschultzer** [comment]
Looks right. Can you post your Endpoint module?

**Comment by ebagdasa** [comment]
```
defmodule MyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :my

  socket "/socket",
         MyWeb.UserSocket,
         websocket: true,
         longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phx.digest
  # when deploying your static files in production.
  plug Plug.Static,
       at: "/",
       from: :my,
       gzip: false,
       only: ~w(css fonts images js favicon.ico robots.txt)

         # Code reloading can be explicitly enabled under the
         # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
       parsers: [:urlencoded, :multipart, :json],
       pass: ["*/*"],
       json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
       store: :cookie,
       key: "_key",
       signing_salt: "key"

  plug Pow.Plug.Session, otp_app: :my

  plug Pow.Plug.Session,
       repo: My.Repo,
       user: My.Users.User,
       web_module: MyWeb


  plug MyWeb.Router
end
```

**Comment by danschultzer** [comment]
Ok, I've added a few more tests with #110 since I wasn't sure if this was a bug in Pow. It seems it all works as expected so it must be an invalid setting somewhere.

Can you try `mix clean`, and start up the phoenix server again?

**Comment by ebagdasa** [comment]
yeah, I see the same thing. Can you give me some tips on how to debug it? I can update files in deps/pow/lib/pow/phoenix/, but it doesn't seem to make difference either.

**Comment by ebagdasa** [comment]
oh, it needs mix clean --deps --only pow. Let me keep debugging, I will get back here.

**Comment by danschultzer** [comment]
Did that work?

If not, and you're ok with digging through the deps source code you can add `IO.inspect/1` to this file:

https://github.com/danschultzer/pow/blob/4f0f1f93e14d0b0f7aee705958e1bbe0669c1c88/lib/pow/phoenix/controllers/controller.ex#L118-L126

And then rebuild the deps. I would put it like this to figure out what configuration it has access to:

```elixir
  @spec routes(Conn.t(), atom()) :: atom()
  def routes(conn, fallback) do
    conn
    |> Plug.fetch_config()
    |> IO.inspect()
    |> Config.get(:routes_backend, fallback)
    |> IO.inspect()
  end
```

If the configuration is `otp_app: :my`, then you should try check it with `IO.inspect Application.get_env(:my, :pow, [])` to see if the `:routes_backend` is there.

**Comment by ebagdasa** [comment]
Using your idea with printing controller: 
```
config: : [
  mod: Pow.Plug.Session,
  repo: My.Repo,
  user: My.Users.User,
  web_module: MyWeb
]
routes_backend: : Pow.Phoenix.Routes
```

However, running `Application.get_env(:my, :pow, [])` through iex -S mix gives me: 
```
iex(1)> Application.get_env(:my, :pow, [])
[
  user: My.Users.User,
  repo: My.Repo,
  web_module: MyWeb,
  routes_backend: MyWeb.Pow.Routes
]

```

**Comment by danschultzer** [comment]
Oh wait, I didn't look carefully at your Endpoint module 😄 

You got two Pow.Plug.Session plugs:

```elixir
  plug Pow.Plug.Session, otp_app: :my

  plug Pow.Plug.Session,
       repo: My.Repo,
       user: My.Users.User,
       web_module: MyWeb
```

Remove the second one as it overrides the previous one.

**Comment by ebagdasa** [comment]
oh, sweet. Thanks a lot! Sorry, I somehow misunderstood that.
