### ISSUE TITLE
Session templates + email confirmation not working as expected

### ISSUE THREAD

**Issue by dottjt** [danschultzer/pow#116]
Hello :) 

I'm using the PowEmailConfirmation extension, and I believe there are a few inconsistencies in how it works.

Guide: https://github.com/danschultzer/pow/blob/master/lib/extensions/email_confirmation/README.md 

I've noticed in the guide it says you can put this code inside /registration/edit.html:

```
<%= if @changeset.data.unconfirmed_email do %>
        <div>
          <p>Click the link in the confirmation email to change your email to <%= @changeset.data.unconfirmed_email %></span>.</p>
        </div>
      <% end %>
```

However, it doesn't work if I put this code in the /session/new.html template. I don't believe this makes sense, because if a user then attempts to sign in with an unconfirmed email, it doesn't seem to show any errors, or feedback. The page just resets, but doesn't go anywhere.

In fact, it doesn't seem that the session/new.html will throw/show any sort of error for the user? For example, if I just input an email, but not a password - it won't login, but it won't display an error as to what's wrong. 

Or am I doing this wrong?

Here is my session/new.html template for reference:

`
<div class="accounts__wrapper">
  <%= partial "header.html", assigns %>

  <h1 class="accounts__wrapper__title">Sign in</h1>

  <div class="form__wrapper">
    <%= form_for @changeset, @action, [as: :user], fn f -> %>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <%= if @changeset.data.unconfirmed_email do %>
        <div>
          <p>Click the link in the confirmation email to change your email to <%= @changeset.data.unconfirmed_email %></span>.</p>
        </div>
      <% end %>

      <div class="form__input__container">
        <div class="error__label__combo">
          <%= label f, @changeset.data.__struct__.pow_user_id_field() %>
          <%= error_tag f, @changeset.data.__struct__.pow_user_id_field() %>
        </div>
        <%= text_input f, @changeset.data.__struct__.pow_user_id_field() %>
  
        <div class="error__label__combo">
          <%= label f, :password %>
          <%= error_tag f, :password %>
        </div>
        <%= password_input f, :password %>
      </div>

      <div class="form__submission__container">
        <%= submit "Sign in" %>

        <div class="form__extra">
          <span><%= link "Register", to: Routes.pow_registration_path(@conn, :new) %></span> |
          <span><%= link "Reset password", to: Routes.pow_reset_password_reset_password_path(@conn, :new) %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= partial "footer.html", assigns %>
`

Thank you so much in advance!

PS: Sorry for the formatting. @Changeset is actually lowercase.

**Comment by danschultzer** [comment]
`@changeset.data.unconfirmed_email` can only be used in the `edit.html.ex` as it requires an existing user. The session changeset will be a blank user and will never have `:unconfirmed_email` set.

If you have changed the e-mail of an existing user, and e-mail is used for signing in, you would have to sign in with your old e-mail until it's confirmed. It definitely should show a flash error with `The provided login details did not work. Please verify your credentials, and try again.`.

I'm not sure if this can be improved.

**Comment by dottjt** [comment]
Thank you for getting back so quickly.

Basically, it doesn't seem to be showing a flash error. I don't actually believe flash is in that template at all. Would you please be able to guide me in the right direction?

**Comment by danschultzer** [comment]
Sure, how does your `app.html.eex` layout look? You may be missing this:

```elixir
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
```

**Comment by dottjt** [comment]
Ah yes, that may very well be it ~! I will test shortly and get back to you :)
```
<!DOCTYPE html>
<html lang="en">
  <body>
    <main role="main" class="main">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>
```

**Comment by dottjt** [comment]
Oh, thank you so much! Those flash messages were what was missing :)
