### ISSUE TITLE
Bug: Reset password doesn't work when you're logged in.

### ISSUE THREAD

**Issue by dottjt** [danschultzer/pow#130]
Hey Dan,

I think I've found a bug. 

Essentially, when you're logged in as a user and then try and go to the reset password link, it will take you to whatever is defined inside `def after_sign_in_path(conn), do: etc.` as opposed to the reset password page. Or is this by design? 

Here is the link I am using. 

`<%= link "Send reset password email", to: Routes.pow_reset_password_reset_password_path(@conn, :new), class: "button subscribe__button" %>`

Interested to hear your thoughts :)

**Comment by dottjt** [comment]
I believe it might be due to how the routes are defined inside pow_routes inside of the Router, and how the authentication interacts with that. Just a thought!

**Comment by danschultzer** [comment]
You [can't view that page](https://github.com/danschultzer/pow/blob/fd35532ee3e5e3f08739acf05aba0e87e3e3ef04/lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex#L8) if you're already authenticated. It'll redirect the user to the `user_not_authenticated_path/1` route:
https://github.com/danschultzer/pow/blob/9a4ab3a7e0ee98ea2f1f425fc2bcac6d9cc39e6d/lib/pow/phoenix/controllers/plug_error_handler.ex#L24-L28

**Comment by dottjt** [comment]
Ah, okay. Is there a function I can run instead that will just go ahead and send the reset password email?

**Comment by dottjt** [comment]
Which I imagine, would take a user object (which in this case would be the authenticated user) although I'm not sure how you've written it :)

**Comment by danschultzer** [comment]
> Is there a function I can run instead that will just go ahead and send the reset password email?

There's no one function since it depends on both Phoenix and Plug, but you can find how it works in the controller: https://github.com/danschultzer/pow/blob/61d2885d5c232c41cb3e38a5e8538a79aebfd7f9/lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex

This is what you would need to do:

```elixir
# Create token
{:ok, %{token: token, user: user}, conn} = PowResetPassword.Plug.create_reset_token(conn, %{"email" => email})

# Generate URL
url = Routes.pow_reset_password_reset_password_path(conn, :edit, [token])

# Generate e-mail
email = PowResetPassword.Phoenix.Mailer.reset_password(conn, user, url)

# Deliver it
Pow.Phoenix.Mailer.deliver(conn, email)
```

**Comment by dottjt** [comment]
Ahk, thank you very much :)

**Comment by danschultzer** [comment]
No problem!
