### ISSUE TITLE
mix pow.extension.phoenix.gen.templates only generates the reset password template

### ISSUE THREAD

**Issue by foggy1** [danschultzer/pow#144]
If I run `mix pow.extension.phoenix.gen.templates --extension PowEmailConfirmation --extension PowInvitation` (together or one by one), I receive the following error: `No extensions was provided as arguments, or found in config :my_app, :pow configuration.` Running the same command for `PowResetPassword` works fine and generates the templates.

At the moment, I have my app configured as the `web_module` for other non-extension templates, so missing the invitation template in my web context breaks things.

I see this stuff is really new so if I have a minute tomorrow I'd be happy to see if I can make a PR if this just hasn't been implemented for the other extensions yet.

EDIT: Took a peek at the code and Invitations looks like it's implemented, so perhaps something is wrong with my config; here is my config block for Pow:

```
config :my_app, :pow,
  user: MyApp.Users.User,
  repo: MyApp.Repo,
  extensions: [PowResetPassword, PowEmailConfirmation, PowInvitation],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  mailer_backend: MyAppWeb.PowMailer,
  web_module: MyAppWeb
```
EDIT EDIT: I started this thread on `1.0.3` then upgraded to `1.0.4` when I noticed the fresh commits specifically pertaining to `PowInvitation`. Alas, the issue persists with my current config.

**Comment by danschultzer** [comment]
Thanks! I've improved the feedback provided by the mix tasks in #145, so it now outputs a warning for the extension(s) that doesn't seem to have any views/templates. It'll make it easier to understand what's going wrong.

**Comment by danschultzer** [comment]
Just to be clear, running `mix pow.extension.phoenix.gen.templates --extension PowEmailConfirmation --extension PowInvitation` with 1.0.4 works right?

1.0.3 doesn't have the PowInvitation extension.

**Comment by foggy1** [comment]
Running that command on 1.0.4 yields the same result: `No extensions was provided as arguments, or found in `config :my_app, :pow` configuration.`

And actually I set up and confirmed PowInvitation was working on 1.0.3. I couldn't dump the template but I was able to go to `/invitations/new` and send invitations and everything.

**Comment by danschultzer** [comment]
Oh yeah, you are right, 1.0.3 adds PowInvitation extension, and 1.0.4 fixes extension templates support for it.

I tested locally with from scratch with phoenix 1.4, and it generates the extension templates with the same config setup as you got. You should not get this error either way since you are passing the extensions in the arguments, and also have them in your config settings.

Can you offer some more information on your setup so I can try replicate the issue? I can't really think of a reason why the extension arguments aren't picked up.

**Comment by foggy1** [comment]
It was cached build stuff! Clearing my `deps` and `_build` before upgrading to 1.0.4 fixed it.

thanks!
