### ISSUE TITLE
Persistent Session for API security

### ISSUE THREAD

**Issue by Immortalin** [danschultzer/pow#167]
Hi! Thanks for building this! İs it acceptable to use persistent sessions for API security? (Think mobile app backends)

**Comment by danschultzer** [comment]
It all depends on what kind of app you are building. If you are using sessions for your API already, then there isn't any difference by adding persistent session, it will be equally secure just with a longer TTL.

However, I would recommend that you use something like `Phoenix.Token` or Guardian rather than sessions. Sessions makes sense in a browser setup, but since you would manage both client and server with a mobile app it probably makes more sense to handle it all with API keys (e.g. like an oauth2 setup).

It has been discussed in https://github.com/danschultzer/pow/issues/153, and someone actually did use sessions in their mobile app too in https://github.com/danschultzer/pow/issues/154.

**Comment by Immortalin** [comment]
Understood thank you!

**Comment by Immortalin** [comment]
The most tricky thing is CSRF.

**Comment by danschultzer** [comment]
You can bypass all the Phoenix stuff by using the plug methods in [custom api controllers](https://github.com/danschultzer/pow/blob/master/guides/CUSTOM_CONTROLLERS.md#controllers):

```elixir
def create(conn, %{“user” => user_params) do
  conn
  |> Pow.Plug.authenticate_user(user_params)
  |> case do
     # Handle response
  end
end
```

You would need to manually call the appropriate method in the persistent session plug module to enable it, but this should give you an idea of how to work with Pow in an API.

**Comment by danschultzer** [comment]
Then you can remove CSRF completely from the API routes.

**Comment by Immortalin** [comment]
But that means API routes are vulnerable to CSRF.

**Comment by Immortalin** [comment]
İ am trying to stick to sessions instead of rolling Phoenix.Token because it means I will have to write the refresh logic etc.

**Comment by danschultzer** [comment]
The `Phoenix.Token` method is pretty simple if you just [leverage Pow](https://github.com/danschultzer/pow#authorization-plug). Pow will regenerate the id for you assuming that you use the plug methods, and you can add in logic to regenerate the id after certain amount of time. You would need to make sure that your app can receive the token (so e.g. you assign the token in the conn, and when you output json you remember to include the token for the app to retrieve).

This is probably the best way, and I’m thinking of maybe having this as a guide or even include a `Pow.Plug.Token` module.

With session/cookie, yeah, CSRF is best practice. The CSRF is all Phoenix though and you would have to check the Phoenix docs for how long it perists. Pow doesn’t have any knowledge of the CSRF. I would ignore it if I control both client and server, and instead use an API key to limit access to only my client.

**Comment by Immortalin** [comment]
Perfect, I will try it out tomorrow. Thanks so much :)

**Comment by Immortalin** [comment]
A Pow.Plug.Token module would be really great addition.

**Comment by Immortalin** [comment]
For [this](https://github.com/danschultzer/pow/issues/167#issuecomment-485443333) do you think you can include a JSON endpoint with pow? Because I imagine API auth is going to be increasingly popular and it's impractical to roll a custom controller everytime.

**Comment by Immortalin** [comment]
I am currently using the Guardian plug example with Guardian DB because Phoenix.token requires too much additional code to do login logic. I wish there's a way to unify the sessions of Pow, Phoenix and Guardian all into Mnesia. Right now Pow is absolutely golden and I don't have to worry about load balancer configs etc. but the same can't be said of Phoenix's server side sessions and Guardian DB. Any suggestions or advice? It's difficult to scale horizontally when not all ephemeral data are in Mnesia. You end up having to worry about stuff like CSRF and sticky sessions in load balancers because data doesn't automatically sync. Not to mention lack of autoexpiry in server sessions. Any suggestions?

**Comment by danschultzer** [comment]
Yeah, I plan to write a guide as I will start a project soon that will use Pow in a API context. I'm not sure having controllers for JSON API would be the right approach, but I'm thinking this through and will be working on Pow to make API integration a no-brainer like Pow currently is for regular HTML web interface. You are right that it's a very common use case, and I would love to see Pow making it super easy.

I'll probably work with Flutter and GraphQL for my project. It'll take a while before I got something ready, so any feedback for your approach and experiences are helpful.

**Comment by Immortalin** [comment]
I am actually planning to send a pull request for the session controller using `get_format` and return JSON. This way you can point the JSON routes to the same controller.

**Comment by Immortalin** [comment]
The authorization plug however does not cover token refresh etc. in any form. I am using your guardian example with Guardian db for revocation. If you can provide a phoenix.token plug, that would make things a lot more efficient.
