### ISSUE TITLE
Module Routes is not Available

### ISSUE THREAD

**Issue by jasonbarbee** [danschultzer/pow#178]
I'm trying out the library, things were rolling well until I generated templates for registration and sessions.
First off, 
Elixir 1.8.1
Phoenix 1.3
Fresh master of POW as of today.

Using everything compiled it worked, I registered a user, but after I ran the 
`mix pow.phoenix.gen.template`
I hit URL/registration/new I get a traceback. The template calls this

`<span><%= link "Register", to: Routes.pow_registration_path(@conn, :new) %></span>`

```
UndefinedFunctionError at GET /registration/new
function Routes.pow_session_path/2 is undefined (module Routes is not available)

```
So investigating this, I triple checked the normal issues from the git issue history and thread on elixirforum.

```
 scope "/" do
    pipe_through :browser 

    pow_routes()
  end

```

 ```
 config :myapp, :pow,
  user: myapp.Users.User,
  repo: myapp.Repo,
  web_module: myappWeb

```

```
plug Plug.Session,
    store: :cookie,
    key: "_myappapi_key",
    signing_salt: "randomstring"

    plug Pow.Plug.Session, otp_app: :myapp
    plug myappWeb.Router
```

I dig through the guides and code, try to make a custom controller (along with routes_backend) passthrough to push down the Routes module down to the template view, no luck.

```
defmodule myappWeb.Pow.Routes do
  use Pow.Phoenix.Routes
  alias myappWeb.Router.Helpers, as: Routes

end
```
added  to my config to activate it 
`routes_backend: myappWeb.Pow.Routes`
No luck. Same traceback.

I change the template to my new module name

`<span><%= link "Register", to: myappWeb.Pow.Routes.pow_registration_path(@conn, :new) %></span>`
Different traceback - 
```
UndefinedFunctionError at GET /session/new
function myappWeb.Pow.Routes.pow_registration_path/2 is undefined or private
```
Aha. Last - I remove the pow_ prefix - and then it works. 

`<span><%= link "Register", to: CallbackapiWeb.Pow.Routes.registration_path(@conn, :new) %></span>`

I'm not an expert, and just testing this library, but something seems wrong here.  The Routes helper is not usable for me from the generators.

Steps to repeat - 
All the compile time templates work fine as long as web_module is not defined. 
If I generate the templates again and activate web_module, I start off with a broken Routes module reference and need to overwrite with my module names.

What am I doing wrong?

**Comment by danschultzer** [comment]
Your view macro in Phoenix is missing the Routes alias. Since Phoenix 1.4 it's now aliased rather than imported:

```elixir
defmodule MyAppWeb do
  # ...

  def view do
    quote do
      use Phoenix.View,
        root: "lib/my_app_web/templates",
        namespace: MyAppWeb

      # Import convenience functions from controllers
      import Phoenix.Controller, only: [get_flash: 1, get_flash: 2, view_module: 1]

      # Use all HTML functionality (forms, tags, etc)
      use Phoenix.HTML

      import MyAppWeb.ErrorHelpers
      import MyAppWeb.Gettext
      alias MyAppWeb.Router.Helpers, as: Routes
    end
  end

  # ...
end
```

You can resolve this by either adding the alias, or just remove `Routes.` so it looks like this:

```elixir
<span><%= link "Register", to: pow_registration_path(@conn, :new) %></span>
```

**Comment by jasonbarbee** [comment]
You nailed it. I updated to Phoenix 1.4.0, I still got an error with Routes not found, but I removed "Routes." and used this syntax and it worked correctly. 
`<span><%= link "Register", to: pow_registration_path(@conn, :new) %></span>`

I think you might still want to revise the templates you generate, because even freshly generating them on Phoenix 1.4 I still get the Routes not found, and have to revise the template. The current repo does not seem to generate a correct template for either 1.3 or 1.4.

**Comment by danschultzer** [comment]
> So while Pow works with Phoenix 1.3 it uses the conventions from Phoenix 1.4. I do encourage you to upgrade to 1.4 if possible.

You need a fresh Phoenix 1.4 project too since just upgrading doesn't update the `view` macro to the default generated one in Phoenix 1.4. The above code is what was generated by Phoenix 1.4 for a demo app I got running with Pow.

If you follow this 1.3 to 1.4 upgrade guide, the default generated templates should be working: https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e#add-a-routes-alias-and-update-your-router-calls

**Comment by jasonbarbee** [comment]
Upgrade to 1.4 worked, generators are working as expected. Thanks!
