### ISSUE TITLE
Custom render layout template.

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#182]
I currently use a different layout template for my registration / session view than is what is my app's default layout. 

IE: This was how I render my own custom layout when using my own auth lib

```
  render("new.html", layout: {PolymorphicProductionsWeb.LayoutView, "full-header.html"},
```

from the looks of it there is nothing allowing me customization of which layout to use when calling render from the controller. 

https://github.com/danschultzer/pow/blob/master/lib/pow/phoenix/controllers/session_controller.ex#L24-L30

Thoughts?

**Comment by danschultzer** [comment]
You can use [`Phoenix.Controller.put_layout/2`](https://hexdocs.pm/phoenix/Phoenix.Controller.html#put_layout/2). In your `router.ex` you can set it as a pipeline:

```elixir
pipeline :pow_layout do
  plug :put_layout, {PolymorphicProductionsWeb.LayoutView, “full-header.html”}
end

scope "/" do
  pipe_through [:browser, :pow_layout]
  
  pow_routes()
end
```

**Comment by joshchernoff** [comment]
Awesome, thank you! Thats really cool I had no idea you could do that.
