### ISSUE TITLE
Question: Admins editing registrations and the requirement of current password. 

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#187]
Whats the best pattern to allow for admins to edit registrations.  
IE override current_password requirement. 

Do I just need to make a new changeset in my user schema?

**Comment by danschultzer** [comment]
Yeah, make a new changeset method for admin.

The default changeset [can be changed](https://github.com/danschultzer/pow/blob/bb1cec836fe4743fb007e9dbd56bc8afde92e7e7/lib/pow/ecto/schema.ex#L59-L78) so current password isn't required, but it's much better to just have an explicit changeset method for admin (you can always DRY up the two with a combined private method).

**Comment by joshchernoff** [comment]
Thanks
