### ISSUE TITLE
Trying to use bamboo for mailer

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#188]
Been hitting a wall when trying to use bamboo as a mailer, specifically around customizing the templates. 

Heres a branch of my work 
https://github.com/PolymorphicProductions/polymorphic.productions/tree/replace_auth

I suspect I'm not setting up my  `web_mailer_module: PolymorphicProductionsWeb` correctly.
because I'm seeing 
```
function PolymorphicProductionsWeb.PowResetPassword.MailerView.subject/2 is undefined (module PolymorphicProductionsWeb.PowResetPassword.MailerView is not available)
``` 
at `subject = view_module.subject(template, view_assigns)` 

I assume I'm not meant to implement subject/2 on my own. 

Any tips?

**Comment by danschultzer** [comment]
Seems like you haven't generated the templates/views? https://github.com/danschultzer/pow#modify-mailer-templates

```bash
mix pow.extension.phoenix.mailer.gen.templates --extension PowResetPassword --extension PowEmailConfirmation
```

**Comment by joshchernoff** [comment]
Ah thank you. that was the first part of my issue though I still have more questions around using a custom layout for my emails. 

Using bamboo I had setup a custom layout via ` put_html_layout({LayoutView, "email.html"})`

ie 

https://github.com/PolymorphicProductions/polymorphic.productions/blob/809d8820d966948e850e3c33acdd7df45ac0f5e7/lib/polymorphic_productions_web/email.ex#L37-L45

Which I initially translated into something like. 

```
defmodule PolymorphicProductionsWeb.PowMailer do
  use Pow.Phoenix.Mailer
  require Logger

  @impl true
  def cast(%{user: user, subject: subject, text: text, html: html, assigns: _assigns}) do
    # Build email struct to be used in `process/1`

   new_email()
    |> to({"Josh Chernoff", "jchernoff@polymorphic.productions"})
    |> from({from_name, user.email})
    |> put_html_layout({LayoutView, "email.html"})
    |> subject(subject)
    |> render("contact.html")
  end

  @impl true
  def process(email) do
    # Send email
    email
    |> Mailer.deliver_now()
  end
end
```
but then I found that `Pow.Phoenix.Mailer.Mail.new/4` is doing the rendering of the template. 
https://github.com/danschultzer/pow/blob/331d2e838c5c0533580e19ac5d5ce54774d47a68/lib/pow/phoenix/mailer/mail.ex#L19-L35

It does not look like new/4 will allow for a custom layout so I assume that some work needs to be done to allow this.  I'd be happy to take a stab at it though I'd like your thoughts on that.

**Comment by danschultzer** [comment]
Yeah this is a great use case, and definitely need to be easy to set up.

If you got a solution in mind please dig into it. I'll look into how this can be done also. My gut feeling is that this is due to how controllers work, and there is no controllers for mailer just the `Pow.Phoenix.Mailer.Mail`, so layout can't really be set anywhere (like how it's done with plugs in controller/router).

**Comment by danschultzer** [comment]
FYI with custom mailer template [`Phoenix.View macro`](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/view.ex) is used, so it's just the `render` methods defined in the use macro there. Doesn't seem like there is any way to pass on layout unfortunately, it has to be passed as an assign to the method.

**Comment by danschultzer** [comment]
I've added an experimental PR in #190. However, I've doubts about it. I think maybe the better way of handling it is to use the plug mechanism. E.g. you can set the layout in the conn like so:

```elixir
pipeline :pow_email_layout do
  plug :put_email_layout, {MyAppWeb.LayoutView, :email}
end

scope "/" do
  pipe_through [:browser, :pow_email_layout]
  
  pow_routes()
end

def put_email_layout(conn, layout) do
  assign(conn, :email_layout, layout)
end
```

The large issue here is that there is no default email handling in Phoenix, and I haven't really thought all through how a mailer should work. I think it should align as much as possible to how phoenix controllers work, but it's still a separate domain so I'm not sure how the plugs/conn can work together with the pow mailer.

**Comment by danschultzer** [comment]
Ok, got a better PR up with #191. It feels much closer to how Phoenix works 😄 I think it's ready to be merged in, but I'll just wait a little to see if I got it right. Feel free to try it out and check the docs.

**Comment by joshchernoff** [comment]
Awesome I will get you some feedback by tonight and also wow thank you! 🙏

**Comment by danschultzer** [comment]
I've looked it through, and I'm happy with how it is. I've merged it to master, and will publish a new release soon.
