### ISSUE TITLE
Update conn.assigns.current_user

### ISSUE THREAD

**Issue by neneboe** [danschultzer/pow#197]
Thanks @danschultzer for creating this lib!

I'm in the process of swapping out Coherence, and running into a problem in development where I can't get the conn.assigns.current_user to update for more than one request.

After a user signs up, I assign them a `:payment_id`.

  * If I do a Repo.get of the user, the payment_id is there.
  * If I call `Pow.Plug.Session.do_create(conn, user, [])` with the updated user in a controller action, the payment_id is there for that one action, but not there for any other actions.
  * Same with Pow.Plug.assign_current_user(conn, user, []), which I gather from the docs is used pretty much exclusively for testing, right?

Is this the expected behavior of `Pow.Plug.Session.do_create\3`, or is there another way to update the assigns current_user?

**Comment by neneboe** [comment]
Ah, sorry, missed the part where you have to fetch the config first.

**Comment by danschultzer** [comment]
You got this solved, but I'm curious, do you assign the payment id in the changeset or how? Sounds like it something that happens after the user is created, and that's why you need to reassign it.

**Comment by neneboe** [comment]
Yep, exactly. Once the user is created, I send an api request to create an account with the payment processor and save the ID it sends back. I use a separate changeset that allows updates to only the payment ID field.

**Comment by danschultzer** [comment]
I see. Then yeah, `Pow.Plug.Session.do_create/3` is the one you want to call to update the user stored in the credentials cache, and yes, you need to load the config before calling that method.

Depending on your implementation you may also be able to keep the payment handling in the original changeset if it's something that should happen always during sign up. You can differentiate between persisted and new users by using `Ecto.get_meta/2` or just looking up `@changeset.__meta__.state`:

```elixir
Ecto.get_meta(user, :state) == :built
```

**Comment by neneboe** [comment]
Thank you for the suggestion, that is a much cleaner way to do it. Also, side note, I definitely would like to see this lib keep going, so if there's ever anything I can do to help out please hit me up.
