### ISSUE TITLE
allow mapping password_hash to another field?

### ISSUE THREAD

**Issue by chevinbrown** [danschultzer/pow#20]
For those of us migrating from devise, we have `encrypted_password` as a field.

For most fields, I can do `field :email, :string, [source: :other_field]`.

Think it would be possible to add in a config option for `pow_fields()` like `pow_fields(password_hash: :encrypted_password`?

**Comment by danschultzer** [comment]
Would you need to keep both the rails and phoenix app running at the same time? If not, then I think the best would be to create a migration to rename the column.

It would be pretty easy to add a `password_hash_field` like the existing `user_id_field` configuration, but I'll check if there is a better way of handling this situation.

**Comment by chevinbrown** [comment]
Yes, we'd be going for the incremental migration--pulling over individual contexts one at a time, while keeping more complex logic that's established in the rails app--smaller surface area gets moved first, then we'll step up slowly over time as the phoenix app is proved stable.

I believe a lot of rails apps will be taking this approach (and migrating from devise).

**Comment by chevinbrown** [comment]
I will note, it'll work just fine to forgo the `pow_user_fields()` in my schema and do it explicitly. 😃 

```
  schema "admin_users" do
    field :email, :string
    field :password, :string, virtual: true
    field :current_password, :string, virtual: true
    field :confirm_password, :string, virtual: true
    field :password_hash, :string, [source: :encrypted_password]
end
```

**Comment by danschultzer** [comment]
It's exactly what I'm testing out 😄 I like if it could be something as explicit. Maybe like this:

```elixir
schema "admin_users" do
  field :password_hash, :string, [source: :encrypted_password]

  pow_user_fields()
end
```

And the `pow_user_fields/0` will just ignore that field (the Ecto `field/3` macro registers a module attribute with all the fields so would be easy enough to ignore).

**Comment by danschultzer** [comment]
I've got a PR up: https://github.com/danschultzer/pow/pull/21

**Comment by chevinbrown** [comment]
I approve. 👏
