### ISSUE TITLE
Unable to use 'Pow.Plug.authenticate_user(conn, params)' method for my API request.

### ISSUE THREAD

**Issue by vetrivendhan48** [danschultzer/pow#200]
Hi team,

I facing an issue with a POW method. I already made setup for default HTML authentication and role_base access using POW. But when I tried to write my own plugs and session controller for the API request I facing few issues. When I tried to use the following method

```
**Code**
  Pow.Plug.authenticate_user(conn, params)
```
were values in the params will be
`%{"id" => "c9177159-bab9-4e2f-8fb2-7cc2fd27c968", "password" => "1234567890"}`

 I facing the following error

**Error stack:**

```
[error] #PID<0.450.0> running CfcWebappWeb.Endpoint (connection #PID<0.449.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /api/login?id=c9177159-bab9-4e2f-8fb2-7cc2fd27c968&password=1234567890
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.Break.trim_leading/1
        (elixir) lib/elixir/unicode/properties.ex:288: String.Break.trim_leading(nil)
        (elixir) lib/string.ex:1114: String.trim/1
        (pow) lib/pow/ecto/schema.ex:265: Pow.Ecto.Schema.normalize_user_id_field_value/1
        (pow) lib/pow/ecto/context.ex:168: anonymous fn/2 in Pow.Ecto.Context.normalize_user_id_field_value/2
        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
        (pow) lib/pow/ecto/context.ex:159: Pow.Ecto.Context.get_by/2
        (pow) lib/pow/ecto/context.ex:100: Pow.Ecto.Context.authenticate/2
        (pow) lib/pow/plug.ex:82: Pow.Plug.authenticate_user/2
        (cfc_webapp) lib/cfc_webapp_web/controllers/user_controller.ex:54: CfcWebappWeb.UserController.authenticate/2
        (cfc_webapp) lib/cfc_webapp_web/controllers/user_controller.ex:1: CfcWebappWeb.UserController.action/2
```

Any help/suggestions are welcome.
Thanks,
Vetri

**Comment by danschultzer** [comment]
It's because you're missing the user id field in your params (defaults to `:email`). This shouldn't blow up though, I'll set up a PR so it'll just refuse authentiation when user id value is nil.

**Comment by danschultzer** [comment]
Merged fix. If you pull from `master`, it should now just return nil rather than raising an exception 😄

**Comment by danschultzer** [comment]
Also if you wish to use the `:id` as the user id then you have to update the configuration:

```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema,
    user_id_field: :id

  schema "users" do
    pow_user_fields()

    timestamps()
  end
end
```

If you already use another user id field (e.g. email) for sign up, and just in this case wish to authenticate users with the id instead, then you'll have to set up the logic yourself. It could look like this:

```elixir
def authenticate_with_id(conn, %{"id" => id, "password" => password}) do
  config = Pow.Plug.fetch_config(conn)

  case do_authenticate(id, password, config) do
    nil  -> conn
    user -> config[:mod].do_create(conn, user, config)
  end
end

defp do_authenticate(id, password, config, conn) do
  [id: id]
  |> Pow.Ecto.Context.get_by(config)
  |> verify_password(password)
end

defp verify_password(nil, password), do: nil
defp verify_password(user, password) do
    case user.__struct__.verify_password(user, password) do
      true -> user
      _    -> nil
    end
end
```

**Comment by vetrivendhan48** [comment]
Hi @danschultzer ,

Thanks for your quick reply. It works. I prefer the email way of authentication.
Now I can able to see the session key in the response. And special thanks for your sample codes. As I am a noob to Elixir this helps me a lot.

Is any example POW library used project is available, with API/(ReactJS or React native) implementation?

Regards,
@vetrivendhan48

**Comment by danschultzer** [comment]
There're [some who have used Pow](https://github.com/danschultzer/pow/search?q=graphql&type=Issues) with GraphQL (absinthe), and I'm planning to [write a guide](https://github.com/danschultzer/pow/issues/176) on how to set up Pow with an API.

This issue in particular show some example code: https://github.com/danschultzer/pow/issues/61
