### ISSUE TITLE
Broken Hex.pm docs (links)

### ISSUE THREAD

**Issue by dweremeichik** [danschultzer/pow#209]
Hi @danschultzer awesome project! I noticed while using the docs on hex.pm, any of the links that reference the guide or lib folders are broken. For example any of the links in the [extensions](https://hexdocs.pm/pow/Pow.html#extensions) section. I started to put together a PR, but I'm not sure which direction you would like to go in. Should links in the docs point to the files in the master branch here on GitHub, or should they point to their respective pages on hex? In either case, I would imagine that they'd need to be hard links (instead of relative) due to GitHub using markdown files, and hex/ex_doc generating html files (that way the links work on both systems).

**Comment by danschultzer** [comment]
Thanks!

I haven’t found any solution how to fix these broken links. The links are relative because that way you can look at a certain version ref on github and it’ll keep the link url within that tag. If they are hardcoded to master then previous releases may have broken links too.

There was an issue about it on ExDoc, where they decided to not fix it: https://github.com/elixir-lang/ex_doc/issues/889

I would love for these links to work in the generated docs.

**Comment by danschultzer** [comment]
These broken links bothered me enough to make me create a custom parser in #211. If you pull that branch and generate the docs with `mix docs`, then all the links should be working, and it the links will still work on github :smile:

**Comment by dweremeichik** [comment]
Wow, that's awesome! I didn't realize that could be done. I've pulled the docs branch, and it works great. One thing I've noticed however is the Exceptions section is missing.

**Comment by danschultzer** [comment]
Great! I'll get it cleaned up and merged in ASAP. I removed the exceptions since there was no `@moduledoc` for them.

**Comment by dweremeichik** [comment]
Doh.. I should have clicked further in. That makes sense now. 

n.b. Thanks for everything you are doing here. I had started to roll my own solution till I came across Pow. I have to say, Pow is making authentication a much nicer experience than I've worked with in the past.

**Comment by danschultzer** [comment]
That's great to hear, thanks! I've worked hard to make Pow ergonomic to work with. If you find anything that can be improved, don't hesitate to open an issue or PR!

**Comment by danschultzer** [comment]
Just released `v1.0.10`, and the links now works at https://hexdocs.pm/pow/ 😄
