### ISSUE TITLE
Pow.Phoenix.RegistrationController not available?

### ISSUE THREAD

**Issue by wdiechmann** [danschultzer/pow#22]
I've followed the **Getting Started (Phoenix)** section in the README to the letter but when I 'fire up' the `iex -S mix phx.server` and try going to localhost:4000/registration/new I'm told that

```
$ iex -S mix phx.server
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

[info] Running PowwowWeb.Endpoint with Cowboy using http://0.0.0.0:4000
Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 10:25:47 - info: compiled 6 files into 2 files, copied 3 in 874 ms
[info] GET /registration/new
[info] Sent 500 in 69ms
[error] #PID<0.398.0> running PowwowWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: GET /registration/new
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function PowwowWeb.Pow.Phoenix.RegistrationController.init/1 is undefined (module PowwowWeb.Pow.Phoenix.RegistrationController is not available)
        PowwowWeb.Pow.Phoenix.RegistrationController.init(:new)
        (powwow) lib/powwow_web/router.ex:1: anonymous fn/1 in PowwowWeb.Router.__match_route__/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (powwow) lib/powwow_web/endpoint.ex:1: PowwowWeb.Endpoint.plug_builder_call/2
        (powwow) lib/plug/debugger.ex:122: PowwowWeb.Endpoint."call (overridable 3)"/2
        (powwow) lib/powwow_web/endpoint.ex:1: PowwowWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/Walther/tmp/meetup/powwow/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
[info] GET /
[debug] Processing with PowwowWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 12ms
```

Any ideas?

**Comment by danschultzer** [comment]
You probably have the routes set up like this:

```elixir
  scope "/", Powweb do
    pipe_through :browser

    pow_routes()
  end
```

You should remove the `Powweb` namespace so it looks like this:

```elixir
  scope "/" do
    pipe_through :browser

    pow_routes()
  end
```

**Comment by wdiechmann** [comment]
I did too - but it did not help changing the namespace like your suggestion :(

I'm on macOS 10.13.5, Erlang 21.0.8, Elixir 1.7.3 if that might have anything to do with it?

**Comment by danschultzer** [comment]
I’ve almaot thr same setup. Can you post the content of `router.ex`?

**Comment by danschultzer** [comment]
Great! That's where you put your protected resources that requires authentication to view (e.g. a user dashboard).

**Comment by danschultzer** [comment]
No problem!

I usually keep my app paths in a separate scope like this:

```elixir
scope "/" do
  pipe_through :browser

  pow_routes()
end

scope "/", PowWeb do
  pipe_through :browser

  get "/", PageController, :index
end
```

**Comment by danschultzer** [comment]
`v1.0.1` has been released that raises an error with instructions when the scope is incorrect to prevent this confusion :rocket:

**Comment by amitvchaudhary** [comment]
@danschultzer 

I still get the same error. I am trying to create it for API and following https://hexdocs.pm/pow/api.html#content doc.

Request: POST /registration
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function RegistrationController.init/1 is undefined (module RegistrationController is not available)
        RegistrationController.init(:create)
        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (interyoo_api 0.1.0) lib/interyoo_api_web/endpoint.ex:1: InteryooApiWeb.Endpoint.plug_builder_call/2
        (interyoo_api 0.1.0) lib/plug/debugger.ex:136: InteryooApiWeb.Endpoint."call (overridable 3)"/2
        (interyoo_api 0.1.0) lib/interyoo_api_web/endpoint.ex:1: InteryooApiWeb.Endpoint.call/2
        (phoenix 1.6.6) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) d:/Projects/Interyoo/Code/phoenix/interyoo_backend/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) d:/Projects/Interyoo/Code/phoenix/interyoo_backend/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) d:/Projects/Interyoo/Code/phoenix/interyoo_backend/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


router.ex
------------
  pipeline :api do
    plug :accepts, ["json"]
    plug InteryooApiWeb.ApiAuthPlug, otp_app: :interyoo_api
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: InteryooApiWeb.ApiAuthErrorHandler
  end

  scope "/" do
    pipe_through :api

    # pow_routes()
    resources "/registration", RegistrationController, singleton: true, only: [:create]
    resources "/session", SessionController, singleton: true, only: [:create, :delete]
    post "/session/renew", SessionController, :renew
  end
