### ISSUE TITLE
Unsure how to fix "Pow configuration not found in connection"

### ISSUE THREAD

**Issue by joelbyler** [danschultzer/pow#222]
Following the readme for installation and currently seeing [this error](https://github.com/danschultzer/pow/blob/master/lib/pow/plug.ex#L179) and I'm unsure of how to correct it.  I'm glad to follow up with a PR to add some more clarity to the message or perhaps add some more troubleshooting info in the README if it helps to keep this from coming up again.

**Comment by danschultzer** [comment]
Did you follow [the instructions](https://github.com/danschultzer/pow/blob/master/README.md#phoenix-app) adding the `Pow.Plug.Session` plug to your endpoint?

The error explains that no configuration has been set for Pow in the conn. That usually, but not always, means that no Pow plug was called (like `Pow.Plug.Session`).

PR or suggestions that improves the feedback is most welcome!

**Comment by joelbyler** [comment]
Hmm...  I thought I did.  I'll restart on a fresh new hello world app and walk thru those instructions.  There's definitely a `plug Pow.Plug.Session, otp_app: :my_app` in the endpoint.

**Comment by joelbyler** [comment]
Ah, its the order that's important.  I rushed thru too quickly, that new plug needs to be right after  `plug Plug.Session`.  I had it and the end of the file, after the router plug.

**Comment by danschultzer** [comment]
Yeah, in that case the routes would be called before the Pow plug, so no Pow config would have been set in the conn.

**Comment by joelbyler** [comment]
Probably more of a common sense thing and I think the README already mentions to put it where it should be.  I'll close.  Thanks for the help @danschultzer !  Feel free to reopen if you disagree and I can try and submit a PR to clarify.

**Comment by maysam** [comment]
the instruction for API says not to do the endpoint.ex modifications
