### ISSUE TITLE
ReloadUser plug reloads user only for current action

### ISSUE THREAD

**Issue by popo63301** [danschultzer/pow#231]
Hello!

I'm using a ReloadUser plug copied from the guide [sync_user](https://github.com/danschultzer/pow/blob/master/guides/sync_user.md) . The problem is that the plug is assigning the updated version of the user only for the current action but if I don't call this plug for an other action, what we get is the previous user. The function `Pow.Plug.assign_current_user` does not update the user once and for all for the conn, it updates it only for the current action. 

Which function should I use to update the user once and for all ?

Thanks

**Comment by popo63301** [comment]
I found a solution that is working. I just used the last lines of Sync_user.

Instead of using:
```elixir
Pow.Plug.assign_current_user(conn, reloaded_user, config)
```

I use:
```elixir
plug = Pow.Plug.get_plug(config) 
plug.do_create(conn, reloaded_user, config)
```

It works but I wonder if this is how I should proceed. Anyway, it works for me so I think that's okay. If there should be a modification in the documentation, then I can do a quick PR.

**Comment by danschultzer** [comment]
You have to handle it by following the [“Update user in credentials cache”](https://github.com/danschultzer/pow/blob/master/guides/sync_user.md#update-user-in-credentials-cache). If you want to always have the updated user in all actions everywhere, then I would recommend creating a plug module that loads the user from the db and reassigns the current user. It can then be added after `plug Pow.Plug.Session` In your endpoint.

The guide does details the important distinction that the default current user is the cached credential and not the actual user data in the db. So if it should always be as it is in the DB then it’s best to just load the user on every request. Maybe it can be made clearer.

**Comment by danschultzer** [comment]
The way you have set it up it’ll update the cache on a request in that controller. But it’s probably not the intention, since the cache will only be updated in that controller, and otherwise it may be old data (all other controllers doesn’t have the plug method call).

**Comment by popo63301** [comment]
Okay. In my case, I use some specific actions to trigger an update of the user cached. I don't need to reload the user cache in all actions of my app though. 

Maybe, I can add some lines to explain precisely the behaviours of the plugs of the guide when I have a moment.

Thank you

**Comment by danschultzer** [comment]
In that case, then yeah, the above works as long as the plug is called after the update action. I would recommend calling the `do_create/3` method as close to the user update action as possible like detailed in the “Update user in credentials cache” section, rather than rely on current assigned user in conn.

**Comment by popo63301** [comment]
I'll give some details of my situation.

I'm updating my user data from the database thanks to a function I call through the iex shell. This function changes the user from user role to admin role. And as I am lazy to update the user info by logging out, I changed the reload user to update definitely the user. Is it more clear? 😄

**Comment by danschultzer** [comment]
Oh yeah, now I understand. You can update the sessions for a user by doing the following:

```elixir
config       = [otp_app: :my_app]
store_config = [backend: Pow.Config.get(config, :cache_store_backend, Pow.Store.Backend.EtsCache)]

case Pow.Store.CredentialsCache.sessions(config, backend_config, user) do
  []                              -> :ok
  [session_id | _rest] -> Pow.Store.CredentialsCache.put(config, backend_config, session_id, user)
end
```

This is from the top of my head, not sure if it will work but something like this should work 😄 It'll update the cached value. Do note that it'll extend the TTL for the first session. The sessions are short lived so it shouldn't be too much of an issue though.

**Comment by popo63301** [comment]
Oh okay, very nice alternative. Thanks for this snippet. 😁
