### ISSUE TITLE
How to set expiration for session persistence cookie

### ISSUE THREAD

**Issue by owenstrevor** [danschultzer/pow#235]
Hello, I'd like to set the session persistence to expire after 10 years instead of 1 month. How can this be done?

**Comment by danschultzer** [comment]
You can set `:persistent_session_cookie_max_age` in your config or pass it as an option to the `PowPersistentSession.Plug.Cookie`: https://hexdocs.pm/pow/PowPersistentSession.Plug.Cookie.html#module-configuration-options

```elixir
plug PowPersistentSession.Plug.Cookie, persistent_session_cookie_max_age: Integer.floor_div(:timer.hours(24) * 365 * 10, 1000)
```

The value has to be in seconds.

**Comment by danschultzer** [comment]
Oh, just realized that the TTLis not carried over to the cache. So the above won’t work.  Let me open a PR to fix this.

**Comment by danschultzer** [comment]
This should work, but I want to unify the TTL, with the plug ultimately deciding what TTL to use in the cache:

```elixir
ttl = :timer.hours(24) * 365 * 10

plug PowPersistentSession.Plug.Cookie,
  persistent_session_cookie_max_age: Integer.floor_div(ttl, 1000),
  persistent_session_store: {PowPersistentSession.Store.PersistentSessionCache, backend: Pow.Store.Backend.EtsCache, ttl: ttl}
```

**Comment by danschultzer** [comment]
Sorry for the delay, I have been pretty busy the last days. Got a fix up in #236 that makes it possible to set the TTL for both by just setting `persistent_session_ttl: :timer.hours(24) * 365 * 10`

**Comment by joepstender** [comment]
Sorry to respond to a closed issue. Shouldn't this configuration option be added to the documentation?

**Comment by danschultzer** [comment]
@joepstender oops, I first saw this reply now. It’s documented here: https://hexdocs.pm/pow/1.0.15/PowPersistentSession.Plug.Cookie.html#module-configuration-options
