### ISSUE TITLE
ControllerCallbacks with extensions

### ISSUE THREAD

**Issue by albertosramires** [danschultzer/pow#240]
Good day,
In my project I'm using all pow extensions and I need a couple of custom controller callbacks so I'm doing the following:

```
defmodule LfWeb.Pow.ControllerCallbacks do
  use Pow.Extension.Phoenix.ControllerCallbacks.Base

  @impl true
  def before_respond(Pow.Phoenix.RegistrationController, :create, {:ok, user, conn}, config) do
    Pow.Extension.Phoenix.ControllerCallbacks.before_respond(...put_info_in_conn...)
  end

  @impl true
  def before_respond(Pow.Phoenix.SessionController, :create, {:ok, conn}, config) do
    Pow.Extension.Phoenix.ControllerCallbacks.before_respond(... put_info_in_conn...)
  end

  @impl true
  def before_respond(Pow.Phoenix.SessionController, :delete, {:ok, conn}, config) do
    Pow.Extension.Phoenix.ControllerCallbacks.before_respond(... remove_info_from_conn...)
  end
```

My config is the following:

```
config :lf_web, :pow,
  user: Lf.Users.User,
  repo: Lf.Repo,
  web_module: LfWeb,
  routes_backend: LfWeb.Pow.Routes,
  extensions: [PowEmailConfirmation, PowResetPassword, PowPersistentSession, PowInvitation],
  web_mailer_module: LfWeb,
  mailer_backend: LfWeb.Mailer,
  controller_callbacks: LfWeb.Pow.ControllerCallbacks
```

This seems to be working for the email confirmation on register `:create` because I'm calling `Pow.Extension.Phoenix.ControllerCallbacks.before_respond` on my implementation but it doesn't seem to work for register `:update` because I have no custom implementation (by not working I mean that no email is being sent or flash placed in the conn, database field `unconfirmed_email` is being updated correctly though).
If I add the following it works correctly but I get `this clause cannot match because a previous clause at line XX always matches` warnings so I assume I'm doing something incorrectly:

```
@impl true
  def before_respond(controller, action, results, config),
    do:
      Pow.Extension.Phoenix.ControllerCallbacks.before_respond(
        controller,
        action,
        results,
        config
      )

  @impl true
  def before_process(controller, action, results, config),
    do:
      Pow.Extension.Phoenix.ControllerCallbacks.before_process(
        controller,
        action,
        results,
        config
      )
```

I noticed that in the `Pow.Extension.Phoenix.ControllerCallbacks` docs it mentions:

```
## Usage
use Pow.Plug.Session,
        controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
        extensions: [PowExtensionA, PowExtensionB]
```

Which I don't really have anywhere, is this needed? Am I missing something?

**Comment by danschultzer** [comment]
`Pow.Extension.Phoenix.ControllerCallbacks.Base` is only used for individual extension callbacks. It [defines catch-all fallbacks](https://github.com/danschultzer/pow/blob/c252cf68fa59dad86aca115ef0062c0536d2424c/lib/pow/extension/phoenix/controllers/controller_callbacks/base.ex#L36-L44), and that's why you get the `this clause cannot match because a previous clause at line XX always matches`.

For the controller callbacks module in your app, you should write it out like this:

```elixir
defmodule LfWeb.Pow.ControllerCallbacks do
  alias Pow.Extension.Phoenix.ControllerCallbacks

  def before_respond(Pow.Phoenix.RegistrationController, :create, {:ok, user, conn}, config) do
    ControllerCallbacks.before_respond(...put_info_in_conn...)
  end
  def before_respond(Pow.Phoenix.SessionController, :create, {:ok, conn}, config) do
    ControllerCallbacks.before_respond(... put_info_in_conn...)
  end
  def before_respond(Pow.Phoenix.SessionController, :delete, {:ok, conn}, config) do
    ControllerCallbacks.before_respond(... remove_info_from_conn...)
  end

  defdelegate before_respond(controller, action, results, config), to:  ControllerCallbacks

  defdelegate before_process(controller, action, results, config), to: ControllerCallbacks
end
```

I'll see if the docs can be made clearer, or maybe add a macro to `Pow.Extension.Phoenix.ControllerCallbacks` so it can be used in custom controller callbacks to add fallback methods.

As for the example, it just shows how you pass the config directly to the plug rather than using the app env config. It's the same effect as writing:

```elixir
use Pow.Plug.Session, otp_app: :my_app

config :my_app, :pow,
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  extensions: [PowExtensionA, PowExtensionB]
```

**Comment by albertosramires** [comment]
@danschultzer Thank you so much. <3
Everything working correctly now.
