### ISSUE TITLE
Encrypted cookie storage for sessions

### ISSUE THREAD

**Issue by liamwhite** [danschultzer/pow#250]
Rails has, and uses by default, an [encrypted cookie store](https://edgeapi.rubyonrails.org/classes/ActionDispatch/Session/CookieStore.html) session.

Because I have encrypted my Phoenix sessions, I tried to implement this with Pow. I found that I was not able to, because Pow does not appear to have any way to give the store the Conn, or get it back from the store:
https://github.com/danschultzer/pow/blob/223fd21495bf955e8de8c82cc6fd96096e65f7ec/lib/pow/plug/session.ex#L56-L66

In order to do this now, I'd have to write `MyApp.Plug.Sesssion`, which would largely be a copy of `Pow.Plug.Session`.

**Comment by danschultzer** [comment]
The plug sessions in Phoenix is by default encrypted: https://hexdocs.pm/plug/Plug.Session.COOKIE.html

It’s handled in the `plug Plug.Session`, before `Pow.Plug.Session`. Also, the only thing saved by `Pow.Plug.Session` into the session is just the randomly generated session id. The id doesn’t have any identifying information.

**Comment by liamwhite** [comment]
> Also, the only thing saved by Pow.Plug.Session into the session is just the randomly generated session id.

Yeah, that's the part I'd like to change. I'd like to store the user ID and a fragment of the password hash directly into the encrypted cookie, identically to how Devise operates, and not simply store an opaque session ID.

**Comment by danschultzer** [comment]
The user struct (containing id and password hash) is stored in the credentials cache, and the session id stored in the encrypted cookie is what's used to fetch the user struct from the credentials cache (ETS or Mnesia for instant access). This is the most secure way.

If you wish to store identifying information in the encrypted cookie, then you should set up a custom auth plug. Here's how to do that with `Phoenix.Token`: https://github.com/danschultzer/pow#authorization-plug

This will forego the Pow session store entirely, since it won't be needed in this case. Just be aware that it isn't a good idea to store identifying information in the cookie, even if encrypted.

**Comment by liamwhite** [comment]
Thank you, sorry to be a bother.

**Comment by danschultzer** [comment]
Oh, it's no problem! Will you go with a custom auth plug, or just let Pow handle it by default? If you go with custom auth plug, is there a reason for that? I'm curious of your use case since I think the docs can be improved to make the above clearer.

**Comment by liamwhite** [comment]
Something I learned a while back when dealing with persistent Rails sessions is that session storage is a very messy business when you have more than around 1,000,000 daily active sessions. (I expect to have at least this many within a few months, because this is a replacement for an existing Rails application.)

In that sense, even though storing the user information in the session cookie isn't necessarily the _most secure_ move, it is good enough, and doesn't require any sort of external storage.

Why I prefer cookie storage in this scenario:
- I don't have to deal with any financial data.
- If someone steals my secret key, this doesn't immediately compromise my authentication, because an attacker still needs to know the password hash fragment for whomever they want to authenticate as.

I am going to go with a custom auth plug for this application. Even if less flexible, it is simpler to use and deal with.

**Comment by danschultzer** [comment]
Oh, I see. That's a valid use case, and you should be able to set up what you need with a custom auth plug.

I would suspect that Elixir and ETS/Mnesia would perform much better than Rails with large amounts of transient data (e.g. the `Pow.Plug.Session` prevents session fixation, so sessions are updated very frequently), but I don't have any production experience with 1M+ sessions. Your approach with stateless session will definitely ensure there is no bottleneck.

**Comment by liamwhite** [comment]
Here's what this looks like, before any persistence or TOTP is added
```elixir
defmodule Philomena.Plugs.Session do
  use Pow.Plug.Base

  alias Plug.Conn
  alias Philomena.{Repo, Users.User}

  @session_key :philomena_session

  def fetch(conn, _config) do
    conn = Conn.fetch_session(conn)
    user = Conn.get_session(conn, @session_key)

    conn
    |> maybe_load_user(user)
  end

  def create(conn, user, _config) do
    user = session_value(user)

    conn =
      conn
      |> Conn.fetch_session()
      |> Conn.put_session(@session_key, user)
    
    {conn, user}
  end

  def delete(conn, _config) do
    conn
    |> Conn.fetch_session()
    |> Conn.delete_session(@session_key)
  end

  defp maybe_load_user(conn, {:ok, user}) do
    with {:ok, [user_id, hash]} <- Jason.decode(user),
         %User{} = user <- Repo.get(User, user_id),
         ^hash <- binary_part(user.encrypted_password, 0, 25)
    do
      {conn, user}
    else
      _ ->
        {conn, nil}
    end
  end
  defp maybe_load_user(conn, _) do
    {conn, nil}
  end

  defp session_value(user) do
    Jason.encode([user.id, binary_part(user.encrypted_password, 0, 25)])
  end
end
```

**Comment by danschultzer** [comment]
Looks good, that should be working well! It's vulnerable to session fixation, but there's no way around that with stateless tokens.

**Comment by danschultzer** [comment]
One thing to note is that you do a DB request each time to load the user. In that case you could move the session store to the DB since the you already use the DB on each request (that has a session token). But then you may end up just going back to ETS/Mnesia anyway since it's ephemeral data that's better handled there 😄

Instead of just using the user id, I would probably just have serialized the user struct (using a whitelist of what data to include), and then only fetch from the DB when I need the full struct.

**Comment by DavidOliver** [comment]
> The plug sessions in Phoenix is by default encrypted: https://hexdocs.pm/plug/Plug.Session.COOKIE.html

@danschultzer, I don't know if Phoenix has changed since your comment, but, if my understanding is correct, the default session cookie is by default signed but not encrypted. From my new umbrella project's `endpoint.ex`:

```elixir
  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "...",
    signing_salt: "..."
```

No `encryption_salt` is defined by default here.

**Comment by danschultzer** [comment]
@DavidOliver oh I think you are right! It’s been a while so can’t remember how it used to be, but I’ve updated the comment for anyone following thanks 🙂
