### ISSUE TITLE
Remove /registration/edit route

### ISSUE THREAD

**Issue by DragosMocrii** [danschultzer/pow#254]
Hi, first of all, thank you for this package!

I am looking to disable the /registration/edit route, since I want to build my own page for account settings. I'm currently adding the Pow routes using the `pow_routes()` macro, but I haven't found a way to remove a route in Phoenix. Is there a way to do this so I don't have to define all routes manually, as in the case with the API scope?

Thank you

**Comment by danschultzer** [comment]
You can use [the disable registration guide](https://github.com/danschultzer/pow/blob/ed9dbfc6d549344d75c98dd30deacc634d110abd/guides/disable_registration.md#routes) and only enable some routes:

```elixir
  scope "/" do
    pipe_through :browser

    pow_session_routes()
  end

  scope "/", Pow.Phoenix, as: "pow" do
    pipe_through [:browser, :protected]
    resources "/registration", RegistrationController, singleton: true, only: [:new, :create, :delete]
  end
```

The other way is to simply override it::

```elixir
  scope "/", MyAppWeb do
    pipe_through [:browser]

    resources "/registration", RegistrationController, singleton: true, only: [:edit, :update]
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end
```

That `resources` definition will catch any requests for `/registration/edit` and `/registration/update`, before it gets to the definitions in `pow_routes/0`.

**Comment by DragosMocrii** [comment]
Thank you so much!
