### ISSUE TITLE
Override default configuration values; password_min_length

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#26]
There's a default setting of `password_min_length: 10`. And I'd like to redefine it to `8` because it's widely accepted. I don't want to bother or enforce the inconveniences to my users.

How can I redefine some default configurations like `password_min_length`? Adding `password_min_length: 8` in the `config.exs` didn't work.

**Comment by jung-hunsoo** [comment]
It seems that 'Pow` is already able to override password length. There's a test case of `test "can use custom length requirements for password"`.

I just found that the right place to override default values is `MyApp.Users.User`. It is documented in `Pow.Ecto.Schema`. Now it works properly, Great.

**Comment by danschultzer** [comment]
👍 Yeah, that configuration option belongs to the user schema module.
