### ISSUE TITLE
Marketing/SEO

### ISSUE THREAD

**Issue by Immortalin** [danschultzer/pow#260]
This isn't the first result when you Google "Elixir Phoenix Auth". It should be. The internet is safer for everyone when less wheels are reinvented. Django has it built-in, Rails has Devise. It's unreasonable and dangerous that Phoenix users have to jump through forum posts and tutorials on implementing Authn/Authz from scratch.

**Comment by danschultzer** [comment]
I do see Pow being mentioned near top in elixirforum and theguild tutorial on the first page on Google with incognito which is great. It's something that will mostly just take time as more people write about Pow and link to it with the relevant keywords.

I've thought of maybe creating a landing page for Pow similar to https://phoenixframework.org. It may make Pow more trustworthy, which is essential to get more people onboard. I'm not saying that Pow is the best solution for everybody, but I do prefer that developers with weak security experience just let Pow do the work for them, and I definitely agree that the advice of rolling your own is dangerous.

**Comment by danschultzer** [comment]
I've created https://powauth.com as a landing page for Pow. Feel free to submit any PR's, repo is at https://github.com/danschultzer/pow_site.
