### ISSUE TITLE
key :organization_id not found

### ISSUE THREAD

**Issue by thantez** [danschultzer/pow#263]
hi
I tried to install invitation extension for my project according to [its README](https://github.com/danschultzer/pow/blob/master/lib/extensions/invitation/README.md) but when I entered email for inviting an user I got this error:
`
key :organization_id not found in: %Project.Account.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirm_password: nil, current_password: nil, email: "aaa@aaa.aaa", email_confirmation_token: "ef6e1f6e-beeb-43e4-b8e3-ae43cf685d83", email_confirmed_at: #DateTime<2019-08-26 14:02:43Z>, id: 5, inserted_at: ~N[2019-08-26 14:02:33], invitation_accepted_at: nil, invitation_token: nil, invited_by: #Ecto.Association.NotLoaded<association :invited_by is not loaded>, invited_by_id: nil, invited_users: #Ecto.Association.NotLoaded<association :invited_users is not loaded>, password: nil, password_hash: "$pbkdf2-sha512$100000$X3UILb2A8IL6sCDzgmzyNA==$zVjYxeaQpkYjNxeFXl4De5wyVtFX2qyxQ4P0ad7UblEI4A6r69jCEiWlcEMKstwzZW8vV9hzWcb63HcVLex54g==", unconfirmed_email: nil, updated_at: ~N[2019-08-26 14:02:43]}`

and that was predictable. this is my user module:
```
defmodule Project.Account.User do
  use Ecto.Schema
  use Pow.Ecto.Schema
  use Pow.Extension.Ecto.Schema,
    extensions: [PowResetPassword, PowEmailConfirmation, PowPersistentSession, PowInvitation]

  schema "users" do
    pow_user_fields()
    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
  end

  def invite_changeset(user_or_changeset, invited_by, attrs) do
    user_or_changeset
    |> pow_invite_changeset(invited_by, attrs)
    |> changeset_organization(invited_by)
  end

  defp changeset_organization(changeset, invited_by) do
    Ecto.Changeset.change(changeset, organization_id: invited_by.organization_id)
  end
end
```
so what should I do?
thanks.

**Comment by thantez** [comment]
I wonder what organization is, is it about administration and managing users levels?

**Comment by thantez** [comment]
wow.
I thought inviting is just for advertising by users,
for example bob invite jack for ad site to him.
thanks a lot.

**Comment by adelnizamutdinov** [comment]
man it would be so cool to have a guide on adding `organization_id` in Pow. I'm still a beginner, that would help immensely

**Comment by danschultzer** [comment]
I’ve it planned for powauth.com. Here’s a draft: https://github.com/pow-auth/pow_site/issues/11#issuecomment-534659975
