### ISSUE TITLE
Link to resend confirmation e-mail

### ISSUE THREAD

**Issue by danschultzer** [danschultzer/pow#267]
It’s common to have a “resend e-mail” link in the user profile when an e-mail change is pending. An example should be put in the PowEmailConfirmation readme like with the current e-mail change paragraph that shows when there’s a pending change.

**Comment by joshchernoff** [comment]
Was just about a submit a ticket about this, thanks for your impressive efforts on this library 🙏

**Comment by danschultzer** [comment]
Yep, saw that it wasn't updated on gh pages, it's up here now: https://powauth.com/guides/2020-03-07-resend-email-confirmation-link.html
