### ISSUE TITLE
Using pow for desktop native apps?

### ISSUE THREAD

**Issue by fire** [danschultzer/pow#27]
I'm looking into implementing https://tools.ietf.org/html/rfc8252, but I'm not sure how to authenticate using pow.

My best guess is some sort of double authentication. The app authenticates with pow and then pow authenticates with Google Apps (for an example). Any ideas?

Sample: https://github.com/googlesamples/oauth-apps-for-windows/blob/master/OAuthConsoleApp/OAuthConsoleApp/Program.cs

**Comment by danschultzer** [comment]
For google apps authentication, you should use [PowAssent](https://github.com/danschultzer/pow_assent). It has a google strategy that you can use. What will you build the native app with? I assume you won't need phoenix, ecto or plug but only some light logic for OAuth 2.0 auth flow?

**Comment by fire** [comment]
An oauth login client was written in gdscript which is godot game engine's internal scripting language. This also convertible to c++.

What my first prototype did was use keycloak as an openid server and then have the game connect to the keycloak endpoints using the oauth client. Then, the keycloak site triggers a google accounts login. This authenticates keycloak and google. My second future prototype is to have the keycloak and elixir / phoenix working.

This isn't ideal because it's not a pure erlang / elixir solution. The best situation is to also have the openid server be in elixir, but there doesn't appear to be any openid server implementations.

The idea is the game client connects to pow's openidc server endpoints and have the pow server trigger google logins. I have no idea how to do that.

**Comment by danschultzer** [comment]
Ah, I don't know anything about godot, so any information on how the flow works would help me understand your situation. Is OpenID required, or do you just need to authenticate users with their Google account?

If OpenID Connect is required, then I've built an [OAuth 2.0 provider](https://github.com/danschultzer/ex_oauth2_provider) for elixir that could be worked into support OpenID Connect protocol as, AFAIK the only difference is nonce validation and JWT id token. You would also need to set up the flow so it'll redirect to google for auth.

Using Pow may be easier. If you wouldn't need OpenID, then you only have to set up your server with PowAssent, using the Google strategy. This will authenticate and register users.

**Comment by fire** [comment]
* Start redirect server at localhost with a random port
* Generate 32 + 32 state and code verifier bytes
* Call openidc provider authorization endpoint. 
```
string.Format("{0}?response_type=code&scope=openid%20profile&redirect_uri={1}&client_id={2}&state={3}&code_challenge={4}&code_challenge_method={5}",
                authorizationEndpoint,
                System.Uri.EscapeDataString(redirectURI),
                clientID,
                state,
                code_challenge,
                code_challenge_method);
```
* Open browser uri using the os
* The authorization endpoint redirects to Google.
* The authorization calls the redirect. 
* Shutdown listener
* Check code from browser (redirect browser request)
* Exchange code for tokens
* Use bearer token to go to userInfoEndpoint to get Email / Name

Future:
* Use bearer token to login to elixir servers.

**Comment by danschultzer** [comment]
Thanks! I found this one helpful too: https://developers.google.com/identity/protocols/OAuth2InstalledApp

So the OAuth 2.0 provider only requires that a resource owner exists. It could be set after google authentication as it would be in your case. ExOauth2Provider doesn't have any expectations for how the resource owner is authenticated, just that it exists.

If you have more than one application connecting to the same server it's definitely the way to go. You can combine Pow/PowAssent and ExOauth2Provider to make the work easier, but you'll have to set up the controller to handle the auth flow from the app to google and back.

You could also skip the OAuth 2.0 setup on your server entirely if you only ever have one app, and instead do a custom validation check in your app. You could use JWT or Hawk in this case, and send a signed token back that can be verified both in the client and on the server.

**Comment by danschultzer** [comment]
I think this has been resolved now.
