### ISSUE TITLE
 broken?  Pow.Plug.assign_current_user

### ISSUE THREAD

**Issue by sensiblearts** [danschultzer/pow#272]
I added a safe change method to change some fields of the user.

I'm pretty sure that Pow.Plug.assign_current_user was working previously. 

But now it does not seem to change the assign.

I can update the db repeatedly with new username versions, but Pow.Plug.current_user always shows the version that was current at the last session creation. 

Am I missing something or did this break?

```elixir
def edit(conn, _params) do
    user = Pow.Plug.current_user(conn)  # session, not db version
    user = Users.get_user!(user.id)  # I have to do this to get the db (latest) version...
    changeset = Users.change_user(user)
    render(conn, "edit.html", settings: user, changeset: changeset)
  end

  def update(conn, %{"user" => settings_params}) do
    user = Pow.Plug.current_user(conn)
    case Users.update_user(user, settings_params) do
      {:ok, %User{} = user} ->
        IO.puts user.username # confirms it's the new username
        # FIXME: 
        Pow.Plug.assign_current_user(conn, user, Pow.Plug.fetch_config(conn))  # ...because this not working..?
        |> put_flash(:info, "Settings updated successfully.")
        |> redirect(to: Routes.gallery_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", settings: user, changeset: changeset)
    end
  end
```

**Comment by sensiblearts** [comment]
close for now

**Comment by danschultzer** [comment]
Yeah `Pow.Plug.assign_current_user/2` only assigns the user to the current conn, but doesn't update the user in the cache. You can deal with it this way: https://github.com/danschultzer/pow/blob/v1.0.13/guides/sync_user.md#update-user-in-credentials-cache

**Comment by sensiblearts** [comment]
Yes, sorry to trouble you, I found that and fixed it.
