### ISSUE TITLE
Log out link is not working for me

### ISSUE THREAD

**Issue by csisnett** [danschultzer/pow#273]
Hi!
Thank you for making the library,

I'm trying to use the following for log out:

`<span><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></span>`
but is not working, it says route /session GET doesn't exist when I click it

**Comment by danschultzer** [comment]
It should generate something like:

```html
<span><a href="/session" data-csrf="csrf_token" data-method="delete" data-to="/session">Sign out</a></span>
```

It may be the javascript that's not working. The docs `Phoenix.HTML` explains that javascript has to be enabled for it to work: https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2-javascript-dependency

There's a javascript file in `Phoenix.HTML` that has to be added to the JS build. The other way of dealing with it is to have it as a form:

```elixir
<%= form_for @conn, Routes.pow_session_path(@conn, :delete), [method: :delete, as: :user], fn _ -> %>
  <%= submit "Sign out" %>
<% end %>
```

**Comment by csisnett** [comment]
Thank you for the prompt answer, I didn't have javascript imported so that must be why it didnt work
