### ISSUE TITLE
Registration Changeset

### ISSUE THREAD

**Issue by jacobwarren** [danschultzer/pow#276]
According to the docs it looks like there's several changeset options available based on different actions, however I can't figure out how to specify a changeset for the registration.

Here's my resolver which registers the user:

```
def register(_parent, params, %{context: %{conn: conn}}) do
  user_params = Map.put(params, :sign_in_count, 1)
  conn
  |> Pow.Plug.create_user(user_params)
  |> case do
    {:ok, user, conn} ->
      token = %{access_token: conn.private[:api_auth_token], renew_token: conn.private[:api_renew_token]}
      {:ok, %{token: token, user: Map.from_struct(user)}}
    {:error, changeset, _conn} ->
      {
        :error,
        message: "Could not create account",
        details: ChangesetErrors.error_details(changeset)
    }
  end
end
```

This passes through the default `changeset` function. How can I get this to pass through a specific `register_changeset` function instead?

I need to chain several other ecto jobs together to create the related tables and want to do this efficiently, which is why I want registration-specific changesets.

**Comment by danschultzer** [comment]
`changeset/2` will be called for both [create](https://github.com/danschultzer/pow/blob/v1.0.13/lib/pow/ecto/context.ex#L131-L144) and [update](https://github.com/danschultzer/pow/blob/v1.0.13/lib/pow/ecto/context.ex#L146-L157) calls. You could add a custom context to override the behavior, but I would recommend that you just check if the user is new or persisted:

```elixir
def changeset(user_or_changeset, attrs) do
  changeset = pow_changeset(user_or_changeset, attrs)

  case Ecto.get_meta(changeset.data, :state) do
    :built -> create_changeset(changeset, attrs)
    _any  -> update_changeset(changeset, attrs)
  end
end
```

In general ecto just works with the same changeset no matter state. If this isn't sufficient, can you explain a bit more about your setup. Do you chain ecto changesets together, or do you do several repo calls (e.g. as `Ecto.Multi`)?

**Comment by jacobwarren** [comment]
@danschultzer this is perfect! Currently I'm chaining changesets together and I think this is exactly what I'm looking for.

Thank you so much for such a quick reply too. I've looked at many of your Github issues, and this is by far the best library support I've seen in a VERY long time!
