### ISSUE TITLE
Is it possible to redirect from within a callback?

### ISSUE THREAD

**Issue by joelbyler** [danschultzer/pow#279]
I sometimes want to redirect to a different page depending on the type of user registration (a conn param). Is this possible using a callback or is there another way of accomplishing this?

**Comment by danschultzer** [comment]
Yeah, you do it with a custom routes backend: https://github.com/danschultzer/pow#callback-routes

```elixir
defmodule MyAppWeb.Pow.Routes do
  use Pow.Phoenix.Routes
  alias MyAppWeb.Router.Helpers, as: Routes

  def after_registration_path(conn) do
    case conn.params["a"] do
       "1" -> Routes.a_path(conn, :index)
      _any -> Routes.b_path(conn, :index)
  end
end
```

You can see all routes in https://github.com/danschultzer/pow/blob/v1.0.13/lib/pow/phoenix/routes.ex

**Comment by danschultzer** [comment]
I assume the above answered your question 🙂

**Comment by joelbyler** [comment]
Yes that helps a ton!  Much more elegant than what I cam up with
