### ISSUE TITLE
Cannot confirm email by setting :email_confirmed_at.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#28]
In the readme of `PowEmailConfirmation`, manual email confirmation by setting up `:email_confirmed_at` is described.

But in my test seed it didn't work. I think `:email_confirmed_at` field is not casted in the changeset.

Seed codes are like this;
```elixir
user_params = %{name: "na", email: "na@some_url.com", password: "abcd1234", confirm_password: "abcd1234", email_confirmed_at: DateTime.utc_now()}
{:ok, na_user} = Pow.Operations.create(user_params, otp_app: :myapp)
```

Fortunately, `PowEmailConfirmation.Ecto.Context.confirm_email/2` is working as expected.

**Comment by danschultzer** [comment]
I've updated readme, thanks 👍

**Comment by jung-hunsoo** [comment]
Casting fields in changeset should be dealt with care, so I agree your approach is proper.

By the way how about replacing `PowEmailConfirmation.Ecto.Context.confirm_email/2` with `PowEmailConfirmation.confirm_email/2` or `PowEmailConfirmation.Operations.confirm_email/2`? It will wrap lower level functions and allow possible independent with Ecto.

**Comment by danschultzer** [comment]
That's a great idea. The extensions have been built so they are tightly connected between the plug and ecto APIs, mostly because I wasn't 100% sure how the extensions should be working. Having an `Operations` module for the extensions makes a lot of sense. Let me reopen this until I can create a PR to add a similar high level API 👍

**Comment by danschultzer** [comment]
I've been looking at this several times, but I think as Pow currently is it works pretty well. There hasn't been a need to decouple extension plug and extension ecto modules so I don't think it's really needed. I'll revisit this if it becomes relevant, but it seems like extensions are so tightly coupled that any modification would in any case require developers to plan carefully.
