### ISSUE TITLE
Add fn Pow.Operations.current_user(conn)

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#29]
In my webapp, `Bodyguard` library is used for simple authorization.

And `Bodyguard.Plug.Authorization` receives 1-arity fn for user allocation like `&get_current_user/1`. [Docs](https://hexdocs.pm/bodyguard/Bodyguard.Plug.Authorize.html)

Currently there's a helper fn which simply wraps `Pow.Operations.current_user(conn, otp_app: :myapp)`.

I believe almost every users with `Bodyguard` and `Pow` would do the same thing, which means it'll be one of the most frequently used fn.

So, how about adding a fn `current_user(conn)` or `current_user(conn, default_options)`?

**Comment by danschultzer** [comment]
You can use [`Pow.Plug.current_user/1`](https://github.com/danschultzer/pow/blob/master/lib/pow/plug.ex#L11). It'll pick up the configuration found in the connection. `Pow.Plug.current_user/2` is just to make it more explicit.

**Comment by jung-hunsoo** [comment]
Oh I totally got confused. I can't remember why I couldn't find that fn so far. Thanks!
