### ISSUE TITLE
Defining custom messages doesn't get default methods defined

### ISSUE THREAD

**Issue by blatyo** [danschultzer/pow#294]
Say I have a custom module like so:

``` elixir
defmodule MyApp.Pow.Messages do
  use Pow.Phoenix.Messages
  use Pow.Extension.Phoenix.Messages, extensions: [PowAssent]
end
```

Theoretically, it should be possible to configure this module to be used and it would be equivalent to the existing module.

However, when it defines the extension methods, it'll only generate prefixed ones. For example, `pow_assent_could_not_sign_in/1`. However, when `pow_assent` calls the messages module, it's calling `could_not_sign_in/1` as seen [here](https://github.com/danschultzer/pow_assent/blob/c8d161ec47dc24de2301a889ea6934451087baeb/lib/pow_assent/phoenix/controllers/authorization_controller.ex#L133). It seems like pow should also be generating a `could_not_sign_in/1` function that delegates to `pow_assent_could_not_sign_in/1`.

**Comment by danschultzer** [comment]
It's done in this way to prevent naming conflicts, and it should be working as expected by adding a custom `pow_assent_could_not_sign_in/1` method. I got a test [for it here](https://github.com/danschultzer/pow/blob/v1.0.13/test/pow/extension/phoenix/messages_test.exs). 

Behind the scenes, the `Pow.Extension.Phoenix.Messages` macro will generate a `MyApp.Pow.Messages.PowAssent.Phoenix.Messages` module which is what the `exension_messages/1` will look up during the ` extension_messages(conn).could_not_sign_in(conn)` call. 

`MyApp.Pow.Messages.PowAssent.Phoenix.Messages.could_not_sign_in/1` falls back to the `MyApp.Pow.Messages.pow_assent_could_not_sign_in/1`.

**Comment by blatyo** [comment]
Thanks, this turns out to have been an issue where the messages module wasn't configured and a controller was overridden. So, pow was looking for something nested under the overridden module and not finding it.
