### ISSUE TITLE
Adding fields on registration?

### ISSUE THREAD

**Issue by mrcasals** [danschultzer/pow#295]
What's the recommended way to add fields to the registration/sign up process? Say I want users to have a username, or their name, apart from their email.

I guess I can follow these steps:

1. Add new field to the DB
1. Overwite the `changeset` function in the `User` module to cast the new field
1. Overwrite the registration template to add the new field

Is there any other way to achieve it? I couldn't find any info in the guides :(

Thanks!

**Comment by danschultzer** [comment]
Yeah, that's how you do it. [Create a custom changeset](https://github.com/danschultzer/pow#ecto-changeset) and then just add the field to the templates. It's meant to be identical to how you do it with just Phoenix.

**Comment by mrcasals** [comment]
Yeah, I wondered if there was a way to add fields through config to make it more magical, but the current solution will work fine.

Thanks!

**Comment by danschultzer** [comment]
Yeah, I try to prevent as much magic as possible so the code stays explicit and easy to understand 😄
