### ISSUE TITLE
No route found for delete session

### ISSUE THREAD

**Issue by an-drian** [danschultzer/pow#297]
Hey,

I met the problem, when i logged in and try to log out, Phoenix told me that I don't have a route for `GET /session :delete`. But it's a bit weird, because when I check `phx.routes` that route already here .I've tried to completely recompile the app but it did'n help :(

Phoenix ~> 1.4.9
Elixir ~> 1.9.1

My router.ex: 
```
pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", LaerWeb do
    pipe_through [:browser, :protected]

    # Add your protected routes here
  end

  scope "/", LaerWeb do
    pipe_through :browser

    # Add your protected routes here
    get "/", PageController, :index
  end
```

**Comment by danschultzer** [comment]
It's because it has to be `DELETE /session :delete`. Make sure that you have the `:delete` method set and that `phoenix_html.js` is included in your JS:

```elixir
<%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %>
```

https://hexdocs.pm/phoenix_html/Phoenix.HTML.Link.html#link/2-javascript-dependency

**Comment by an-drian** [comment]
Thanks, it helped to me 👍
