### ISSUE TITLE
Add :last_login_at and :last_login_ip to User struct.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#30]
Both `:last_login_at` and `:last_login_ip` attributes are useful when providing basic security protection.

Maybe `:updated_at` can be used in replace for `:last_login_at` though not proper. (for example, when user changed name or password).

**Comment by danschultzer** [comment]
I never really liked that way for handling security. It only makes sense if you permit only one active session at a time. Also recording only the IP isn't all that useful.

In Pow all active sessions can be found in the credentials store, by calling [Pow.Store.CredentialsCache.sessions/3](https://github.com/danschultzer/pow/blob/master/lib/pow/store/credentials_cache.ex#L19-L28). By default it only records the session id, but you could add in user agent, ip, etc. With Phoenix 1.4 it was shown how telemetry can be enabled easily, and I think that's the way Pow should live update a lot of this stuff. I believe that Pow should ping whenever a session event occurs, and an extension or custom module can pick up and decide how to log it.

I've an idea for a security heavy extension for Pow that persistently store all login history, and has a page for users to see current and past login with user agent and location (IP). The user can also remove active sessions.

I've mostly followed recommendations by the [OWASP](https://www.owasp.org/) organization, and I would like to implement their recommendations for [logging session lifecycle](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Logging_Sessions_Life_Cycle:_Monitoring_Creation.2C_Usage.2C_and_Destruction_of_Session_IDs).

**Comment by humancopy** [comment]
@jung-hunsoo For now you can use this as a quick and simple tracking solution: https://github.com/humancopy/pow_last_login
