### ISSUE TITLE
Undefined module for ResetPasswordView when using walkthru in documentation

### ISSUE THREAD

**Issue by joelbyler** [danschultzer/pow#300]
I've tried to use the documentation to setup the password reset feature but getting the error below.

```
UndefinedFunctionError at GET /reset-password/new
function MyAppWeb.PowResetPassword.ResetPasswordView.render/2 is undefined (module MyAppWeb.PowResetPassword.ResetPasswordView is not available)
```

I'm glad to try and update the docs to make this more clear but I'm not sure what I missed.  Should I be defining that view module or should it be included as part of pow?

**Comment by joelbyler** [comment]
Nevermind I found it, sorry for the noise

**Comment by aikomastboom** [comment]
same issue.. have not found it yet.. 
should I make this? or should it be generated? or should it work out of the box?

I think I followed the instructions correctly.. 
I also ran `$ mix pow.extension.phoenix.mailer.gen.templates --extension PowResetPassword --extension PowEmailConfirmation
` but that did not correct this.

**Comment by danschultzer** [comment]
Did you update config with `web_mailer_module: MyAppWeb` where `MyAppWeb` is the module name of your app?

**Comment by aikomastboom** [comment]
I have indeed... my config.ex looks like this now:
```elixir
config :dos, :pow,
       user: Dos.Users.User,
       repo: Dos.Repo,
       web_module: DosWeb,
       extensions: [PowResetPassword, PowEmailConfirmation],
       controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
       mailer_backend: Dos.Mailer,
       web_mailer_module: DosWeb

```

**Comment by danschultzer** [comment]
Did you also run `mix pow.extension.phoenix.gen.templates --extension PowResetPassword --extension PowEmailConfirmation`?

**Comment by aikomastboom** [comment]
yes I have both run:
```
mix pow.extension.ecto.gen.migrations --extension PowResetPassword --extension PowEmailConfirmation
mix pow.extension.phoenix.gen.templates --extension PowResetPassword --extension PowEmailConfirmation
```
and updated `config.ex` as documented.. resulting in above config.ex content

**Comment by danschultzer** [comment]
What is the error message you see? Is it `function DosWeb.PowResetPassword.ResetPasswordView.render/2 is undefined`? If it is does the `DosWeb.PowResetPassword.ResetPasswordView` module exist?

**Comment by aikomastboom** [comment]
Yes the error is 
```
(UndefinedFunctionError) function DosWeb.PowResetPassword.ResetPasswordView.render/2 is undefined (module DosWeb.PowResetPassword.ResetPasswordView is not available)
```
and No, I have not created it.
( the Readme currently doesn't mention I should, as I was just following along to get started, I didn't want to jynx the outcome ;))

**Comment by danschultzer** [comment]
I'm not sure what's going wrong here. Running `mix pow.extension.phoenix.gen.templates --extension PowResetPassword` should have generated the view. There's no errors when running the command?

**Comment by aikomastboom** [comment]
Ok, ran the command.. and... to my surprise files got created.. 
```sh
$ mix pow.extension.phoenix.gen.templates --extension PowResetPassword --extension PowEmailConfirmation 
* creating lib/dos_web/views/pow_reset_password/reset_password_view.ex
* creating lib/dos_web/templates/pow_reset_password/reset_password/new.html.eex
* creating lib/dos_web/templates/pow_reset_password/reset_password/edit.html.eex
Notice: No view or template files will be generated for PowEmailConfirmation as this extension doesn't have any views defined.

```

I guess I somehow skipped ahead when trying to deal with the Mailer and get that part working. and forgot to backtrack and double check I had run all the different generators.

a clear case of pebcac (where I found myself switching between the different readme files and lost track of what I was doing and where I was)

case closed
thank you for your patience
