### ISSUE TITLE
Email should be required for PowResetPassword extension

### ISSUE THREAD

**Issue by kurisusan** [danschultzer/pow#305]
Hi @danschultzer,
When trying to reset password, the first step form that asks for the user's email shouldn't accept empty email input submit. I tried to require the email field in my app User schema changeset but the extension just ignores it.
Currently when submiting empty email there is no error message, just a redirection with a flash message confirming that an email was sent with password reset instructions.
Also a fake email submit will have the same behaviour, though I can understand in this case that it is maybe for security concern.
But at least shouldn't we prevent user from submiting empty email input.

Is there a way to fix that I'm unaware of?

**Comment by danschultzer** [comment]
> Also a fake email submit will have the same behaviour, though I can understand in this case that it is maybe for security concern.

Yeah, it shouldn't leak information whether an account exists or not based on the e-mail. So regardless if the reset password succeeds or not the [same success message returns](https://github.com/danschultzer/pow/blob/v1.0.13/lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex#L30-L43). This means that also empty input will return success response.

If you got custom templates, then you can just add a [HTML5 require attribute](https://www.w3schools.com/tags/att_input_required.asp) to the email field, or maybe even add [email type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) for email validation.

I don't see any easy way of handling this in Pow. The controller just passes on the params and the context logic only returns an nil if the user can't be found. The `PowResetPassword.Plug` module would probably be [the place to handle this](https://github.com/danschultzer/pow/blob/35a3150445c294cfa24997868df39128c943de03/lib/extensions/reset_password/plug.ex#L35-L70), but I think it might make the logic more complex than it needs to be.

**Comment by kurisusan** [comment]
Thanks I think the custom templates with HTML5 require attribute to the email field should be fine. The email validation already works. thanks
