### ISSUE TITLE
Embedded association with user ?

### ISSUE THREAD

**Issue by ZePedroResende** [danschultzer/pow#308]
Hi, i need to create a profile that is a has_one association with the user.

This needs to be create in the register form (embedded) alongside the user. 

Is there a standard way to do this in pow or do i need to override the controllers ?

**Comment by danschultzer** [comment]
Yeah, no need to override controllers. You just have to [customize the changeset](https://github.com/danschultzer/pow#ecto-changeset) and [add custom templates](https://github.com/danschultzer/pow#modify-mailer-templates) with the custom fields e.g. using `Phoenix.HTML.Form.inputs_for/4`.

If it should only update during registration then this might help you: https://github.com/danschultzer/pow/issues/276#issuecomment-532899903

**Comment by ZePedroResende** [comment]
@danschultzer thank you so much for the quick answer ! 
I already have changed the changeset and the template but i need to preload the profile assoc, so for what i understand for the other issue i probably need to do a custom context.

**Comment by danschultzer** [comment]
If it’s an embedded schema then you won’t have to preload it?

**Comment by danschultzer** [comment]
Oh reading your question again, I realize you probably didn’t mean embedded schema. So yes, you you can use a custom context, but this should only be necessary for update or existing users.

**Comment by ZePedroResende** [comment]
@danschultzer im actually using the invitation extension with the register disable.
What would you recommend the custom context would look like with i only wanted to do the preload :smile:  ?

**Comment by danschultzer** [comment]
I assume that the above worked. I'll close the issue.
