### ISSUE TITLE
I18n for email.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#31]
There are some email templates types of `html` and `text`. At first I followed document guide, but it didn't work.

Mine is currently providing both `English` and `Korean` and going to add some Asian languages soon.

If you're busy then I can make PR. (I don't fully understand pow yet.)

**Comment by danschultzer** [comment]
If you generate the mailer templates, then you can modify them to use your Gettext module: https://github.com/danschultzer/pow#modify-mailer-templates

**Comment by jung-hunsoo** [comment]
I generated the mailer templates, and rewriting them to wrap with `Gettext.dgettext("pow", "blah_blah")` for every hard-coded messages.

How about provide default i18n feature in mailer, too?

**Comment by danschultzer** [comment]
It was my plan initially, but I found it difficult to streamline. Phoenix by default doesn't set up Gettext in generated templates, so I followed the same practice to get around that issue. I think that maybe there should be a separate i18n library for Pow with generated (and potentially translated) templates.

**Comment by jung-hunsoo** [comment]
I have a working i18n templates. It depends on `MyappWeb.Gettext` instead of `MyappWeb.Pow.Messages`. Flow is quite simple.

First check `myapp_web.ex` includes `import MyappWeb.Gettext` in `view/0`.
Next call `dgettext/2` in the templates like `dgettext("pow", "Sign In")`.

I can make draft PR them in the installer.

**Comment by danschultzer** [comment]
So what you're thinking is that the mix task will check if `MyAppWeb.Gettext` exists in `myapp_web.ex` and if so, then use `dgettext`? And update the templates like this: https://github.com/danschultzer/pow/blob/master/lib/pow/phoenix/templates/registration_template.ex

**Comment by danschultzer** [comment]
Ah yeah. I would be grateful for a PR, but I’m not sure this is the best approach. There must be a reason that Phoenix doesn’t automatically use gettext in the generated templates, so I’ll have to check up on why that is first. I prefer to keep the defaults as close to what Phoenix has as possible.

It will still be a great thing to have in Pow, as it eliminates a lot of unnecessary work

**Comment by danschultzer** [comment]
Here's the justification from José: https://github.com/phoenixframework/phoenix/pull/1705

I agree with that.

**Comment by jung-hunsoo** [comment]
That's reasonable, too. I18n can be either important or useless. That's why i18n is optional rather than default.

I don't know what's de-facto approach about i18n. Any developers can easily implement i18n to `Pow`, as I made it in an hour.

If i18n is optional, then `Pow` is better to remove i18n default for its simplicity. But `MyappWeb.Pow.Messages` is necessary when i18n the flash messages. There's no way to i18n flash messages under base controller.

**Comment by jung-hunsoo** [comment]
How can I translate email title?

I got title of `Confirm your email address` when an email confirmation was received. I think it's great if I can serve Korean too. (and maybe Japanese soon)

**Comment by danschultzer** [comment]
They are generated in the view files as `subject` methods. You simply update them with gettext there.

**Comment by jung-hunsoo** [comment]
Great! I simply make the email titles i18n by replacing with `def subject(:email_confirmation, _assigns), do: dgettext("pow", "Confirm your email address")`
