### ISSUE TITLE
Unique email

### ISSUE THREAD

**Issue by bumbus** [danschultzer/pow#310]
Hi there it looks like, I can sign up multiple times with the same email address, is there a way to prevent this?

**Comment by danschultzer** [comment]
You need to add a unique index to the email field. It's usually done automatically if you ran `mix pow.install` to generate the migration file.

**Comment by bumbus** [comment]
Thanks for your reply.
I was integrating pow into an existing project and I added some more fields into the index. This seemed to produce my problem. After separating them the "issue" is gone. So all fine, thanks for your advise.
