### ISSUE TITLE
Extension setup for TOTP-based two factor

### ISSUE THREAD

**Issue by liamwhite** [danschultzer/pow#318]
I would like to design an extension to Pow that does the following.

In the user context:
- Provides an interface for model attributes to store an encrypted TOTP secret, the activation state of two-factor authentication, and a list of backup codes on the user's account.
- I would preferably like to use `cloak_elixir` for encrypted attribute storage, but I have to maintain compatibility with Rails' `attr_encrypted` for my purposes, so it should be a pluggable interface of some sort.
- I also have to maintain compatibility with `devise_two_factor`, which stores the backup codes as bcrypt hashes (ugh)

In the session creation action:
- If the user's username and password match, requires that the user has also entered a valid TOTP code or a backup code, if two-factor authentication is enabled
- Stores the consumed TOTP token into the user model to prevent replay

In the registration edit action:
- Generates and stores a TOTP secret in the user before rendering the page, if the user does not currently have one stored

In the registration update action, if the user does not have two-factor authentication enabled and inputted a TOTP token that matched the secret:
- Enables two-factor authentication on the user
- Generates and stores 12 backup codes on the user

In the registration update action, if the user has two-factor authentication enabled and inputted a TOTP token that matched the secret:
- Disables two-factor authentication on the user
- Deletes the user's 12 backup codes
- Deletes the user's consumed TOTP token

I've been going through the extensions code for Pow for some time now and I have to admit that I am rather thoroughly baffled by how it works. I tried to follow the code in the email confirmation extension, but I mostly just ended up making a complete and total mess.

Advice on where to start building a working extension that does the above from scratch would be appreciated. Thanks!

**Comment by danschultzer** [comment]
Sorry for the late response, I'm traveling atm, but will reply to this as soon as I'm back later this week. I think most of this can be dealt with through a plug.

**Comment by danschultzer** [comment]
Ok, finally able to take a look at this. Sorry for the wait. This relates to #6 that I'll look at when I have the time.

You can deal with this as a custom extension, but it would probably be easier to just build this straight into your app unless you got a good reason to make it an extension.

> In the user context:
> 
> * Provides an interface for model attributes to store an encrypted TOTP secret, the activation state of two-factor authentication, and a list of backup codes on the user's account.
> * I would preferably like to use `cloak_elixir` for encrypted attribute storage, but I have to maintain compatibility with Rails' `attr_encrypted` for my purposes, so it should be a pluggable interface of some sort.
> * I also have to maintain compatibility with `devise_two_factor`, which stores the backup codes as bcrypt hashes (ugh)

I'll assume you have the above layed out and ready to go. It's all in ecto schemas and context.

> In the session creation action:
> 
> * If the user's username and password match, requires that the user has also entered a valid TOTP code or a backup code, if two-factor authentication is enabled
> * Stores the consumed TOTP token into the user model to prevent replay
> 
> In the registration edit action:
> 
> * Generates and stores a TOTP secret in the user before rendering the page, if the user does not currently have one stored
> 
> In the registration update action, if the user does not have two-factor authentication enabled and inputted a TOTP token that matched the secret:
> 
> * Enables two-factor authentication on the user
> * Generates and stores 12 backup codes on the user
> 
> In the registration update action, if the user has two-factor authentication enabled and inputted a TOTP token that matched the secret:
> 
> * Disables two-factor authentication on the user
> * Deletes the user's 12 backup codes
> * Deletes the user's consumed TOTP token

Ok, so here's where the meat of this reply will be. I'll use plugs to handle both the 2FA registration and TOTP requirement. I'll also add a custom controller for specific actions. 

First let's set up some routes:

```elixir
defmodule MyAppWeb.Router do
  use Phoenix.Router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :my_app

  # pipelines ...

  pipeline :require_totp do
    plug Pow.Plug.Require2FAForUserPlug
    plug Pow.Plug.TOTPPlug
  end
  
  scope "/", MyAppWeb do
    pipe_through :browser

    resources "/register-totp", TOTPRegistrationController, only: [:new, :create]
    resources "/totp-phase", TOTPVerificationController, only: [:new, :create]
  end

  scope "/" do
    pipe_through [:browser, :require_totp]

    pow_routes()
    pow_extension_routes()
  end
  
  scope "/" do
    pipe_through [:browser, :require_totp]

    # ...
  end

  # routes ...
end
```

We want to make all routes except the 2FA registration and TOTP verification phase go through the two custom plugs.

Now let's set up the first plug that will require users to have enabled 2FA by redirecting them to the registration page if `:encrypted_otp_secret` hasn't been set:

```elixir
defmodule MyAppWeb.Require2FAForUserPlug do
  @moduledoc """
  This plug ensures that a user has enabled 2FA.

  ## Example

      plug MyAppWeb.Require2FAForUserPlug
  """

  alias MyAppWeb.Router.Helpers, as: Routes

  @doc false
  @spec init(any()) :: any()
  def init(opts), do: opts

  @doc false
  @spec call(Conn.t(), any()) :: Conn.t()
  def call(conn, _opts) do
    conn
    |> Plug.current_user()
    |> case do
      nil  -> conn
      user -> maybe_require_2fa_registration(user, conn)
    end
  end
  
  defp maybe_require_2fa_registration(%{encrypted_otp_secret: nil}, conn) do
    conn
    |> Controller.redirect(to: Routes.totp_registration_path(conn, :new))
    |> Plug.Conn.halt()
  end
  defp maybe_require_2fa_registration(_user, conn), do: conn
end
```

And now let's set up the second plug to requires TOTP verification unless `:encrypted_otp_secret` hasn't been set:

```elixir
defmodule MyAppWeb.TOTPPlug do
  @moduledoc """
  This plug ensures that a user session has a valid TOTP.

  ## Example

      plug MyAppWeb.TOTPPlug
  """

  alias MyAppWeb.Router.Helpers, as: Routes
  alias MyApp.Repo

  @doc false
  @spec init(any()) :: any()
  def init(opts), do: opts

  @doc false
  @spec call(Plug.Conn.t(), any()) :: Plug.Conn.t()
  def call(conn, _opts) do
    conn
    |> Plug.current_user()
    |> case do
      nil  -> conn
      user -> maybe_require_totp_phase(user, conn)
    end
  end
  
  defp maybe_require_totp_phase(%{encrypted_otp_secret: nil}, conn), do: conn
  defp maybe_require_totp_phase(user, conn) do
    conn.private
    |> Map.get(:pow_session_metadata, [])
    |> Keyword.get(:valid_totp_at)
    |> case do
      nil ->
        conn
        |> Controller.redirect(to: Routes.totp_verification_path(conn, :new))
        |> Plug.Conn.halt()

      _valid_at ->
        conn
    end
  end

  @doc false
  @spec update_valid_totp_at_for_sesion(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def update_valid_totp_at_for_sesion(conn, user) do
    metadata =
      conn.private
      |> Map.get(:pow_session_metadata, [])
      |> Keyword.put(:valid_totp_at, DateTime.utc_now())

    config = Pow.Plug.fetch_config(conn)
    plug   = Pow.Plug.get_plug(config)
    conn   = Plug.Conn.put_private(conn, :pow_session_metadata, metadata)

    plug.do_create(conn, user, config)
  end
end
```

We've added a `update_valid_totp_at_for_sesion/2` method to the above plug so we can update that value upon succesful TOTP answer.

That's it! Now we just need to fill out the blanks with the controller actions, but the above and the ecto context module(s) have majority of the TOTP logic.

```elixir
defmodule MyAppWeb.TOTPRegistrationController do
  use MyAppWeb, :controller

  def new(conn, _params) do
    changeset = Pow.Plug.change_user(conn)

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, params) do
    conn
    |> Pow.Plug.current_user()
    |> MyApp.Users.User.totp_changeset(params)
    |> MyApp.Repo.update()
    |> case do
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
      
      {:ok, user} ->
        conn
        |> MyAppWeb.TOTPPlug.update_valid_totp_at_for_sesion(user)
        |> redirect(to: Routes.page_path(conn, :index))
    end
  end
end
```

```elixir
defmodule MyAppWeb.TOTPVerificationController do
  use MyAppWeb, :controller

  def new(conn, _params) do
    changeset = Pow.Plug.change_user(conn)

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, params) do
    conn
    |> Pow.Plug.current_user()
    |> MyApp.Users.User.valid_totp?(params)
    |> case do
      false ->
        conn
        |> Pow.Plug.clear_authenticated_user()
        |> put_flash(:error, "Sorry, invalid TOTP. Please sign in again.")
        |> redirect(to: Routes.pow_session_path(conn, :new))

      true ->
        user = Pow.Plug.current_user(conn)

        conn
        |> MyAppWeb.TOTPPlug.update_valid_totp_at_for_sesion(user)
        |> redirect(to: Routes.page_path(conn, :index))
    end
  end
end
```

So this is just the outline of how I imagine it could work. You'll have to work in all the TOTP logic from here. I hope I'll get time to work on #6 soon, there may be things in Pow that can be changed to make make it super easy plugging this stuff in. The above has a pretty simple simple catch-all approach there may not be desired for all situations.

Let me know if this helps!

**Comment by liamwhite** [comment]
@danschultzer Thanks, I'll be giving this a go.

**Comment by liamwhite** [comment]
I think I've almost got it. There only seems to be a small (heh) snag, which is that the "valid" status of the TOTP authentication isn't being stored in the session.

I have verified that the code correctly marks the TOTP token as consumed and updates that in the database. However, once it gets here...
https://github.com/derpibooru/philomena/blob/7784c09b3ec63ae6556d6f9825ed7d0c4302ef52/lib/philomena_web/controllers/session/totp_controller.ex#L25-L28
...and then calls here...
https://github.com/derpibooru/philomena/blob/7784c09b3ec63ae6556d6f9825ed7d0c4302ef52/lib/philomena_web/plugs/totp_plug.ex#L44-L57
... it simply redirects back to asking for a new TOTP token, meaning that state must not have been stored in the session. Routes [here](https://github.com/derpibooru/philomena/blob/canary/lib/philomena_web/router.ex).

**Comment by danschultzer** [comment]
Update Pow in your deps to `v1.0.14`. It adds [metadata to sessions](https://github.com/danschultzer/pow/releases/tag/v1.0.14).

**Comment by liamwhite** [comment]
Okay, it looks like that mostly works. I am still having an issue with the session TotpController. In particular, this code
```elixir
  def create(conn, params) do
    conn
    |> Pow.Plug.current_user()
    |> User.consume_totp_token_changeset(params)
    |> Repo.update()
    |> case do
      {:error, _changeset} ->
        {:ok, conn} =
          conn
          |> Pow.Plug.clear_authenticated_user()

        conn
        |> put_flash(:error, "Sorry, invalid TOTP token entered. Please sign in again.")
        |> redirect(to: Routes.pow_session_path(conn, :new))

      {:ok, user} ->
        conn
        |> PhilomenaWeb.Plugs.TotpPlug.update_valid_totp_at_for_session(user)
        |> redirect(to: "/")
    end
  end
```
works fine when the token is valid, but takes multiple seconds when the token is invalid, and then fails to clear the session.

**Comment by danschultzer** [comment]
You need to pass on the conn after calling `Pow.Plug.clear_authenticated_user/1`:

```elixir
  def create(conn, params) do
    conn
    |> Pow.Plug.current_user()
    |> User.consume_totp_token_changeset(params)
    |> Repo.update()
    |> case do
      {:error, _changeset} ->
        {:ok, conn} =
          conn
          |> Pow.Plug.clear_authenticated_user()
          |> put_flash(:error, "Sorry, invalid TOTP token entered. Please sign in again.")
          |> redirect(to: Routes.pow_session_path(conn, :new))

      {:ok, user} ->
        conn
        |> PhilomenaWeb.Plugs.TotpPlug.update_valid_totp_at_for_session(user)
        |> redirect(to: "/")
    end
  end
```

**Comment by liamwhite** [comment]
[`Pow.Plug.clear_authenticated_user/1`](https://github.com/danschultzer/pow/blob/master/lib/pow/plug.ex#L110) does not return a Conn; it returns a 2-tuple `{:ok, conn}`, hence my construction above. I am correctly passing on the conn as far as I can see.

**Comment by danschultzer** [comment]
Oh, sorry you're right.

How does `consume_totp_token_changeset/2` work? Do you use a TOTP library that could cause the wait due to e.g. time drift?

As for the session not being cleared, what happens when you get redirected to `Routes.pow_session_path(conn, :new)`? Do you get redirected again?

**Comment by liamwhite** [comment]
The delay when the token is invalid seems to be caused by the [large number of trials in pot](https://github.com/yuce/pot/blob/master/src/pot.erl#L176-L198), the library I chose to use to check them; my bad. [`consume_totp_token_changeset/2`](https://github.com/derpibooru/philomena/blob/canary/lib/philomena/users/user.ex#L132-L150)

I'm not sure what changed, but it does seem to be clearing the session redirecting correctly now. Thanks very much for your help!

**Comment by liamwhite** [comment]
Addendum: this solution works great in isolation and hasn't had any problems. However it interacts less than gracefully with the `PowPersistentSession` extension: the user is prompted for a new token every time the browser is restarted. How can this be avoided?

**Comment by danschultzer** [comment]
Good call. It's no possible currently since `PowPersistentSession` can only pull the fingerprint from the current session. I've opened #330 so custom metadata can be added to the persistent session and applied to subsequent sessions. I'll see if I can look at it tomorrow and come up with a solution.

**Comment by danschultzer** [comment]
I've opened PR in #332, so the way you would fix this (if you use the PR `{:pow, github: "danschultzer/pow", ref: "persistent-session-metadata", override: true}`) is to just update the persistent session with the appropriate metadata:

```elixir
conn =
  conn
  |> Plug.Conn.put_private(:pow_persistent_session_metadata, session_metadata: Keyword.take(metadata, [:valid_totp_at]))
  |> PowPersistentSession.Plug.Cookie.create(user, config)
```

I've updated the example above https://github.com/danschultzer/pow/issues/318#issuecomment-552608811.

**Comment by danschultzer** [comment]
@liamwhite did that PR work as expected for you?

**Comment by liamwhite** [comment]
@danschultzer It seems to, though I admit that I haven't done any rigorous testing other than closing my browser a few times

**Comment by danschultzer** [comment]
That would be sufficient :rocket: I'll review the PR tomorrow with fresh eyes and get it merged it in.

**Comment by danschultzer** [comment]
Fix has been merged to master.

**Comment by danhunsaker** [comment]
Too bad this _isn't_ an extension. Would love to just drop it in on my own app(s). :slightly_smiling_face:
