### ISSUE TITLE
Keep getting no `:user` configuration option found

### ISSUE THREAD

**Issue by satyavh** [danschultzer/pow#319]
Started from scratch, can't get this package going. 
Followed the setup and _copy-pasted_ the api guide 1:1, added this to my config.ex:

```
config :dailystate, :pow,
  user: Dailystate.Users.User,
  repo: Dailystate.Repo  

```

Results in error
```
[error] #PID<0.535.0> running DailystateWeb.Endpoint (connection #PID<0.534.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST //api/v1/registration
** (exit) an exception was raised:
    ** (Pow.Config.ConfigError) No `:user` configuration option found.
        (pow) lib/pow/config.ex:56: Pow.Config.raise_error/1
        (pow) lib/pow/ecto/context.ex:138: Pow.Ecto.Context.create/2
        (pow) lib/pow/plug.ex:136: Pow.Plug.create_user/2
```

When posting to `http://localhost:4000/api/v1/registration`

**Comment by satyavh** [comment]
Sorry found it, copy-paste is nasty.

**Comment by voger** [comment]
@satyavh what was the problem? I think I am in the same spot as you but can't find what's wrong.

**Comment by danschultzer** [comment]
@voger Make sure that `:my_app` in `plug Pow.Plug.Session, otp_app: :my_app ` correspond with the one in config `config :my_app, :pow,`.

**Comment by voger** [comment]
@danschultzer The mistake was in front of me. I had configured the user schema as 
```elixir
# Config the pow library
config :tweetclone, :pow,
  user: Tweetclone.User,
  repo: Tweetclone.Repo
```

but it should be 
```elixir
user: Tweetclone.Account.User,
```
