### ISSUE TITLE
User Role security risk in guides

### ISSUE THREAD

**Issue by intpl** [danschultzer/pow#321]
Hi, great work on Pow - I love it! I am new to Elixir/Phoenix, but I don't quite get the approach here:

https://hexdocs.pm/pow/user_roles.html#content

After following steps in this guide, I ended up with a huge security gap in my application, where malicious user can just add field "role" in edit/create registration form and grant themselves admin privileges. I tested it out and am able to easily grant myself admin role just by editing the DOM in Chrome console. 
Am I missing something? What's the correct approach to validate/restrict user input in this case? I understand that copying the controller `Pow.Phoenix.RegistrationController` and doing validation there. I believe it should be mentioned in the guide.

Thank you and keep up the good work!

**Comment by intpl** [comment]
for my app, i came out with this plug i use in newly created `RegistrationController`:

```
defmodule MyAppWeb.ValidateUserParamsPlug do
  use MyAppWeb, :controller

  import Plug.Conn, only: [halt: 1]
  import Pow.Plug, only: [current_user: 1]

  # https://github.com/danhper/plug-navigation-history
  import MyAppWeb.Controllers.Helpers, only: [redirect_back: 2]

  @admin_restricted_fields ["role"]

  def init(_opts), do: nil

  def call(conn, _opts) do
    case current_user(conn) |> params_are_valid?(conn.params) do
      true -> conn
      false ->
        conn
          |> put_flash(:error, "Invalid data")
          |> redirect_back(default: "/")
          |> halt()
    end
  end

  defp params_are_valid?(%MyApp.Users.User{role: "admin"}, _), do: true
  defp params_are_valid?(_, %{"user" => user_params}) do
    myers_diff = List.myers_difference(@admin_restricted_fields, Map.keys(user_params))

    case Keyword.get(myers_diff, :eq) do
      nil -> true
      _ -> false
    end
  end

  defp params_are_valid?(_, _), do: true
end
```

**Comment by danschultzer** [comment]
You are absolutely right. I'll update the guide when I got time to review this.

The best way of handling this is to not permit casting the role, but have a context method to handle it. Something like this should work:

```elixir
defmodule MyApp.Users.User do
  # ...

  schema "users" do
    field :role, :string, default: "user"

    pow_user_fields()

    timestamp()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> maybe_put_user_role()
    |> validate_role()
  end

  defp maybe_put_user_role(changeset) do
    case Ecto.Changeset.get_change(changeset, :role) do
      nil  -> Ecto.Changeset.put_change(changeset, :role, "user")
      _any -> changeset
    end
  end

  def changeset_role(user_or_changeset, attrs) do
    user_or_changeset
    |> Ecto.Changeset.cast(attrs, [:role])
    |> validate_role()
  end

  defp validate_role(changeset) do
    Ecto.Changeset.validate_inclusion(changeset, :role, ~w(user admin))
  end

  # ...
end
```

```elixir
defmodule MyApp.Users do
  alias MyApp.Users.User

  def set_admin_role(user) do
    user
    |> User.changeset_role(%{role: "admin"})
    |> Repo.update()
  end
end
```

`MyApp.Users.set_admin_role/1` is then called in an appropriate controller action (e.g. admin interface where standard users can be upgraded to admins).

**Comment by intpl** [comment]
Thank you very much! Btw you have expired certificate on https://dreamconception.com/ ;)

**Comment by danschultzer** [comment]
Oops, thanks, renewed 😄

**Comment by danschultzer** [comment]
Added #322 to resolve this. Thanks!
