### ISSUE TITLE
Pow registration controller, sending options to new.html.eex and edit.html.eex. Further passing options to app.html.eex layout.

### ISSUE THREAD

**Issue by Abat** [danschultzer/pow#331]
If I use Pow's registration controller, how can I send some variables to app.html.eex layout?

Do I need to use custom controllers?

**Comment by danschultzer** [comment]
What variables do you want to use? All assigns should be available in `app.html.eex`.

**Comment by Abat** [comment]
How do I assign, say @profile to edit.html.eex, to later use it in app.html.eex?

**Comment by danschultzer** [comment]
What data will `@profile` have? You could do it with a plug in `router.ex`, assigning the value there.

**Comment by Abat** [comment]
It's a struct

**Comment by danschultzer** [comment]
But where do you pull it from? Is it part of `@current_user`?

**Comment by Abat** [comment]
I pull it from Profiles context. I use `@current_user.id` to get Profile and want to pass it to app.html.eex

**Comment by danschultzer** [comment]
You can load it in a plug similar to the one in [the sync user guide](https://hexdocs.pm/pow/1.0.14/sync_user.html#reload-the-user).

```elixir
defmodule MyAppWeb.LoadProfilesPlug do
  @doc false

  @spec init(any()) :: any()
  def init(opts), do: opts

  @doc false
  @spec call(Conn.t(), atom()) :: Conn.t()
  def call(conn, _opts) do
    case Pow.Plug.current_user(conn) do
      nil ->
        conn

      user ->
        profile = MyApp.Repo.get!(MyApp.Profiles.Profile, user_id: user.id)

       Plug.Conn.assign(conn, :profile, profile)
    end
  end
end
```

**Comment by Abat** [comment]
thanks a lot! I will work on this and other issue I opened and get back with results. And close the issues.

**Comment by Abat** [comment]
Works! Thanks a lot!
