### ISSUE TITLE
redis chache store stream_scan/3

### ISSUE THREAD

**Issue by antoniolopesgomes** [danschultzer/pow#337]
While adding redis cache store to my project I was getting the error:

`no function clause matching in ... RedisCache.stream_scan/3`

I traced it back to:

```
  def all(config, match_spec) do
    compiled_match_spec = :ets.match_spec_compile([{{match_spec, :_}, [], [:"$_"]}])

    Stream.resource(
      fn -> do_scan(config, compiled_match_spec, "0") end,
      &stream_scan(config, compiled_match_spec, &1),
      fn _ -> :ok end
    )
    |> Enum.to_list()
    |> IO.inspect(label: "list")
  end
```

The second argument of the `Stream.resource` should be a function that returns a tuple with the form: `{[values_to_emit], acc}`

**values_to_emit**: stream values
**acc**: internal accumulator being used in the internal stream logic, used as an argument in the next iteration.

```
  defp stream_scan(_config, _compiled_match_spec, {[], "0"}), do: {:halt, nil}

  defp stream_scan(config, compiled_match_spec, {[], iterator}),
    do: do_scan(config, compiled_match_spec, iterator)

  defp stream_scan(_config, _compiled_match_spec, {keys, iterator}), do: {keys, {[], iterator}}

  defp do_scan(config, compiled_match_spec, iterator) do
    prefix = to_binary_redis_key([namespace(config)]) <> ":*"

    case Redix.command(@redix_instance_name, ["SCAN", iterator, "MATCH", prefix]) do
      {:ok, [iterator, res]} ->
        {filter_or_load_value(compiled_match_spec, res, config), iterator}
    end
  end
```

Because the `do_scan` function is returning {[keys], iterator}, the second iteration of
`&stream_scan(config, compiled_match_spec, &1)` will have a single value (string) as the argument, and as one can inspect in the `stream_scan` functions posted above, none of the them has a form that accepts a single value as an argument, this being the origin of 
`no function clause matching in ... RedisCache.stream_scan/3`

if I change the second form to
```
 defp stream_scan(config, compiled_match_spec, {[], iterator}),
    do: {[], do_scan(config, compiled_match_spec, iterator)}
```
everything works but I'm not sure if it's twisting the logic. 

Thanks for this great project and for all of the contributors time.

**Comment by danschultzer** [comment]
Thanks! You're right, I've updated it in #338. Let me know if it works for you changing it to that. Basically I forgot to pass the result through the `stream_scan/3` method again. I've modified the test too, so all the callbacks get triggered.

**Comment by antoniolopesgomes** [comment]
It works, thanks for the quick response!
