### ISSUE TITLE
Update a user password 

### ISSUE THREAD

**Issue by sunloverz** [danschultzer/pow#344]
I want to create a custom feature, is there a way to update the only password field?

**Comment by danschultzer** [comment]
You can set up a custom changeset:

```elixir
def update_password_changeset(user_or_changeset, attrs) do
  user_or_changeset
  |> pow_password_changeset(attrs)
  |> pow_current_password_changeset(attrs)
end
```

Per the docs https://hexdocs.pm/pow/1.0.15/Pow.Ecto.Schema.html#content

**Comment by sunloverz** [comment]
Thank you very much for quick response Dan! It helped me a lot, just forgot to reply :)
