### ISSUE TITLE
[Advice] Building `return_to` functionality

### ISSUE THREAD

**Issue by coladarci** [danschultzer/pow#346]
A common need for an auth flow is to ensure that the user can be returned to where they initially wanted to go;

- User tries to load `/profile/1`
- User isn't logged in so is redirected to `/sign_in`
- After a successful login, user is returned to `/profile/1`

I have implemented this by passing in a `return_to` query param, adding it to my form and then adding:

```
  def after_sign_in_path(%{params: %{"user" => %{"return_to" => return_to}}}), do: return_to
  def after_sign_in_path(_conn), do: "/"
```

And this works pretty nicely. BUT, this falls apart the moment you want to use `pow_assent` and have that login flow happen externally w/ FB/Twitter/etc as I don't control the form in the same way you would w/ traditional sign in. 

The options, as I see them are:

1) Build support into pow assent where I can redirect to `/auth/facebook/new?return_to=/profile/1` and have it do what it takes pass that through the oauth callback flow
2) Completely bail on this and store the desired URL in the session and pull it from the session after login (I am leaning toward this one but something about it worries me and I can't figure out what it is)
3) .... ? :) 

Do you have any advice on this? 

Appreciate it!

**Comment by danschultzer** [comment]
You don't need to implement this yourself since Pow does support this out of the box. [The docs](https://hexdocs.pm/pow/Pow.Phoenix.Routes.html#user_not_authenticated_path/1) describes it, and here's the relevant code: https://github.com/danschultzer/pow/blob/v1.0.15/lib/pow/phoenix/routes.ex#L88-L104

If you have custom `after_sign_in_path/1` you can pull it from the assigns:

```elixir
  def after_sign_in_path(%{assigns: %{request_path: request_path}}) when is_binary(request_path),
    do: request_path
  def after_sign_in_path(conn), do: Routes.custom_path(conn, :index)
```

PowAssent has support for it in master with https://github.com/pow-auth/pow_assent/pull/110. I'll release a new version asap.

**Comment by coladarci** [comment]
I am so glad to hear this is implemented natively, but I am not understanding how to make it work. 

- User loads a page in my website "/profile/1". They are not logged in, so in that case are you saying that `user_not_authenticated_path/1` is called and `/profile/1` is stored in request_path?
- I have a top nav link that says `login` that a user can click. That link is simply `Routes.pow_session_path(@conn, :new)`
- The user clicks that link and the entire page redirects to `/login`. At this point isn't `request_path` gone?

**Comment by danschultzer** [comment]
It gets triggered when you use the [`Pow.Plug.RequireAuthenticated` plug](https://hexdocs.pm/pow/1.0.15/Pow.Plug.RequireAuthenticated.html#content) like described in [the readme](https://github.com/danschultzer/pow#phoenix-app). The `user_not_authenticated_path/1` gets called that way.

For your login link you could use `Routes.pow_session_path(@conn, :new, request_path: Phoenix.Controller.current_path(conn))` to return the user to the page they clicked the link.

**Comment by coladarci** [comment]
I see the confusion, and it's largely due to how I framed my fake example. In our re-world use-case we don't REQUIRE auth on the given route, it's optional, but we do want to bring you back there after you login. So basically I was doing everything correctly, I just didn't have to invent my own query param and add to the form. 

I'll play w/ this and your new release of assent (Thanks for that, by the way!!) but this can def be closed... appreciate it.
