### ISSUE TITLE
Typo in Production checklist guide

### ISSUE THREAD

**Issue by joepstender** [danschultzer/pow#347]
`config :mensia, :dir, '/path/to/dir'`
should be
`config :mnesia, :dir, '/path/to/dir'`

**Comment by pdgonzalez872** [comment]
:+1 

Would you like to submit a PR or should I do it?

**Comment by danschultzer** [comment]
Thanks! I've fixed it in #348. Feel free to just go ahead and submit PRs @pdgonzalez872 😄

**Comment by pdgonzalez872** [comment]
@danschultzer I just saw this... 🤦‍♂ Sorry, thanks for adding! 👍
