### ISSUE TITLE
Page hangs on reset password submission

### ISSUE THREAD

**Issue by coladarci** [danschultzer/pow#351]
Steps:

- Submit the form to send a reset email
- Click link in email and complete the form for a new password
- Submit the form

Expected: It gives a success indication of some sort
Actual: The page just hangs, and the logs say a 302 was sent:

This is what appears in the logs:
```
UPDATE "users" SET "password_hash" = $1, "updated_at" = $2 WHERE "id" = $3 RETURNING "id" ["$....", ~N[2019-12-10 20:06:51], 11388]
[debug] QUERY OK source="users" db=3.4ms queue=1.8ms
SELECT u0."id", u0."first_name", u0."last_name", u0."phone", u0."legacy_id", u0."password_hash", u0."email", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."id" = $1) [11388]
[info] Sent 302 in 551ms
```

But in the browser:

![image](https://user-images.githubusercontent.com/1004167/70565025-1dcf3180-1b46-11ea-949c-65267a2dea95.png)

that'll just stay there forever..

If I reload the page while it's "stuck" I get a double flash message:
![image](https://user-images.githubusercontent.com/1004167/70565335-b960a200-1b46-11ea-9973-a3627a0a9c67.png)
which might give some sort of indication of what's happening?

Sorry I can't provide any more information but happy to answer questions / try things out, etc!

**Comment by danschultzer** [comment]
The request is handled in Pow since [the info flash message is set, and there's a 302 redirect returned](https://github.com/danschultzer/pow/blob/v1.0.15/lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex#L75-L77). I suspect that either the browser or the server is blocking the request rather than anything in Pow/Plug/Phoenix, though it could be something that is sent by Plug that gets blocked.

With the reload, do you trigger a POST or GET request? Does this happen with local tests? Could you try this in a different browser (or machine) just to be sure it's not the client? Sometimes plugins can prevent requests. To be sure it's not something Pow related you can set up a controller test, testing the route and check whether it does respond with a redirect.

**Comment by coladarci** [comment]
Thanks - I have some more learnings:

1) If I do this is Safari (versus Chrome) the page doesn't hang, after you login in, the page errors w/ an infinite loop "too many redirects"

Basically, anytime you manually navigate to the sign_in route when you are already authenticated you get that error. I have overridden any routes; this is just the stock `Pow.Phoenix.Routes` 

I wonder if the problems are related...

**Comment by danschultzer** [comment]
Both the [reset password controller](https://github.com/danschultzer/pow/blob/v1.0.15/lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex#L8) and [session controller](https://github.com/danschultzer/pow/blob/v1.0.15/lib/pow/phoenix/controllers/session_controller.ex#L13) are not accessible if the user has been authenticated. The user will then be redirected to `/` (by default).

What pages do you get redirected between? How is Pow configured in `router.ex` (the plugs in the pipelines can also cause redirect)?

**Comment by coladarci** [comment]
OK - so the infinite loop can be ignored; there was some code setting `request_path` and in some cases it would be where the user already is, which would be bad (maybe it's worth thinking about preventing that on your end? either way, it was my code's fault).

That said, I still have the original problem; chrome hangs and safari doesn't...

**Comment by coladarci** [comment]
I just noticed that chrome works if incognito; could be a bad plugin? That said, this is pretty concerning. I'll see if I can isolate it...

**Comment by danschultzer** [comment]
> OK - so the infinite loop can be ignored; there was some code setting `request_path` and in some cases it would be where the user already is, which would be bad (maybe it's worth thinking about preventing that on your end? either way, it was my code's fault).

Oh, this was what you were implementing in #346, right? Pow should prevent such loop, since it only sets the `:redirect_path` for the `user_not_authenticated_path/1` route. So it should only redirect twice in the worst case.

> I just noticed that chrome works if incognito; could be a bad plugin?

Does the same thing happen in Safari? A plugin can block requests, so it just says "(pending)".

**Comment by coladarci** [comment]
> Does the same thing happen in Safari?

No..

This has gotten even more strange! This only happens in Chrome when I use a specific password!! It's 8 characters long w/ no special chars.  That exact password works in Safari and in Chrome Incognito. My first thought was a bug around trying to reset to the existing password; this is not what's happening. 

I went on a disable plugin spree thinking LastPass could be to blame, but so far nothing. 

This is crazy... (almost certainly not a problem w/ the library but I imagine you're interested)

**Comment by coladarci** [comment]
I have narrowed this down to being signed into chrome w/ a specific user. I blew away that entire profile (half by mistake) so I am no longer able to reproduce... def something sketchy going on w/ chrome. I'm going to close this. Thanks for hearing me out....

**Comment by danschultzer** [comment]
That’s frustrating, guess it’s some rare bug in Chrome.

**Comment by coladarci** [comment]
@danschultzer I think I know why it was hanging... I now get this w/ this specific password
![image](https://user-images.githubusercontent.com/1004167/74564120-1e5bbe00-4f23-11ea-9e1d-5f42fe8c5ad8.png)

I suspect Chrome had a bug in this feature before it launched that was causing the browser to hang.

**Comment by danschultzer** [comment]
Thanks for the update!
