### ISSUE TITLE
How to get the config for do_delete, do_create?

### ISSUE THREAD

**Issue by dfalling** [danschultzer/pow#353]
I'm implementing Pow somewhat manually as I have an API supporting a SPA.  Unlike many of the examples though, I'm just using cookies/sessions and need to tie into that system.  I've read the docs and looked through heaps of tickets here, but still can't figure out exactly where `Pow.Config.t` should come from.

I've seen two references in tests:
`opts = Pow.Plug.Session.init(otp_app: :app_name)`
`opts = Session.init(@default_opts)`

Here's my SessionController:

```elixir
  @spec create(Conn.t(), map()) :: Conn.t()
  def create(conn, %{"user" => user_params}) do
    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        config = ????
        conn
        |> Pow.Plug.Session.do_create(user, config)
        |> send_resp(:no_content, "")

      {:error, conn} ->
        error(conn, :unauthorized, 401)
    end
  end

  @spec delete(Conn.t(), map()) :: Conn.t()
  def delete(conn, _params) do
    config = ????
    conn
    |> Pow.Plug.Session.do_delete(config)
    |> send_resp(:no_content, "")
  end
```

Thanks!

**Comment by dfalling** [comment]
I might have found the solution when I picked this back up today:
`config = Pow.Plug.fetch_config(conn)`

I'm still chasing errors, so I'll close this ticket out once I get everything compiling and confirm this is it.

**Comment by danschultzer** [comment]
Yep `Pow.Plug.fetch_config/1` is the one you should use here. There’s a section in the readme that describes how config generally works in Pow: https://github.com/danschultzer/pow#configuration

You can also call the plug dynamically so it will use whichever was used in the endpoint/pipeline, decoupling the logic a bit:

```elixir
    config = Pow.Plug.fetch_config(conn)
    plug   = Pow.Plug.get_plug(config)

    plug.do_create(conn, user, config)
```

Though not what you need, I would recommend reading the API guide just to see a different way of implementing Pow in an APi: https://hexdocs.pm/pow/1.0.15/api.html#content

**Comment by dfalling** [comment]
Thanks, that got me past that hurdle.  I also dug into the `Pow.Plug.authenticate_user` source and saw it's already doing `do_create` for me, so that whole code block I had was redundant.

**Comment by danschultzer** [comment]
Just adding updated example for reference to others who wish to implement Pow with an SPA:

```elixir
defmodule MyAppWeb.SessionController do
  use MyAppWeb, :controller

  alias Plug.Conn

  @spec create(Conn.t(), map()) :: Conn.t()
  def create(conn, %{"user" => user_params}) do
    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        json(conn, %{data: %{}})

      {:error, conn} ->
        conn
        |> put_status(401)
        |> json(%{error: %{status: 401, message: "Invalid email or password"}})
    end
  end

  @spec delete(Conn.t(), map()) :: Conn.t()
  def delete(conn, _params) do
    conn
    |> Pow.Plug.delete()
    |> json(%{data: %{}})
  end
end
```

**Comment by dfalling** [comment]
Mine's similar, but I do a bit more to also store the session in a cookie and handle the error if the user's already logged in (not sure if that's still needed?
```elixir
  def create(conn, %{"session" => user_params}) do
    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        config = Pow.Plug.fetch_config(conn)
        user = Pow.Plug.current_user(conn)

        conn
        |> PowPersistentSession.Plug.Cookie.create(user, config)
        |> send_resp(:no_content, "")

      {:error, %{assigns: %{current_user: %IdoApi.Accounts.User{}}} = conn} ->
        conn
        |> put_status(:unauthorized)
        |> put_view(IdoApiWeb.AuthView)
        |> render("logged_in.json", [])
        |> halt()

      {:error, conn} ->
        conn
        |> put_status(:unauthorized)
        |> put_view(IdoApiWeb.AuthView)
        |> render("401.json", [])
        |> halt()
    end
  end
```

I like the idea of handling the `:not_authenticated` in the fallback controller.

**Comment by danschultzer** [comment]
> not sure if that's still needed?

Ideally you can't access that action if you already are signed in. I would use the `Pow.Plug.RequireNotAuthenticated` plug here.

I sometimes have helpers for this:

```elixir
  def require_not_authenticated(conn, _opts) do
    opts = Pow.Plug.RequireNotAuthenticated.init(error_handler: MyAppWeb.Pow.AuthErrorHandler)
    Pow.Plug.RequireNotAuthenticated.call(conn, opts)
  end
```

Then I can just import it in the MyAppWeb controller macro, and call it like this:

```elixir
defmodule MyAppWeb.SessionController do
  use MyAppWeb, :controller

  plug :require_not_authenticated when action in [:create]

  # ...
end
```

**Comment by dfalling** [comment]
Ah nice, good point.  That's a lot cleaner.

**Comment by lud** [comment]
@danschultzer from your previous example :

> function Pow.Plug.delete/1 is undefined or private

Did you mean `clear_authenticated_user(conn)`  ?

**Comment by danschultzer** [comment]
You are probably using an older version of Pow. That method has been deprecated in favor of `delete/1` since `v1.0.17`: https://github.com/danschultzer/pow/blob/v1.0.19/CHANGELOG.md#v1017-2020-02-04

**Comment by lud** [comment]
Indeed !
