### ISSUE TITLE
Custom controller for reset password using pow 

### ISSUE THREAD

**Issue by sunloverz** [danschultzer/pow#354]
I am using the reset password extension.
As far as I know I can reset a token using this code `PowResetPassword.Plug.create_reset_token(user_params)`
But how can I send an email after token reset?

**Comment by danschultzer** [comment]
You can find an example here: https://github.com/danschultzer/pow/issues/61#issuecomment-451779111

In short, call [`PowResetPassword.Phoenix.Mailer.reset_password/3`](https://github.com/danschultzer/pow/blob/v1.0.15/lib/extensions/reset_password/phoenix/mailers/mailer.ex#L8) and[ `Pow.Phoenix.Mailer.deliver/2`](https://github.com/danschultzer/pow/blob/v1.0.15/lib/pow/phoenix/mailer.ex#L45):

```elixir
  defp deliver_email(conn, user, token) do
    url = reset_password_url(conn, token)
    email = PowResetPassword.Phoenix.Mailer.reset_password(conn, user, url)

    Pow.Phoenix.Mailer.deliver(conn, email)
  end

  defp reset_password_url(conn, token) do
    Routes.pow_reset_password_reset_password_url(
      conn,
      :edit,
      token
    )
  end
```

**Comment by sunloverz** [comment]
@danschultzer Thank you for your quick response! 

I'm trying to integrate with Phoenix LiveView and there is no `conn` (only `socket` value) there,
do you happen to know how  to handle it?

**Comment by danschultzer** [comment]
The issue I linked with https://github.com/danschultzer/pow/issues/61#issuecomment-451779111 has the example without `conn`. It’s for absinthe integration.

You may be able to just pass in the socket though, since it closely relates to `conn`. You just have to set the config with `Pow.Plug.

**Comment by sunloverz** [comment]
Thanks @danschultzer ! It works like a charm :)
