### ISSUE TITLE
Limit Reset Password email sending

### ISSUE THREAD

**Issue by popo63301** [danschultzer/pow#357]
How can we limit the reset password emails number allowed for a user? If the number of reset password emails possible is unlimited, I see it as a potential  threat for an app because someone can loop through the process and yield huge costs for email sending.

**Comment by danschultzer** [comment]
Yeah, I've been thinking about this before.

I think this is something that should be handled either at the e-mail delivery API, or with a rate limiter in the `MyAppWeb.PowMailer` module. Definitely would be good to have a section about this in the docs, at least in the [production checklist guide](https://hexdocs.pm/pow/1.0.15/production_checklist.html#content).

`PowEmailConfirmation` is another extension where it's possible to spam out large amounts of e-mails.

**Comment by danschultzer** [comment]
Added section in #368 with a simple example using Hammer.
