### ISSUE TITLE
Double send error on session creation

### ISSUE THREAD

**Issue by liamwhite** [danschultzer/pow#361]
Seeing a lot of these in my error logs:
```
Request: POST /session
** (exit) an exception was raised:
    ** (Plug.Conn.AlreadySentError) the response was already sent
        (plug) lib/plug/conn.ex:580: Plug.Conn.resp/3
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.action/2
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (philomena) lib/philomena_web/endpoint.ex:1: PhilomenaWeb.Endpoint.plug_builder_call/2
        (philomena) lib/philomena_web/endpoint.ex:1: PhilomenaWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
15:51:38.829 [error] #PID<0.22254.0> running PhilomenaWeb.Endpoint (connection #PID<0.22252.0>, stream id 1) terminated
```

Thoughts on how that could happen?

**Comment by danschultzer** [comment]
Do you have any custom callbacks or plugs that are triggered? I think this may happen if `Plug.Conn.halt/1` was not called properly and it tries to redirect/render after redirect has already been set in the response.

**Comment by liamwhite** [comment]
I have [this](https://github.com/derpibooru/philomena/blob/master/lib/pow_lockout/phoenix/controllers/controller_callbacks.ex#L38), which is probably the culprit.

What do I need to return in the `before_respond` callback if the request is halted?

**Comment by danschultzer** [comment]
I think it may [be this](https://github.com/derpibooru/philomena/blob/master/lib/pow_lockout/phoenix/controllers/controller_callbacks.ex#L76-L84). Does the log happen when that warning is shown?

If so, I would add `halt()` after so it looks like this:

```elixir
  defp invalid_credentials(conn) do
    {:ok, conn} =
      Plug.clear_authenticated_user(conn)

    conn
    |> Conn.assign(:changeset, Plug.change_user(conn, conn.params["user"]))
    |> Controller.put_flash(:error, messages(conn).invalid_credentials(conn))
    |> Controller.render("new.html")
    |> Conn.halt()
  end
```

The response is good otherwise and it shouldn't process any further. I suspect it might be [one of the plugs](https://github.com/danschultzer/pow/blob/v1.0.15/lib/pow/phoenix/controllers/session_controller.ex#L13-L17) that adds something though you already have set the response.

**Comment by liamwhite** [comment]
For the record, I [added `halt` here](https://github.com/derpibooru/philomena/blob/master/lib/pow_lockout/phoenix/controllers/controller_callbacks.ex#L84) and it is still double rendering.

```
Request: POST /session
** (exit) an exception was raised:
    ** (Plug.Conn.AlreadySentError) the response was already sent
        (plug) lib/plug/conn.ex:580: Plug.Conn.resp/3
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.action/2
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (philomena) lib/philomena_web/endpoint.ex:1: PhilomenaWeb.Endpoint.plug_builder_call/2
        (philomena) lib/philomena_web/endpoint.ex:1: PhilomenaWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
```

**Comment by liamwhite** [comment]
A quick investigation (now that I have had the time) revealed that actions are handled as follows:
https://github.com/danschultzer/pow/blob/203b0a6b755868ebe7c7c42bdb8865f475630c90/lib/pow/phoenix/controllers/controller.ex#L92-L102

Since I have a `before_respond` callback installed, this is invoked with the result of the callback:
https://github.com/danschultzer/pow/blob/203b0a6b755868ebe7c7c42bdb8865f475630c90/lib/pow/phoenix/controllers/controller.ex#L108-L111

That then finally calls this, which finishes the response pipeline:
https://github.com/danschultzer/pow/blob/203b0a6b755868ebe7c7c42bdb8865f475630c90/lib/pow/phoenix/controllers/session_controller.ex#L39-L51

Since I am returning `{:error, conn}` instead of `{:halt, conn}`, `respond_action` does not care that the conn is halted, and passes it the already-rendered conn on to the session controller instead, which then renders again and raises the AlreadySentError.

I realized that I have no need to halt this and treat it specially (and in fact, doing so could cause information leakage). All I need to do is clear the user from the session, if it exists, and then show the regular session error page:
```elixir
  defp maybe_fail_attempt(user, conn, _error) do
    PowLockoutPlug.fail_attempt(conn, user)
    |> case do
      {:error, _changeset, conn} ->
        {:halt, conn}

      {:ok, %{locked_at: nil}, conn} ->
        {:error, invalid_credentials(conn)}

      {:ok, user, conn} ->
        send_unlock_email(user, conn)

        {:error, invalid_credentials(conn)}
    end
  end

  defp invalid_credentials(conn) do
    {:ok, conn} = Plug.clear_authenticated_user(conn)

    conn
  end
```

That seems to have cut off the error entirely. I haven't seen it in the error log since I deployed the change. So, sorry to bother you again with something that's not a bug.

**Comment by danschultzer** [comment]
Great that you figured it out!
