### ISSUE TITLE
SameSite cookie support for persistent sessions

### ISSUE THREAD

**Issue by liamwhite** [danschultzer/pow#362]
SameSite cookie support is fairly easy for the session:
```elixir
  # endpoint.ex

  plug Plug.Session,
    store: :cookie,
    extra: "SameSite=Lax",
    # ...
```
...but doesn't appear to be possible at all for the persistent session extension, because [none of the cookie options are configurable except the max-age](https://github.com/danschultzer/pow/blob/203b0a6b755868ebe7c7c42bdb8865f475630c90/lib/extensions/persistent_session/plug/cookie.ex#L305-L307).

**Comment by danschultzer** [comment]
Great thought. Implemented in #365, thanks!
