### ISSUE TITLE
Possible issue in umbrella docs

### ISSUE THREAD

**Issue by christophweegen** [danschultzer/pow#370]
[Umbrella guides](https://github.com/danschultzer/pow/blob/master/guides/umbrella_project.md) state 
> config/config.ex is inside the Phoenix app(s)

I just created a new umbrella project and there's just a global `config/` dir, but not a separate place of config inside `my_app_web`. 

Is that line maybe a reminiscence to an older phoenix version?

Otherwise that line is a bit misleading and could potentially be phrased better.

Thanks!

**Comment by danschultzer** [comment]
You're right. I've updated the umbrella guide for Elixir 1.9, thanks 😄
