### ISSUE TITLE
Session plug ignores custom get_by

### ISSUE THREAD

**Issue by jandudulski** [danschultzer/pow#371]
Hi,

I was trying to follow `users_context` with `get_by` trick to preload associations for current user (as suggested in different issues) but as far as I was able to dig only persisted session actually uses that function.

For regular Session I had to do this:

```
  def authenticate(params) do
    case pow_authenticate(params) do
      nil -> nil
      user -> user |> preload_assocs()
    end
  end

  defp preload_assocs(user) do
   ...
  end
```

since `authenticate` function is actually dynamically selected. I guess in [this place](https://github.com/danschultzer/pow/blob/v1.0.15/lib/pow/ecto/context.ex#L112) needs somehow be able to use `get_by` from using module.

**Comment by danschultzer** [comment]
Yep, I'm working on it in #343.
