### ISSUE TITLE
"not same as password" is not localized

### ISSUE THREAD

**Issue by krystofbe** [danschultzer/pow#378]
Hi,
thanks for this awesome lib. Do i see this correctly, that the passwords do not match message cannot be localized?
https://github.com/danschultzer/pow/blob/b1d4904492ea85287ec0845a1d9bb4635df17989/lib/pow/ecto/schema/changeset.ex#L215

**Comment by danschultzer** [comment]
How do you currently translate ecto errors?

Usually you would use the [`MyAppWeb.ErrorHelpers`](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/views/error_helpers.ex) for translations. Also note that `v1.0.17 (#380 #379) will change that message to "does not match confirmation" so it matches the default in Ecto for confirmation validation.

**Comment by krystofbe** [comment]
Yes, sorry misunderstandig, i thought there was some way to add error translations automatically like with `mix gettext.extract --merge`

I just added a translation for "not same as password" to `errors.po`
