### ISSUE TITLE
Getting current active users.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#38]
We can get `current active users` from several places; phoenix channel, google analytics. But I think the real data can only get from `credential store`.

There's a similar fn `Pow.Store.CredentialsCache.sessions/3`, but this shows a list of sessions for a given user.

So, how about support fn which list up current active users? This is a fancy and unique fn, too!

**Comment by danschultzer** [comment]
Yeah, that would be a useful feature. It'll only require adding a `all` method in `Pow.Store.Base` and the store modules.

**Comment by danschultzer** [comment]
Sorry for the delay, had a lot of other work coming up, but finally added this with #44.
