### ISSUE TITLE
two different registration forms  

### ISSUE THREAD

**Issue by krystofbe** [danschultzer/pow#388]
Hello :) !

I was just wondering: What would be the right way to add two different registration forms? In my app there are two different roles that would be able to register, each with slightly different registration changesets (e.g. role1 needs to enter an address which role2 doesn't)

How would i do this without copying and modifying the whole registration controller?

**Comment by danschultzer** [comment]
I would recommend using a custom controller, especially if you will use two different URI's. It's more code, but you'll have better control over the flow. In that case you should set up individual `:new` and `:create` methods for each role.

It should be possible to use the default controller though. You may be able to handle it in the view/templates (from the top of my head):

```elixir
defmodule MyAppWeb.Pow.RegistrationView do
  use MyAppWeb, :view

  def render_form(assigns) do
    case role(assigns[:conn]) do
      :role2 ->  render "_role2_form.html", assigns
      _any   ->  render "_role1_form.html", assigns
    end
  end

  defp role(%{params: %{"user" => %{"role" => "role2"}}}), do: :role2
  defp role(_conn), do: role1
end
```

```elixir
<%= render_form(assigns) %>
```

Then you link to the registration form with: `link("Register", to: pow_registration_path(@conn, :new,  user: [role: "role2"]))`. It assumes that the role will always be in the params, so when you go to the `:new` template it'll use the GET query, and when you get a changeset error creating the user, it'll use the POST params.

You can handle it in the changeset from there on. Please be careful and make sure that there is no issue with the user being able to directly change the role in the form though.

```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  schema "users" do
    field :role, :string, default: "role1"
    # ...

    pow_user_fields()

    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> role_changeset(attrs)
    |> validate_for_role(attrs)
  end

  defp role_changeset(changeset, attrs) do
    case Ecto.get_meta(changeset.data, :state) do
      :built ->
        changeset
        |> cast(attrs, [:role])
        |> validate_inclusion(:role, ~w(role1 role2))

      _any ->
        changeset
    end
  end

  defp validate_for_role(changeset, attrs) do
    case get_field(changeset, :role) do
      "role1" -> validate_address(changeset, attrs)
      _any    -> changeset
    end
  end

  defp validate_adddress(changeset, attrs) do
    # ...
  end
end
```

In the above the role can't be changed if the user has been persisted, but the address will always be validated for users who has `role1` role.

Alternatively you can use [custom context](https://hexdocs.pm/pow/1.0.16/Pow.Ecto.Context.html#content). The [user roles guide](https://hexdocs.pm/pow/1.0.16/user_roles.html#content) might be worth checking out.

**Comment by krystofbe** [comment]
wow! thank you for the detailed answer. really appreciate it!
