### ISSUE TITLE
PowPersistentSession doesn't interact with DB storage.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#39]
In my website `pow` is equipped with three included extensions. And whenever I restarted the server, all the sessions are gone away.

I expected that the `PowPersistentSession` stores credentials into DB layer, but there's no additional migration.

Is this feature intended or under development?

**Comment by danschultzer** [comment]
It should be working with mnesia that you enabled in #37. It sounds like mnesia is not actually running.

I’m out of town, but will be able to detail how to ensure mnesia is running when I’m back next week.

**Comment by danschultzer** [comment]
Can you post your current pow config? I want to check that mnesia has been enabled as default store.

**Comment by jung-hunsoo** [comment]
It's working properly when I preserved mnesia directory. No problem.

**Comment by danschultzer** [comment]
That’s great!

Just a quick side note: Persistent session is a long term token that can be used once to create a session token. By default, it will be stored the same place sessions are stored, so if the default ETS cache backend is used as the cache store then it’ll be lost at each restart.

**Comment by jung-hunsoo** [comment]
That's reasonable. I think this is a useful info for users to know.

**Comment by danschultzer** [comment]
Yeah, I’ll  update the docs.
