### ISSUE TITLE
Guest mode

### ISSUE THREAD

**Issue by lud** [danschultzer/pow#397]
Hi, 

I would like to make a guest mode for my game : users can play the game (.i.e. access the auth-required pages and have a user_id) without registering.

So, is it possible to create an user account and connect the user (create a session) without having an email ?

**Comment by danschultzer** [comment]
Yeah, it's possible but you have to make a custom changeset method, and permit `nil` value for the `:email` field. If you still keep the regular user flow, then you should create a custom controller and context for guest registration. If you already have the user migration in production, then you should create a new one that permit `:email` field to be `NULL`.

Here's how it could work from the top of my head:

```elixir
defmodule MyApp.Repo.Migrations.PermitNullForUserEmail do
  use Ecto.Migration

  def change do
    alter table(:users) do
      modify :email, :string, null: true
    end
  end
end
```

```elixir
  use Ecto.Schema
  use Pow.Ecto.Schema
  
  alias Ecto.Changeset

  schema "users" do
    field :email, :string

    pow_user_fields()

    timestamps()
  end

  @spec guest_changeset(Ecto.Schema.t() | Ecto.Changeset.t()) :: Ecto.Changeset.t()
  def guest_changeset(user_or_changeset, attrs) do
    Changeset.cast(user_or_changeset, attrs, [])
    # Add any requirements here
  end
end
```

```elixir
defmodule MyApp.Users do
  alias MyApp.Users.User

  @spec create_guest(map()) :: {:ok, map()} | {:error, map()}
  def create_guest(params) do
    %User{}
    |> User.guest_changeset()
    |> Repo.insert()
  end
end
```

```elixir
defmodule MyAppWeb.GuestRegistrationController do
  use MyAppWeb, :controller

  @spec create(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def create(conn, params) do
    case MyApp.Users.create_guest(params) do
      {:ok, user} ->
        conn
        |> create_session(user)
        |> put_flash(:info, "Welcome!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def create_session(conn, user) do
    config = Pow.Plug.fetch_config(conn)
    plug   = Pow.Plug.get_plug(config)

    plug.do_create(conn, user, config)
  end
end
```

From there on you can add more logic so people can persist their guest account by updating it with email/password, and clean out periodically stale accounts with a cron job.

**Comment by lud** [comment]
That's perfect, thank you very much :)

**Comment by lud** [comment]
For the record.

I would like the persistent session to be created. I've just added `PowPersistentSession.Plug.create(conn, user)`. It seems to set the cookie, so I guess it is fine.

```elixir
  defp create_session(conn, user) do
    config = Pow.Plug.fetch_config(conn)
    plug = Pow.Plug.get_plug(config)

    conn
    |> plug.do_create(user, config)
    |> PowPersistentSession.Plug.create(user)
  end
```

**Comment by danschultzer** [comment]
Yup, that's the way to handle it!
