### ISSUE TITLE
testing Phoenix view helper with conn passed raise Pow.Config.ConfigError

### ISSUE THREAD

**Issue by pironim** [danschultzer/pow#402]
Hi folks.

I'm trying to use sort of helper function in my layout view
```
# apps/web/lib/web/views/layout_view.ex
defmodule Web.LayoutView do
  def main_logo_path(conn) do
    if Pow.Plug.current_user(conn) do
      Routes.room_path(conn, :show)
    else
      Routes.page_path(conn, :index)
    end
end
```

layout contain link with method call and everything working as expected
```
# apps/web/lib/web/templates/layout/header.html.eex
...
<%= link to: main_logo_path(Pow.Plug.current_user(@conn)) do %>
...
```

when I'm trying to test new method there always 
```
     ** (Pow.Config.ConfigError) Pow configuration not found in connection. Please use a Pow plug that puts the Pow configuration in the plug connection.
     code: assert LayoutView.main_logo_path(conn) =~ 'ololo'
     stacktrace:
       (pow) lib/pow/config.ex:56: Pow.Config.raise_error/1
       (pow) lib/pow/plug.ex:18: Pow.Plug.current_user/1
       (web) lib/web/views/layout_view.ex:9: Web.LayoutView.main_logo_path/1
       test/web/views/layout_view_test.exs:15: (test)

```

Testing code has no tricks:

```
 defmodule Web.LayoutViewTest do
  use Web.ConnCase, async: true
  alias Web.LayoutView

  describe "main_logo_path/1" do
    test 'returns room page if user passed', %{conn: conn} do
      assert LayoutView.main_logo_path(conn) =~ '/room'
    end
  end
 end
```

When assert line copied to any controller test with some small changes it works fine without errors 
like
```
assert Web.LayoutView.main_logo_path(conn) =~ '/room'
```
^ just to resolve alias.
per my understanding view test require some additional code to load pow config
I inspect conn for controllers and view and view does not have :pow_config defined
is there any way to load it explicitly

**Comment by danschultzer** [comment]
Since the endpoint is not used outside controller tests, you have to manually set the Pow config. It can be done in a `setup` step:

```elixir
 defmodule Web.LayoutViewTest do
  use Web.ConnCase, async: true
  alias Web.LayoutView

  setup %{conn: conn} do
    {:ok, conn: Pow.Plug.put_config(otp_app: :my_app)}
  end

  describe "main_logo_path/1" do
    test 'returns room page if user passed', %{conn: conn} do
      assert LayoutView.main_logo_path(conn) =~ '/room'
    end
  end
 end
```

Could also be done in the `Web.LayoutView` module.

**Comment by pironim** [comment]
```Pow.Plug.put_config``` working fine.
per my understanding second option with some additional code for Web.LayoutView
can be useful when *view* called separately from *controller* and assume *Pow.Plug.put_config* inside method before usage

**Comment by danschultzer** [comment]
Yup, though it doesn't change anything in the controller tests. In the controller tests, the `plug Pow.Plug.Session` in the endpoint module will just override any existing Pow config in the `conn`.

**Comment by pironim** [comment]
Thanks
