### ISSUE TITLE
Writing a plug-in guideline

### ISSUE THREAD

**Issue by nesimtunc** [danschultzer/pow#410]
Hi,

It would  be great to have a guideline about how to implement a feature as a plug-in into `pow`. I'd like to implement an `username` feature; I could just extend the current implementation but I prefer to do it as a plug-in so other people may use it.

Thank you!

**Comment by danschultzer** [comment]
What would the username plugin do? You can easily switch the user id field like this:

```elixir

defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema, user_id_field: :username

  schema "users" do
    pow_user_fields()

    timestamps()
  end
end
```

**Comment by nesimtunc** [comment]
Oh! I didn't know that feature. Sorry my bad, I might have miss it from the guide. Just would like to have `username` _property_ to use it in my web site for socializing feature.

**Comment by danschultzer** [comment]
Yeah, in that case the above would work. If you have both username and email, you only need to customize the changeset:

```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  schema "users" do
    field :username, :string

    pow_user_fields()

    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> Ecto.Changeset.cast(attrs, [:username])
    |> Ecto.Changeset.validate_required([:username])
    |> Changeset.unique_constraint(:username)
    |> pow_changeset(attrs)
  end
end
```
