### ISSUE TITLE
API Documentation small mistake

### ISSUE THREAD

**Issue by invacto** [danschultzer/pow#415]
In the API documentation, session controller "json/2" gets called with conn even though conn is already in the pipeline.

https://github.com/danschultzer/pow/blob/master/guides/api.md#add-api-controllers

![image](https://user-images.githubusercontent.com/35679622/74109883-cf5f0300-4b87-11ea-9f3a-c60e3cad73cd.png)

**Comment by danschultzer** [comment]
Thanks! Fixed in #416
