### ISSUE TITLE
Can sign in even though email has not been confirmed

### ISSUE THREAD

**Issue by alukito** [danschultzer/pow#419]
I'm using PowEmailConfirmation extension to prevent users from signing in when the email is not yet confirmed. I have set it up according to the guide, and test that the callbacks are called accordingly. 

The problem I'm facing is even though the user's email has not been confirmed, they can sign in into protected page. It is as if the session has not been cleared.

I think it only happened in Pow 1.0.17, because when I test 1.0.16, the behaviour is correct as expected.

**Comment by danschultzer** [comment]
Can you share more details about your setup? Is this just default Pow, or custom controllers?

The thing that comes to mind is this PR that registers before send (the session is first written when the request has been processed): https://github.com/danschultzer/pow/pull/398

But the tests should show that it still works correctly: https://github.com/danschultzer/pow/blob/v1.0.17/test/extensions/email_confirmation/phoenix/controllers/controller_callbacks_test.exs#L13-L26

**Comment by danschultzer** [comment]
Can you try `{:pow, github: "danschultzer/pow", ref: "fix-delete-session"}`, and tell me if it works? It should fix the issue. Once confirmed I'll release `v1.0.18` with this fix.

**Comment by alukito** [comment]
I have tested the branch `fix-delete-session` and it works now. Thanks for your help @danschultzer.

**Comment by danschultzer** [comment]
`v1.0.18` released 🚀
