### ISSUE TITLE
mix pow.install doesn't work

### ISSUE THREAD

**Issue by NAR** [danschultzer/pow#42]
Hello!

I tried to follow the installation instructions: added `pow` to the dependencies, fetched the dependencies using `mix deps.get`, then executed the `mix pow.install` command, but got this error:

`** (Mix) Could not load UserProfileManager.Repo, error: :nofile. Please configure your app accordingly or pass a repo with the -r option.
`

What could be the problem? My project is under an umbrella. The output from `mix deps.get` is this:

Running dependency resolution...
Dependency resolution completed:
  cowboy 1.1.2
  cowlib 1.0.2
  decimal 1.5.0
  ecto 2.2.11
  file_system 0.2.6
  gettext 0.16.0
  mime 1.3.0
  phoenix 1.3.4
  phoenix_ecto 3.5.0
  phoenix_html 2.12.0
  phoenix_live_reload 1.1.7
  phoenix_pubsub 1.1.0
  plug 1.6.4
  poison 3.1.0
  poolboy 1.5.1
  pow 1.0.0-rc.4
  ranch 1.3.2
All dependencies up to date

**Comment by danschultzer** [comment]
Run `mix pow.ecto.install -r MyApp.Repo` inside your ecto app. Sounds like you've ran the mix task inside your phoenix app, so it has just guessed that the ecto app was there too.

**Comment by danschultzer** [comment]
Replace `MyApp.Repo` with your actual repo module name.

**Comment by danschultzer** [comment]
Updated the readme with a note on umbrella projects: https://github.com/danschultzer/pow#getting-started-phoenix

**Comment by NAR** [comment]
Thanks, I managed to start `pow`.
