### ISSUE TITLE
issue with extensions docs?

### ISSUE THREAD

**Issue by nordbit** [danschultzer/pow#423]
Phoenix 1.4.13
pow 1.0.18
migration from coherence to pow
```
% mix pow.extension.ecto.gen.migrations --extension PowResetPassword --extension PowPersistentSession
Warning: No migration file generated for PowResetPassword as it doesn't require any migrations.
Warning: No migration file generated for PowPersistentSession as it doesn't require any migrations.
```
```
% mix pow.extension.phoenix.gen.templates --extension PowEmailConfirmation
Warning: No view or template files generated for PowEmailConfirmation as no templates has been defined for it.
```

**Comment by danschultzer** [comment]
No issue, it works as expected. The warnings are there to notify the user that no files will be generated for those extensions. This is so they don't wonder if something was not working when they don't see files for some of the extensions. It's still recommended to run them all in the mix tasks so you don't miss something.

**Comment by buddhisthead** [comment]
I'm sorry to belabor this point, but can you clarify what is meant by "It's still recommended to run them all in the mix tasks so you don't miss something"? Thanks.

**Comment by danschultzer** [comment]
@buddhisthead It's just for comfort so you don't have to figure out what extension you forgot to add in case you missed one. Instead of guessing what extensions generates what and only call the appropriate ones, it's recommended to run them all, e.g. if you add both `PowEmailConfirmation` and `PowResetPassword` at the same time then it's better to run:

> mix pow.extension.phoenix.gen.templates --extension PowResetPassword --extension PowEmailConfirmation

Instead of just what's needed:

> mix pow.extension.phoenix.gen.templates --extension PowResetPassword

**Comment by buddhisthead** [comment]
Hi @danschultzer Thank you very much for your kind reply. That makes sense to me.
I'm very new to your library but it's been so fast and easy to integrate with! I apologize if the following is off topic and I'm happy to open a new issue for this discussion if you'd like.

I ran `mix pow.extension...` template generators together as recommended and saw the same message at @nordbit.
```Warning: No view or template files generated for PowEmailConfirmation as no templates has been defined for it.```
I ignored this and built out the remaining files as your excellent setup guide suggested. I've configured this to work with MailGun without much trouble, but upon testing the email confirmation feature, I had an undefined view:
```function MisparWeb.PowMailer.PowEmailConfirmation.MailerView.subject/2 is undefined (module MisparWeb.PowMailer.PowEmailConfirmation.MailerView is not available)```
And so I looked around and indeed there is no viewer defined for the confirmation, but I see that one was generated for password reset:
```
#pow_reset_password/mailer_view.ex:
defmodule MisparWeb.PowResetPassword.MailerView do
  use MisparWeb, :mailer_view

  def subject(:reset_password, _assigns), do: "Reset password link"
end
```
And I see that the missing function is `subject/2` from the email confirmation. Did I forget a step or do I need to build my own mailer_view for email confirmation.
Thank you again for your time.

**Comment by buddhisthead** [comment]
Oh man, I'm such a dork. The above comment is true, but I ran the generator command again and voila! I now have a `pow_email_confirmation/mailer_view.ex`. I wish I could tell you my exact steps, but I can't recall how to repro this. I haven't actually tried to run this yet, but will do so now.

**Comment by buddhisthead** [comment]
Okay, still getting a runtime error with missing the `subject/2` function, but let me see if I can find my error.

**Comment by buddhisthead** [comment]
I found my problem, which was just a matter of correcting which module I was using. This could have all stemmed from that; and I apologize for using your time.
