### ISSUE TITLE
argument error on session create

### ISSUE THREAD

**Issue by augnustin** [danschultzer/pow#424]
I'm finally moving from coherence to pow. :-D

I followed the very clear guide and it went pretty good.

Unfortunately I have an error on session create:

```
ArgumentError at POST /session
argument error

Called with 2 arguments
1. Pow.Store.Backend.EtsCache
2. [{{["credentials", MyApp.User, :user, 1324, :session, :_], :_}, [], [:"$_"]}]
```

Here's the stacktrace:

![image](https://user-images.githubusercontent.com/1970156/74664401-ef9d4c00-519d-11ea-8c8b-a8f1338b3c6e.png)

I may have missed something but I don't think so.

Here's my config:

```
      {:phoenix, "~> 1.4.0"},
      {:ecto, "~> 3.3.2"},
      {:ecto_sql, "~> 3.3.4"},
      {:phoenix_ecto, "~> 4.1.0"},
      {:pow, "~> 1.0.18"},
      {:comeonin, "~> 3.0"},

```

**Comment by danschultzer** [comment]
Cool!

This is just a simple `:ets.select` call, so if you are not running any old version of Elixir/OTP, then I would imagine there is some issue with the supervision tree restarting something, like the `Pow.Store.Backend.EtsCache` GenServer. The GenServer initializes the ETS table in protected mode so only the process creating it has access to it. If it gets restarted or crashes then I believe you would experience this error.

In any case, in production you should switch over to Mensia or Redis which would eliminate this issue: https://github.com/danschultzer/pow/#cache-store

**Comment by augnustin** [comment]
Thanks for getting back.

I forgot to add the `:pow,` in the extra applications. This is the `mnesia` guide which took me to the road.

Not sure what it is used for yet though, but it works. :smile:

**Comment by danschultzer** [comment]
Oh right, newer Elixir projects will auto start the apps in dependencies. Mnesia is a distributed database, kinda ETS that works across multiple nodes and with persistence. With the ETS store all sessions will be lost when you restart or deploy in production, the Mnesia store will persist the data to disk.

**Comment by augnustin** [comment]
Indeed, storing sessions in memory is not acceptable for production. 

Haven't succeeded to setup mnesia on the first try, will try again, but I'm wondering if it would make sense to also have the possibility to use [`dets`](https://erlang.org/doc/man/dets.html) as the API is the same as `Ets`.

Of course this doesn't work for distributed systems, but if it is not the case, this would avoid the overcost of setting up mnesia, wouldn't it?

**Comment by danschultzer** [comment]
Mnesia is built on top of ETS/DETS so it's the same, just a lot better for this purpose. Mnesia is a core part of OTP, there shouldn't be a overhead. What error did you see?

The docs have the instructions to set it up: https://hexdocs.pm/pow/1.0.18/Pow.Store.Backend.MnesiaCache.html#content

`:mnesia` has to be added to `:extra_applications` in `mix.exs` to work with mix releases. I remember you had some older mix setup, so this might be necessary to also run in dev for you.
