### ISSUE TITLE
Where is the Bcrypt salt?

### ISSUE THREAD

**Issue by augnustin** [danschultzer/pow#425]
Still trying to migrate from Coherence.

Not sure my previous issue is fixed, but now it seems like the comparison occurs, but the encrypted password is different from the one stored. 

I tried to dive into `comeonin` and `bcrypt` to understand what's going on, and my guess is that the `salt` to the encryption methods is different.

Hence my question: where does the salt come from? It doesn't seem to be in a kind of `config` entry, and sometimes it is `hash_pwd_salt\1` available, sometimes `hashpwdsalt\2` so I'm confused.

How can I make sure not all my users will have to reset their password? :smile: 

Cheers

**Comment by OvermindDL1** [comment]
Unsure of how pow is doing it specifically, but bcrypt itself has the salt be part of the encrypted data.  Something like "$enctype$salt$encdata" or something like that.

**Comment by Schultzer** [comment]
Make sure that you are using the same version of Comeonin as when you started the project.

I did some searches on Coherence and Comeonin which didn't show any breaking changes. 
- https://github.com/smpallen99/coherence/search?q=password_hashing_alg&unscoped_q=password_hashing_alg
- https://github.com/riverrun/comeonin/blob/master/CHANGELOG.md

Maybe this is a good occasion to actually force your users to reset there password and use something else then bcrypt like Argon2.

**Comment by danschultzer** [comment]
@OvermindDL1 is correct, the salt is part of the stored password hash value.

@Schultzer is also correct that this most likely is just an issue with configuration of comeonin. It definitely worked the last time I tested the guide.

Seems like there has been [some changes with comeonin v5](https://github.com/riverrun/comeonin/blob/9f3c98561e1c6c258969a20c0e492bb08da462a6/UPGRADE_v5.md#upgrading-to-version-5) so the macro opts now should be:

```elixir
defmodule MyApp.User do
  use Ecto.Schema
  use Pow.Ecto.Schema,
    password_hash_methods: {&Bcrypt.hash_pwd_salt/1,
                            &Bcrypt.verify_pass/2}

  # ...
end
```

I'll have to adjust the guide.

**Comment by augnustin** [comment]
Thanks for your support guys.

I'm very confused because the mistake was on my side: I forgot that I had been importing the production DB locally so my password had changed in between.

It works very well for me now, with

```
  use Pow.Ecto.Schema,
    password_hash_methods: {&Bcrypt.hash_pwd_salt/1,
                            &Bcrypt.verify_pass/2}
```

```
      {:pow, "~> 1.0.18"},
      {:bcrypt_elixir, "~> 1.1.1"}, # the actual version that was in my mix.lock
```

`Comeonin` doesn't seem to be even required.
