### ISSUE TITLE
Make password confirmation optional on registration

### ISSUE THREAD

**Issue by augnustin** [danschultzer/pow#426]
In our app, we decided not to enforce the user to rewrite password confirmation.

In coherence, if the field `:password_confirmation` was empty, it was ignored, but with pow it seems like it's failing in this case.

How can I make it optional here?

Thanks

**Comment by Schultzer** [comment]
In this case you should really create your own changeset and handle it there, Pow are using Ecto to validate confirm.

I would just copy paste the default changeset from pow and then change the parts you don't want.

**Comment by danschultzer** [comment]
As @schultzer says, you have to customize the changeset. The docs has an example of where you remove password confirmation validation: https://hexdocs.pm/pow/1.0.18/Pow.Ecto.Schema.html#module-customize-pow-changeset
