### ISSUE TITLE
Deprecated information always called using IO.warn

### ISSUE THREAD

**Issue by alukito** [danschultzer/pow#432]
Hello, I'm using pow v1.0.18 and finds that everytime a user is created, a warning with full stacktrace is generated using IO.warn. 

```
warning: warning: passing `confirm_password` value to `Pow.Ecto.Schema.Changeset.confirm_password_changeset/3` has been deprecated, please use `password_confirmation` instead
  (pow) lib/pow/ecto/schema/changeset.ex:120: Pow.Ecto.Schema.Changeset.convert_confirm_password_param/2
  (pow) lib/pow/ecto/schema/changeset.ex:65: Pow.Ecto.Schema.Changeset.password_changeset/3
 ....
```

Is this intentional? I think this could interfere with some people's logging and monitoring system as they usually do some string matching on the log.

**Comment by danschultzer** [comment]
It’s intentional. You should update your custom templates and change the `:confirm_password` field to `:password_confirmation`. It’s a soft deprecation warning so you can fix the issue before it’ll be a breaking change in v1.1.0.

**Comment by alukito** [comment]
Ah, I see, I'll change it then. Just to make user, I don't have to do any Ecto migration right?

**Comment by danschultzer** [comment]
No just the templates have to be changed, it’s the variables being passed to the changeset that it warns about.

**Comment by alukito** [comment]
Got it. Thanks.
