### ISSUE TITLE
Change redirection paths to conn transformation

### ISSUE THREAD

**Issue by augnustin** [danschultzer/pow#440]
Instead of

```
  def after_registration_path(conn) do
    Routes.root_path(conn, :index)
  end
```

which returns a binary, I'd expect this callback to return a `conn` so I can fully customize it:

```
  def after_registration(conn) do
    conn
    |> put_flash(:success, "You are now logged in")
    |> redirect(to: Routes.root_path(conn, :index))
  end
```

I hopped I could do that with controller callbacks, but this issue https://github.com/danschultzer/pow/issues/82 proved me wrong.

**Comment by danschultzer** [comment]
You can change the [flash message](https://hexdocs.pm/pow/1.0.18/README.html#i18n).

If you wish to change the controller flow by adding a custom flash message type (and otherwise change the conn) then you have to handle it in a custom controller. Controllers [are slim](https://hexdocs.pm/pow/1.0.18/README.html#phoenix-controllers) and mostly depends of a single plug method call. This makes it very easy to [set up custom controllers](https://hexdocs.pm/pow/1.0.18/custom_controllers.html#content).

**Comment by augnustin** [comment]
Setting up custom controllers seems like your way to go but I am not a big fan of this approach:

- customizing flash + route + template *can* be not enough 
- if decide to use a custom controller, I have to rewrite every methods of the controller, not only the one I need to customize. 
  - This is obviously not DRY, despite most of the logic being in the `Plug`. 
  - This is much more error prone
  - This brings much more authentication logic code into the code base

In the spirit of pow being a middleware-with-default-behaviors, I find it much more natural to work on the `conn` object, which is the actual philosophy of phoenix. Having flash + route + template would be a default behavior here.

Take this change I made on my own branch: https://github.com/danschultzer/pow/pull/434/commits/4053a4bca4fe2b80c1d7e1410985c6ef34ea3c20#diff-05ff0800d39ee8078fef08153267751e

```
# Pow.Phoenix.Routes
  def after_registration(conn, routes_module \\ __MODULE__) do
    conn
    |> put_flash(:info, messages(conn).user_has_been_created(conn))
    |> redirect(to: routes_module.after_registration_path(conn))
  end

  def after_registration_path(conn, routes_module \\ __MODULE__), do: routes_module.after_sign_in_path(conn)
```

And the controller:

```
# Pow.Phoenix.RegistrationController

  @spec respond_create({:ok | :error, map(), Conn.t()}) :: Conn.t()
  def respond_create({:ok, _user, conn}) do
    routes(conn).after_registration(conn)
  end
  def respond_create({:error, changeset, conn}) do
    conn
    |> assign(:changeset, changeset)
    |> render("new.html")
  end
```

In my case, I simply use

```
  def after_sign_in(conn) do
    create_or_get_application(conn)
  end

  def after_registration(conn) do
    create_or_get_application(conn)
  end

  defp create_or_get_application(conn) do
    user = Pow.Plug.current_user(conn)

    if is_nil(user) do
      redirect(conn, to: Routes.root_path(conn, :index))
    else
      object_id = Plug.Conn.get_session(conn, :object_id)
      other_object_id = Plug.Conn.get_session(conn, :other_object_id)

          case Application.find_or_create_with_params(%{
            user_id: user.id,
            object_id: object_id,
            other_object_id: other_object_id
          }) do
            {:ok, application} ->
              conn
              |> put_flash(:success, "Here is your application")
              |> redirect(to: Routes.application_path(conn, :show, application.id))
            {:error, _error} -> 
              conn
              |> put_flash(:error, "Could not create")
              |> redirect(to: Routes.root_path(conn, :index))
         end
  end
```

This is:
- clearer to read/customize
- DRY
- backward compatible

If you agree, I could definitely PR this separately (my current PR is trash, I keep it only for the diff).

The callback logic could also work though.

**Comment by danschultzer** [comment]
You don't need to override all controller actions, only the one you are customizing. See these examples:

https://hexdocs.pm/pow/1.0.18/lock_users.html#optional-powresetpassword
https://github.com/danschultzer/pow/issues/387#issuecomment-574419374
https://github.com/danschultzer/pow/issues/203#issuecomment-496556495
