### ISSUE TITLE
Use Cloak with Pow to encrypt user emails

### ISSUE THREAD

**Issue by robinvdvleuten** [danschultzer/pow#445]
As a business / GDPR requirement, I need to encrypt all user related data (name, address, email, etc.). I've tried to install Cloak through theses steps (https://hexdocs.pm/cloak_ecto/install.html#content), but in ran into the issue that Pow expects the `:email` property to be a `:string`. Is it possible to override this behaviour?

**Comment by Schultzer** [comment]
You could just change the `:email` column to `:binary` in your user migration file.

**Comment by robinvdvleuten** [comment]
I did, but then I run into the error thrown by the Pow schema (https://github.com/danschultzer/pow/blob/master/lib/pow/ecto/schema.ex#L394).

**Comment by Schultzer** [comment]
Is this still true if you follow this https://github.com/danschultzer/pow/blob/a1b9416c34a954ae3628bbb8bc26c2c11f78e6b8/lib/pow/ecto/schema.ex#L97#L115

**Comment by robinvdvleuten** [comment]
I've tried to rename the email field using the `:source` option when defining the schema, maybe that's what causing it. But it would be nice though if Pow supports that option though :-)

**Comment by robinvdvleuten** [comment]
So I've tried to map the `:email` field to a `:email_encrypted` column.

**Comment by Schultzer** [comment]
Could you provide an example repo?

I’m not sure what you are trying to accomplish but you should be able to just write out the migration and schema files and then you need to make sure you are hashing your email before you look it up, that would properly require a custom session controller or override a function in your user context.

**Comment by danschultzer** [comment]
Interesting situation!

I think for now your only option is to ignore the `use Pow.Ecto.Schema` macro, and set it up the fields and methods yourself as you are only able to override fields with the same name and type. Could look like this:

```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema

  @behaviour Pow.Ecto.Schema

  schema "users" do
    field :email,            MyApp.Encrypted.Binary
    field :email_hash,       Cloak.Ecto.SHA256
    field :password_hash,    :string
    field :current_password, :string, virtual: true
    field :password,         :string, virtual: true
    field :confirm_password, :string, virtual: true

    timestamps()
  end

  @pow_config [] # This is what would be in the macro opts for `use Pow.Ecto.Schema, ...`

  @impl true
  def changeset(user_or_changeset, attrs) do
    pow_changeset (user_or_changeset, attrs)
  end

  defp pow_changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> Pow.Ecto.Changeset.user_id_field_changeset(attrs, @pow_config)
    |> Pow.Ecto.Changeset.current_password_changeset(attrs, @pow_config)
    |> Pow.Ecto.Changeset.password_changeset(attrs, @pow_config)
  end

  @impl true
  def verify_password(user, password) do
    Pow.Ecto.Changeset.verify_password(user, password, @pow_config)
  end

  def pow_user_id_field, do: :email
end
```

I would be very interested to hear if this just works. I've only read the cloak docs superficially so not sure if there would be some issue later down the road with e.g. email lookup in Ecto.

Also I would prefer if the above was much easier. I'll check if it makes sense to implement a change so you can just ignore the error and change a field type. It was done this way so devs don't accidentally introduce buggy setup, but it's kinda overzealous.

**Comment by danschultzer** [comment]
> Also I would prefer if the above was much easier. I'll check if it makes sense to implement a change so you can just ignore the error and change a field type. It was done this way so devs don't accidentally introduce buggy setup, but it's kinda overzealous.

Got a solution up in #447 so you can just override the raise error logic in any way you see fit.

**Comment by robinvdvleuten** [comment]
@danschultzer I've bypassed the error logic by not using the `Pow.Ecto.Schema` macro. My schema now looks like this;

```elixir
defmodule MyApp.User do
  use MyApp.Schema

  @behaviour Pow.Ecto.Schema

  @pow_config [
    password_hash_methods: {&Argon2.hash_pwd_salt/1, &Argon2.verify_pass/2}
  ]

  schema "users" do
    field :first_name, :string
    field :last_name, MyApp.Ecto.EncryptedBinary, source: :last_name_encrypted
    field :email, MyApp.Ecto.EncryptedBinary, source: :email_encrypted
    field :email_hash, Cloak.Ecto.SHA256
    field :password_hash, :string
    field :current_password, :string, virtual: true
    field :password, :string, virtual: true
    field :confirm_password, :string, virtual: true

    timestamps()
  end

  @impl true
  def changeset(user_or_changeset, attrs) do
    pow_changeset(user_or_changeset, attrs)
  end

  defp pow_changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> Pow.Ecto.Schema.Changeset.user_id_field_changeset(attrs, @pow_config)
    |> Pow.Ecto.Schema.Changeset.current_password_changeset(attrs, @pow_config)
    |> Pow.Ecto.Schema.Changeset.password_changeset(attrs, @pow_config)
    |> put_change(:email_hash, get_field(user_or_changeset, :email))
  end

  @impl true
  def verify_password(user, password) do
    IO.inspect user
    IO.inspect password

    Pow.Ecto.Schema.Changeset.verify_password(user, password, @pow_config)
  end

  def pow_user_id_field, do: :email_hash
end
```

But then I ran into the issue that no user can be found by the `email_hash` field  (which should be working "out of the box", if I look at [Cloak's documentation](https://hexdocs.pm/cloak_ecto/Cloak.Ecto.SHA256.html)).

So then I tried to override the user's context with the following;

```elixir
defmodule MyApp.Users do
  use MyApp.Context

  use Pow.Ecto.Context,
    repo: MyApp.Repo,
    user: MyApp.User

  @impl true
  def authenticate(params) do
	# Replace `email` with `email_hash` so it gets picked up by Cloak.
    params
    |> Map.put("email_hash", params["email"])
    |> Map.delete("email")
    |> pow_authenticate()
  end

  @impl true
  def get_by(clauses) do
	# This never gets called...
    pow_get_by(clauses)
  end
end
```

But somehow `get_by` never gets called (I double checked that I'm using `1.0.18`).

**Comment by danschultzer** [comment]
You should do this instead:

```elixir
defmodule MyApp.Users do
  use MyApp.Context

  use Pow.Ecto.Context,
    repo: MyApp.Repo,
    user: MyApp.User

  @impl true
  def get_by(clauses) do
    clauses
    |> Enum.map(fn
      {:email, email} -> {:email_hash, email}
      {key, value}    -> {key, value}
    end)
    |> pow_get_by()
  end
end
```

You want to make sure that for any look up `:email` is changed to `:email_hash`. Remember that if you use `PowEmailConfirmation` you should also handle `:unconfirmed_email`.

**Comment by danschultzer** [comment]
@robinvdvleuten the error raise has been removed with #455. It didn't really make sense to raise instead of just emitting warning.

If you pull from git master (`{:pow, github: "danschultzer/pow"}`) you can use this for the user schema:

```elixir
defmodule MyApp.User do
  use Ecto.Schema
  use Pow.Ecto.Schema,
    password_hash_methods: {&Argon2.hash_pwd_salt/1, &Argon2.verify_pass/2}

  schema "users" do
    field :first_name, :string
    field :last_name, MyApp.Ecto.EncryptedBinary, source: :last_name_encrypted
    field :email, MyApp.Ecto.EncryptedBinary, source: :email_encrypted
    field :email_hash, Cloak.Ecto.SHA256

    pow_fields()

    timestamps()
  end

  @impl true
  def changeset(user_or_changeset, attrs) do
    changeset =  pow_changeset(user_or_changeset , attrs)

    put_change(changeset, :email_hash, get_field(changeset, :email))
  end
end

**Comment by robinvdvleuten** [comment]
@danschultzer I still get an error from Pow when using the latest version;

```
field/association :email is already set on schema
```

I've used exactly the schema you showed in your latest comment.

**Comment by danschultzer** [comment]
Sorry, updated the example, just keep all the fields as you originally had them and remove `pow_fields/0`.

**Comment by rafaeliga** [comment]
@danschultzer @robinvdvleuten what about email duplication validation? Is there any example app with cloak setup?

**Comment by robinvdvleuten** [comment]
@rafaeliga you should be able to use the email_hash field to see if there are already users with a similar email address.
