### ISSUE TITLE
Update user with last login or logout

### ISSUE THREAD

**Issue by astrinh0** [danschultzer/pow#448]
Hello everyone, im doing a project with pow. I want to add a field of datetime on my schema to when logout save that date and time. i need some examples please :smile: 

```elixir
defmodule ApiBrandit.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema
  use Pow.Extension.Ecto.Schema,
    extensions: [PowResetPassword, PowEmailConfirmation]
  use Timex

  schema "users" do

    field :name, :string
    field :logindate, :utc_datetime


    pow_user_fields()

    timestamps()
  end



  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> Ecto.Changeset.cast(attrs, [:name, :logindate])
    |> Ecto.Changeset.validate_required([:name])

  end

end
```

One more thing, anyone got a tutorial to add a api key to this project?

**Comment by danschultzer** [comment]
Do you mean log in or log out? In any case you would need to handle it with [custom controllers](https://hexdocs.pm/pow/1.0.18/custom_controllers.html#content) since no user update happens on login/logout.

> One more thing, anyone got a tutorial to add a api key to this project?

If you mean API layer, then this guide can help you: https://hexdocs.pm/pow/1.0.18/api.html#content

**Comment by astrinh0** [comment]
def delete(conn, _params) do
    conn
    |> Pow.Plug.delete()
    |> redirect(to: Routes.page_path(conn, :index))
  end

now here what i do to get the user field to update?

**Comment by danschultzer** [comment]
Could look like this:

```elixir
def delete(conn, _params) do
  update_logout(Pow.Plug.current_user(conn))

  conn
  |> Pow.Plug.delete()
  |> redirect(to: Routes.page_path(conn, :index))
end

defp update_logout(nil), do: :ok
defp update_logout(user) do
  user
  |> User.logout_changeset()
  |> Repo.update()
end
```

Then add a `logout_changeset/1` method to the `User` schema module where you put the change. You could also just have a context method for it depending how you build the app (e.g. `Users.update_logout(user)`).
