### ISSUE TITLE
template instructions not working

### ISSUE THREAD

**Issue by mithereal** [danschultzer/pow#449]
i have followed the instructions for creating a new session template but the changes arent reflected 

mix pow.phoenix.gen.templates

and in config

config :api, :pow,
  user: Api.Users.User,
  repo: DB.Repo,
  web_module: ApiWeb

**Comment by danschultzer** [comment]
What error do you get?

**Comment by mithereal** [comment]
there is no error the default pow templates are being used, theyre not overriduing with myne

**Comment by Schultzer** [comment]
Can you share an example repo that reproduce this issue?

**Comment by ArneVogel** [comment]
I have the same issue. Templates generated with `mix pow.phoenix.gen.templates` and added `web_module: ListudyWeb` to the [pow config](https://github.com/ArneVogel/listudy/blob/master/config/config.exs#L41). Edits to `lib/listudy_web/templates/pow/registration/edit.html.eex` are not being shown on the page.

Related to that, are there examples of allowing users to delete their account after confirming their password?
