### ISSUE TITLE
:request_path is not used after sign in

### ISSUE THREAD

**Issue by abartier** [danschultzer/pow#453]
Hello, 

In an app where at first I was testing custom pow modifications (controllers, routes...) I went back to the standard and clean pow use case.

But the redirect to the `:request_path` params after sign-in didn't work. 
I see the params in the url when I'm redirected to the session/new form but the redirect never happened. I always get back to "/". 

I have to add a hidden input in the form and override the routes to set a custom `after_sign_in_path()` to be able to redirect the user properly.
 
As I read in #346 this should work out of the box but I don't know what I'm missing. 

Views and templates have been generated and modified.

config.exs:

```
config :my_app, :pow,
  user: MyApp.Users.User,
  repo: MyApp.Repo,
  mailer_backend: MyAppWeb.Mailers.PowMailer,
  web_module: MyAppWeb,
  extensions: [PowResetPassword, PowPersistentSession],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  routes_backend: MyAppWeb.Pow.Routes
```

Workaround: 

```
defmodule MyAppWeb.Pow.Routes do
  use Pow.Phoenix.Routes
  alias MyAppWeb.Router.Helpers, as: Routes

  def after_sign_in_path(%{params: %{"user" => %{"request_path" => ""}}}), do: "/admin"
  def after_sign_in_path(%{params: %{"user" => %{"request_path" => request_path}}}) when is_binary(request_path), do: request_path
  def after_sign_in_path(_conn), do: "/"
end
```

Versions: 
```
{:phoenix, "~> 1.4.13"}
{:pow, "~> 1.0.18"}
```

**Comment by danschultzer** [comment]
The assigns key is used: https://github.com/danschultzer/pow/blob/v1.0.18/lib/pow/phoenix/routes.ex#L118-L128

```elixir
  @doc """
  Path to redirect user to when user has signed in.
  This will look for a `:request_path` assigns key, and redirect to this value
  if it exists.
  """
  def after_sign_in_path(params, routes_module \\ __MODULE__)
  def after_sign_in_path(%{assigns: %{request_path: request_path}}, _routes_module) when is_binary(request_path),
    do: request_path

  def after_sign_in_path(_params, _routes_module), do: "/"
```

And the default Pow controller assigns it: https://github.com/danschultzer/pow/blob/v1.0.18/lib/pow/phoenix/controllers/session_controller.ex#L65-L68

```elixir
  defp assign_request_path(%{params: %{"request_path" => request_path}} = conn, _opts) do
    Conn.assign(conn, :request_path, request_path)
  end
  defp assign_request_path(conn, _opts), do: conn
```

Do you use custom controllers?

**Comment by abartier** [comment]
No I did not use custom controllers. 
I see thoses line in the pow code, that's why I think I'm missing something. 

Here are my router.ex

```

defmodule MyAppWeb.Router do
  use MyAppWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword, PowPersistentSession]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :admin_layout do
    plug :put_layout, {MyAppWeb.LayoutView, "admin.html"}
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through [:browser]

    # Use pow_routes() if registration is needed
    # pow_routes()
    pow_session_routes()
    pow_extension_routes()

    if Mix.env == :dev do
      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/", MyAppWeb do
    pipe_through [:browser]

    get "/", PageController, :index

  end

  scope "/admin", MyAppWeb do
    pipe_through [:browser, :protected, :admin_layout]

    get "/", AdminController, :dashboard
    resources "/users", UserController
  end

end


```

**Comment by danschultzer** [comment]
What form action do you have, do you use the `@action` assign or are you hard coding the route?

**Comment by abartier** [comment]
Here's my session/new.html.eex

```
<%= form_for @changeset, Routes.pow_session_path(@conn, :create), fn f -> %>
...
<% end %>
```

**Comment by abartier** [comment]
Is there a way to break pow execution to see where the assigns :request_path was last seen? 
I see the param in the url on the new action but I can't tell if it's passed to the create action.

**Comment by danschultzer** [comment]
Change the form to:

```elixir
<%= form_for @changeset, @action, fn f -> %>
...
<% end %>
```

This is the missing piece: https://github.com/danschultzer/pow/blob/v1.0.18/lib/pow/phoenix/controllers/session_controller.ex#L74-L79

Otherwise you can build the route with `Routes.pow_session_path(@conn, :create, request_path: @conn.assigns[:request_path])`

**Comment by abartier** [comment]
Yes, that was it! 
Thanks! I knew I was missing something. 

I do believe this came from the custom controllers time, I suppose I just changed the route in the form and do not use the one usually generated by pow.
