### ISSUE TITLE
Custom email templates

### ISSUE THREAD

**Issue by Kaquadu** [danschultzer/pow#459]
Hello,
I'm currently struggling with emails in my system. I'm trying to write custom templates for the confirmation email and the password reset email. My mailer is still sending default templates, even after I followed the guide in readme.md, configured the app and made custom templates.

Config for pow:
```
config :bolig, :pow,
  user: Bolig.Auth.User,
  repo: Bolig.Repo,
  extensions: [PowResetPassword, PowEmailConfirmation],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  mailer_backend: BoligWeb.Mailer,
  cache_store_backend: Pow.Store.Backend.MnesiaCache,
  credentials_cache_store: {Pow.Store.CredentialsCache, ttl: :timer.minutes(15)},
  web_module: BoligWeb,
  web_mailer_module: BoligWeb,
  routes_backend: BoligWeb.Pow.UserRoutes,
  current_user_assigns_key: :current_user,
  session_ttl_renewal: :timer.minutes(14)
```

My `mailer_view`:
```
...
def mailer_view do
    quote do
      use Phoenix.View, root: "lib/bolig_web/templates",
                        namespace: BoligWeb

      use Phoenix.HTML
      import BoligWeb.Gettext
    end
  end
...
```

I would appreciate any advice.

**Comment by danschultzer** [comment]
Hmm, I don't see any issue with your configuration, this should work. Can you try recompile the whole project to be sure it uses the new config value?

If it still doesn't work, do you have any custom logic that may interfere with Pow?

**Comment by Kaquadu** [comment]
> Hmm, I don't see any issue with your configuration, this should work. Can you try recompile the whole project to be sure it uses the new config value?
> 
> If it still doesn't work, do you have any custom logic that may interfere with Pow?

The only logic that interfere the Pow flow is changing user to admin in the router:

```
pipeline :pow_admin do
    plug :set_pow_config,
      repo: Bolig.Repo,
      user: Bolig.Auth.Admin,
      current_user_assigns_key: :current_admin,
      session_key: "admin_auth",
      routes_backend: BoligWeb.Pow.AdminRoutes,
      plug: Pow.Plug.Session,
      cache_store_backend: Pow.Store.Backend.MnesiaCache,
      credentials_cache_store: {Pow.Store.CredentialsCache, ttl: :timer.minutes(480)},
      web_module: BoligWeb,
      session_ttl_renewal: :timer.minutes(180)
  end
```

and some small changes in user paths, witch are independent I guess? Or am I wrong?

```
defmodule BoligWeb.Pow.UserRoutes do
  ... other not important paths ...

  def after_registration_path(conn) do
    conn
    |> Phoenix.Controller.put_flash(
      :info,
      gettext("Registration succesful. Email with confirmation link has been sent.")
    )
    |> Routes.pow_session_path(:new)
  end
end
```

**Comment by danschultzer** [comment]
> The only logic that interfere the Pow flow is changing user to admin in the router when entering admin paths:

So to be clear, the custom mailer templates are not used as expected when you are testing with the regular `Bolig.Auth.User` user right? This doesn't have anything to do with the admin user (I don't see any extensions enabled)?

This also caught my eye:

```elixir
  def after_registration_path(conn) do
    conn
    |> Phoenix.Controller.put_flash(
      :info,
      gettext("Registration succesful. Email with confirmation link has been sent.")
    )
    |> Routes.pow_session_path(:new)
  end
```

The `PowEmailConfirmation` extension should block access until the email has confirmed, so curious what happens here. You did want to override the `pow_email_confirmation_email_confirmation_required` message instead.

**Comment by Kaquadu** [comment]
Yep, admin user is separate part of the system and it doesn't need emails support.

As I said - when generating custom email templates the old ones are sent. So when user makes an account the basic template is sent instead the one I made.

The rest works fine - user can't access account until he confirms email. Only templates are the issue.

Good catch, didn't notice that 👍 I just wanted to override the message you mentioned. Thanks for that.

**Comment by danschultzer** [comment]
Without knowing more about the app, I'm not sure what goes wrong here.

You got both the config, and the `mailer_view` macro right. The `mailer_view` macro should also be referenced in the generated mailer views with `use BoligWeb, :mailer_view`. I would double check the templates inside `"lib/bolig_web/templates"`.

**Comment by Kaquadu** [comment]
I'm gonna try to reproduce it in separate app as soon as I'll have a moment 😄

**Comment by Kaquadu** [comment]
Sorry that it took so long.. I just spotted that I had templates in a wrong folder. Insert facepalm. :) Thank's for helping me.
