### ISSUE TITLE
Consolidating Namespaces in guides vs readme. 

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#466]
I was wondering about the logic for the two types of namespacing I'm seeing.

In the guides, I see a common use of `MyAppWeb.PowSomething` wherein the ReadMe I see `MyAppWeb.Pow.Something` 

Note: the diff if not easily seen is the period between the Pow and Something. 
Is there reasoning around the discrepancies in namespaces? 
My pref would be to have everything under`MyAppWeb.Pow.Something`

Thoughts?

**Comment by danschultzer** [comment]
Good catch, I agree it should all be the same. I can see much of the module documentation also uses the `MyAppWeb.Pow.` namespace.

Not sure which is better, but personally I use `MyAppWeb.Pow.Something` more. It looks cleaner and also fits well with folder structure if you put it under a `pow/` folder. OTOH `PowSomething` is easier to understand when using aliases than `Something`, and I've seen that being recommended before to prevent module name collusions.

**Comment by joshchernoff** [comment]
I'm happy to tackle the renames if you want to agree to on convention. again my preference would be to use `MyAppWeb.Pow.`

**Comment by danschultzer** [comment]
Yup, let's change it to `MyAppWeb.Pow.`. Thanks!

**Comment by joshchernoff** [comment]
I hope you don't mind I also fixed a few small grammar things Grammarly tagged.
