### ISSUE TITLE
User registration if email exists

### ISSUE THREAD

**Issue by pelmenept** [danschultzer/pow#467]
When user tries to register new account, but email already exists in the system, they get an error:
"Oops something went wrong".

When user tries to register new account, but email already exists in the system, and extension "Email Confirmation" is enabled, the flashed message is:
"You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you."

Second response is probably incorrect behavior, it probably should be the same as the first "Oops something went wrong".

Additionally, in both of these cases, pow attempts to insert new user into DB without checking if email already exists. Or course insert fails due to constraint. I might be wrong, but pow probably should not attempt insert when email is already taken.

Also I have a question. I need to create an account in another system (let's say stripe) when new user is registered (but not invited). Where would be the best place to do it ?

Best regards.

**Comment by danschultzer** [comment]
> When user tries to register new account, but email already exists in the system, and extension "Email Confirmation" is enabled, the flashed message is:
"You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you."

It's correct behavior and it's to prevent user enumeration attacks. The docs describe this in detail:

https://hexdocs.pm/pow/1.0.19/pow_email_confirmation.html#content
https://hexdocs.pm/pow/1.0.19/security_practices.html#user-enumeration-attacks

You can turn it off by setting `pow_prevent_user_enumeration: false` in `conn.private` (e.g. in a plug).

> Additionally, in both of these cases, pow attempts to insert new user into DB without checking if email already exists. Or course insert fails due to constraint. I might be wrong, but pow probably should not attempt insert when email is already taken.

This is how Ecto constraint works, it relies on the db for unique constraint to ensure data integrity. It's described here: https://hexdocs.pm/ecto/Ecto.Changeset.html#module-validations-and-constraints

> I need to create an account in another system (let's say stripe) when new user is registered (but not invited). Where would be the best place to do it ?

I would set that up with `Ecto.Multi` with a custom [users contexts module](https://hexdocs.pm/pow/1.0.19/Pow.Ecto.Context.html#content).

**Comment by pelmenept** [comment]
Thank you very much for your answer.

Yep, I've read about enumeration prevention. My point is, when email confirmation extension is enabled, it breaks enumeration prevention, since it returns: 
"You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you."

Which gives an attacker hint that user and email intact exist in db.
