### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by BryanJBryce** [danschultzer/pow#47]
What are the goals for 1.0? What will it take to move from rc to 1.0?

**Comment by danschultzer** [comment]
When I've resolved #19 it'll be released. I'm making sure that the structure in Pow 1.0 is flexible enough, and this is the last bit I need to fix.

**Comment by danschultzer** [comment]
To be more specific: I'll need to figure out how to share multiple Pow session contexts in the same plug connection reasonably (e.g. admin and user session). I think I'm pretty close to having it ready, but have been delayed by work.

**Comment by BryanJBryce** [comment]
Awesome, thanks!

**Comment by danschultzer** [comment]
FYI 1.0.0 has been released today 🚀
