### ISSUE TITLE
missing .tools-version

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#470]
Seeing a bunch fo warnings while running the specs locally. I assume I maybe just using the wrong target for erlang/elixir. I think a .tools-version file would be useful if not a call out in the readme for which version we should be targeting. 

Heres an example of the warnings I'm seeing while running specs. 
```
warning: Pow.Store.Backend.MnesiaCache.keys/1 is deprecated. Use `all/2` instead
  test/pow/store/backend/mnesia_cache_test.exs:120: Pow.Store.Backend.MnesiaCacheTest."test single node backwards compatible"/1
```

**Comment by danschultzer** [comment]
That's expected. It's because I'm testing deprecations that'll be removed in `v1.1.0`. I def should capture all those warnings though, let me see what I can do.

**Comment by joshchernoff** [comment]
No prob, I just wanted to see if there is spec on which specific version of erlang / elixir I should be using when developing pow.
