### ISSUE TITLE
CreateUsers migration field password_hash is nullable

### ISSUE THREAD

**Issue by Ciboulette** [danschultzer/pow#480]
Hey guys,

I'm installing Pow right now, I've just noticed that the field `password_hash` for the `CreateUsers` migration is `nullable`. Is it something we want? any reason?

Take care 🧙‍♂️

**Comment by danschultzer** [comment]
If you use [PowAssent](https://github.com/pow-auth/pow_assent) (or any custom alternative auth mechanism) it has to be nullable. No problem changing it for your particular setup though, the default Pow changeset requires `password_hash`.

**Comment by Ciboulette** [comment]
Thanks for the clarification, I close the issue
