### ISSUE TITLE
Change Language Error Tag

### ISSUE THREAD

**Issue by jagoanmamah** [danschultzer/pow#484]
I want to change the error tag to my language
![download](https://user-images.githubusercontent.com/25195185/78839716-36335800-7a23-11ea-957f-1c84c9c30d08.png)
![download (1)](https://user-images.githubusercontent.com/25195185/78839724-392e4880-7a23-11ea-8668-78cc970ec0c8.png)

**Comment by danschultzer** [comment]
It depends how you translate ecto error messages now. You would normally use the `MyAppWeb.ErrorHelpers` module in your Phoenix app, and manually add the errors to `errors.po`.

More here:
https://elixirforum.com/t/translate-ecto-validation-messages/5469
https://elixirforum.com/t/schema-internationalization-localization/21096

Also see https://github.com/danschultzer/pow/issues/378.

**Comment by jagoanmamah** [comment]
how about

"The provided login details did not work. Please verify your credentials, and try again."

Where does it come from?

**Comment by danschultzer** [comment]
It's detailed here: https://hexdocs.pm/pow/1.0.19/README.html#i18n

**Comment by jagoanmamah** [comment]
I get an error like this after add messages_backend: PowdepsWeb.Pow.Messages to my configuration

![acdbf10c-3562-4cad-af4f-bddefdca034d](https://user-images.githubusercontent.com/25195185/78854326-35aeb780-7a4b-11ea-8846-7731026900ee.png)

**Comment by jagoanmamah** [comment]
what funtion for this error
![ccac74ca-5d97-4f88-bb1f-9a95884fe5f0](https://user-images.githubusercontent.com/25195185/78857204-f1271a00-7a52-11ea-8737-730487264426.png)

I tried all of these functions but it didn't work

![5083600f-b4f0-43b1-b1ba-ab316724f795](https://user-images.githubusercontent.com/25195185/78857214-f71cfb00-7a52-11ea-9673-9e6049c5caed.png)

**Comment by danschultzer** [comment]
It's described in the linked docs that you need to add the extension name to the method:

```
  # Message methods for extensions has to be prepended with the snake cased
  # extension name. So the `email_has_been_sent/1` method from
  # `PowResetPassword` is written as `pow_reset_password_email_has_been_sent/1`
  # in your messages module.
```

So it should look like this:

```elixir
  def pow_email_confirmation_email_confirmation_required(_conn), do: gettext("You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you.")
```
