### ISSUE TITLE
No migration file generated for PowResetPassword

### ISSUE THREAD

**Issue by jagoanmamah** [danschultzer/pow#486]
![Screenshot from 2020-04-11 02-15-40](https://user-images.githubusercontent.com/25195185/79020160-46be0c80-7ba2-11ea-8cb4-d4fea5152c3c.png)

**Comment by danschultzer** [comment]
Same as #485

This is to be expected for extensions that doesn't have migrations like `PowResetPassword`. I've reworded it in #487 so it's more clear.
