### ISSUE TITLE
mix pow.install Match Error  - Pow phoenix 1.4 branch 

### ISSUE THREAD

**Issue by abartier** [danschultzer/pow#49]
Hello, 

I'm trying to test pow in a new phoenix 1.4 app. 
The mix task pow.install return this: 
```

mix pow.install -r Powtest.Repo Accounts.User users
** (MatchError) no match of right hand side value: :undefined
    lib/pow.ex:9: Pow.dependency_vsn_match?/2
    lib/mix/pow/ecto/migration.ex:69: Mix.Pow.Ecto.Migration.source_repo_priv/1
    lib/mix/pow/ecto/migration.ex:15: Mix.Pow.Ecto.Migration.create_migration_files/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    lib/mix/tasks/ecto/pow.ecto.install.ex:49: Mix.Tasks.Pow.Ecto.Install.maybe_run_gen_migration/2
    lib/mix/tasks/ecto/pow.ecto.install.ex:41: Mix.Tasks.Pow.Ecto.Install.run/1
    lib/mix/tasks/pow.install.ex:38: Mix.Tasks.Pow.Install.run_ecto_install/2
    lib/mix/tasks/pow.install.ex:31: Mix.Tasks.Pow.Install.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

Can you provide a user.ex file and the typical migration pow required ?

**Comment by danschultzer** [comment]
You're using the branch in https://github.com/danschultzer/pow/pull/18 ? Good catch, haven't tested it out thoroughly. Could you send me your dependency list in `mix.exs`?

In any case, I've rebased, and it should work now 🤞

**Comment by abartier** [comment]
Yes I think that's the branch I'm using. 

Here are my dependencies, just the regular ones from a mix phx.new: 

```
defp deps do
    [
      {:phoenix, "~> 1.4.0-rc"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 3.5"},
      {:ecto, "~> 3.0-rc", override: true},
      {:ecto_sql, "~> 3.0-rc", override: true},
      {:postgrex, ">= 0.0.0-rc"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2-rc", only: :dev},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:pow, git: "https://github.com/danschultzer/pow", branch: "phoenix-1.4"}
    ]
  end
```

If it's not working, I'll try to use the content of the files generated in a blank phx 1.3 app. 
I want to try pow with 1.4 before using it in a real app ;)

**Comment by abartier** [comment]
Yes it's working right now! Thanks I'm closing this. 
I'll open other issues if I see something on the branch 1.4!

**Comment by danschultzer** [comment]
Cool, thanks a lot! :smile: And please open an issue if you encounter anything, the feedback helps me a lot!

**Comment by abartier** [comment]
Yes I will do for sure! 
I just send you a quick email for other points (didn't want to pollute the issues).

**Comment by danschultzer** [comment]
Just an update, Ecto 3.0 and Phoenix 1.4 support has been merged into the master branch, I'll finish up Pow for the 1.0.0 release ASAP 😄
