### ISSUE TITLE
password_hash not being generated when testing custom SessionController

### ISSUE THREAD

**Issue by mwojtul** [danschultzer/pow#50]
Hi, great library!

Thanks to how configurable it is I've been able to use it in my app which is just an API. I'm trying to write tests for my `SessionController` and when POSTing valid credentials, it seems like the password_hash never gets generated. It works fine outside of the test which leads me to believe it might be a config I need to set somewhere... any idea what I might be missing?

**Comment by danschultzer** [comment]
I would need to see some of the code in your SessionControllerTest to understand that issue, but a guess would be that you don't create the fixture using the Pow changeset:

```elixir
@valid_params %{
  "email" => "john.doe@example.com",
  "password" => "secret1234",
  "confirm_password" => "secret1234"
}

%User{}
|> User.changeset(%User{}, @valid_params)
|> Repo.insert()
```

If this is not what's wrong, can you post the code for the test that fails?

**Comment by mwojtul** [comment]
Thanks, that was it 👍. Was using Ecto to create a factory but wasn't using the Pow changeset.
