### ISSUE TITLE
Can I use UUID for user id

### ISSUE THREAD

**Issue by camstuart** [danschultzer/pow#502]
Hi,

Fantastic library BTW!

When I created my phoenix app, I used:

`mix phx.new myapp --database postgres --binary-id --live` 

As I am hoping to have UUID instead of serial primary keys.
Is it possible to modify my pow setup to support this?

**Comment by danschultzer** [comment]
Thanks!

Yup, you should be able to pass in `--binary-id` for the Pow mix tasks (only needed for the migration step(s)). Pow doesn't [make any assumptions](https://github.com/danschultzer/pow/issues/83#issuecomment-462842459) to the primary key type.

**Comment by camstuart** [comment]
Thanks @danschultzer thats great to know, as you suggest, I had already created migrations as a result of mix tasks for pow.

So, based on your suggestion I made the following changes:

-> migration file to create user table:
```elixir
defmodule MyApp.Repo.Migrations.CreateUsers do
  use Ecto.Migration

  def change do
    create table(:users, primary_key: false) do # disables creation of id column
      add :id, :uuid, primary_key: true         # create the required id column as a uuid type, nominated as primary key
      add :email, :string, null: false
      add :password_hash, :string

      timestamps()
    end

    create unique_index(:users, [:email])
  end
end
```

-> And in the schema file, I added some module attributes:
```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  @primary_key {:id, :binary_id, autogenerate: true} # added
  @foreign_key_type :binary_id                       # added
  schema "users" do
    pow_user_fields()

    timestamps()
  end
end
```

As a side note, my test database needed to be rebuilt because of the change in datatype:
```bash
MIX_ENV=test mix ecto.drop
MIX_ENV=test mix ecto.create
MIX_ENV=test mix ecto.migrate
```

Once again thanks, for your reply and great work on this library!

**Comment by danschultzer** [comment]
Looks good, thanks for posting the code!

**Comment by aphillipo** [comment]
Hey! This is extremely useful, but I can't help think that if you have a mix project setup with --binary_id by default it should be respected by pow by default. Not a big deal as this isn't done very often but I guess a nice to have?

**Comment by danschultzer** [comment]
@aphillipo You are correct. I've opened #668 to use the `config :otp_app, :generators` configuration for the default options. I would appreciate if you could test it and see if it works as expected now, not having to set the flag.
