### ISSUE TITLE
Inconsistency in the API documentation

### ISSUE THREAD

**Issue by blascsi** [danschultzer/pow#504]
So I'm fairly new to POW, and this might be a misunderstanding.

In the [API guide](https://hexdocs.pm/pow/api.html#api-authorization-plug-for-pow) in the inline documentation it says: 
> ` The renewal token is deleted by fetching it from the access token metadata.`

However after the code snippet, the documentation says:

> Be aware that the delete method doesn't invalidate the renewal token, since we only receive the auth token.

Wasn't the renewal token invalidated by deleting it? Or do I not understand this correctly?

If this is just an old piece of info, I'm happy to make a PR removing this line. But if this is something that I understood the wrong way please feel free to close this issue.

Thanks for the help!

**Comment by danschultzer** [comment]
You are right, it's old info that I forgot to remove after https://github.com/danschultzer/pow/pull/454. Feel free to open a PR, thanks!

**Comment by blascsi** [comment]
I have made the PR! If any changes are needed feel free to tell me. 
Thank you for all the work you put into this project!
