### ISSUE TITLE
Modify Controller

### ISSUE THREAD

**Issue by jagoanmamah** [danschultzer/pow#509]
I want to add @setting, how to change the controller?

![a78ccb14-7880-4bf8-b600-d11b495b5310](https://user-images.githubusercontent.com/25195185/80683879-11e10d80-8aef-11ea-9c35-f5b5e1dfa001.png)

**Comment by danschultzer** [comment]
Where do you get settings from, and how do you normally assign it? You can set it in a plug in your router pipeline, calling `Plug.Conn.assign/3`, but depends what `@setting` is.

**Comment by jagoanmamah** [comment]
setting are obtained this way

![Screenshot 2020-05-01 06:01:55](https://user-images.githubusercontent.com/25195185/80767214-996f6080-8b71-11ea-88e9-4910c3b0a3c8.png)

**Comment by danschultzer** [comment]
In this case I would load it in a custom plug:

```elixir
defmodule MyAppWeb.LoadSettingPlug do
  def init(config), do: config

  def call(conn, config) do
    setting = Adjustments.get_setting_first!()

    Plug.Conn.assign(conn, :setting, setting)
  end
end
```

Then you can add it to your browser pipeline in your router:

```elixir
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MyAppWeb.LoadSettingPlug
  end

  # ...
end
```

Now setting will be loaded for all pages.
