### ISSUE TITLE
PowEmailConfirmation extension can easily be hacked

### ISSUE THREAD

**Issue by intpl** [danschultzer/pow#512]
Hi, I noticed a person can easily ignore e-mail confirmation restrictions in Pow-using app and change e-mail to any e-mail. I uploaded an example git repository for you to easily reproduce this.

Steps to reproduce:
```
git clone https://github.com/intpl/pow_email_confirmation_issue && cd pow_email_confirmation_issue
vim config/dev.exs
mix deps.get && mix ecto.setup
mix phx.server
```
1. create an account using http://localhost:4000/registration/new
2. copy and open confirmation link from the terminal
3. sign in
4. navigate to http://localhost:4000/registration/edit
5. fill in current password, change email to "hacked@hacked" and submit
6. it does not change, awaits confirmation, right?
7. ...right?
8. don't refresh. repeat step 5
9. email has been changed to "hacked@hacked"

Same issue occurs in my other app with custom controllers. I guess issue is with `Pow.Plug.update_user` or the extension. What may be helpful is that I could not easily reproduce the issue in tests. On the other hand, I didn't try for long.

**Comment by danschultzer** [comment]
Thanks @intpl! I'm able to replicate the issue. Going through Pow now to see how this is possible.

**Comment by danschultzer** [comment]
Found the PR culprit: https://github.com/danschultzer/pow/pull/259

Embarrassing bug. I've set up a PR to resolve it in #515. I can confirm that I can no longer reproduce the bug in the demo repo using that PR. I'll release a new version of Pow today or tomorrow. Thanks a lot @intpl!

**Comment by intpl** [comment]
No wories! Thank you for addressing it on such short notice!!!
