### ISSUE TITLE
Pow session sign out error

### ISSUE THREAD

**Issue by hassamali** [danschultzer/pow#517]
i installed pow elixir package for phoenix authentication management,registeration route its working but when i am trying to sign out with pow session with method delete its not working and complaining

> no route found for GET /session (QazalbashWeb.Router)

with the pow and session these are only available routes

```
pow_session_path  GET     /session/new                             Pow.Phoenix.SessionController :new
pow_session_path  POST    /session                                 Pow.Phoenix.SessionController :create
pow_session_path  DELETE  /session                                 Pow.Phoenix.SessionController :delete
```

What i am doing on the front-end is this, Register is working fine but not sign out

```
<%= link "Sign Out", to: Routes.pow_session_path(@conn, :delete), method: :delete  %>
<%= link "Register", to: Routes.pow_registration_path(@conn, :new) %>
```

**Comment by danschultzer** [comment]
Make sure that you got `import "phoenix_html"` in your JS, and restart the server if necessary. This is just a default [Phoenix HTML anchor link](https://hexdocs.pm/phoenix_html/2.14.2/Phoenix.HTML.Link.html#link/2-javascript-dependency), and will work as long as the JS is enabled and `priv/static/phoenix_html.js` has been loaded into your build tools.

**Comment by hassamali** [comment]
import "phoenix_html" this was there in file but with errors i fixed the errors in this file and it fixed the solution. Thank you
