### ISSUE TITLE
New app with LiveView enabled, error after login

### ISSUE THREAD

**Issue by dimitarvp** [danschultzer/pow#522]
After making a rather normal Phoenix 1.5.3 app with LiveView enabled I went to install Pow using the steps described in the Hexdocs page. Excerpt from `router.ex`:

```elixir
  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated, error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser
    pow_routes()
  end

  scope "/", EdxmlWeb do
    pipe_through [:browser, :protected]

    # ...a few custom routes for my app are here...

    live "/", PageLive, :index
  end
```

When visiting `localhost:4000` I get redirected to the sign in page, where I do sign in:

```plain
[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{}
  Pipelines: [:browser, :protected]
[info] Sent 302 in 34ms
[info] GET /session/new
[debug] Processing with Pow.Phoenix.SessionController.new/2
  Parameters: %{"request_path" => "/"}
  Pipelines: [:browser]
[info] Sent 200 in 28ms
[info] POST /session
[debug] Processing with Pow.Phoenix.SessionController.create/2
  Parameters: %{"_csrf_token" => "dS11LUc0MCU3Q20CLg5EUF4HIChrHAQ52Y-L7gyNfp_0ckub8OhP21Oq", "request_path" => "/", "user" => %{"email" => "d@d.d", "password" => "[FILTERED]"}}
  Pipelines: [:browser]
[debug] QUERY OK source="users" db=5.2ms queue=1.1ms idle=1736.9ms
SELECT u0."id", u0."password_hash", u0."email", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."email" = $1) ["d@d.d"]
[info] Sent 302 in 489ms
```

Afterwards the server goes in a loop with a progress bar below the browser's address bar slowly filling up and this error periodically appearing in the console:

```plain
[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{}
  Pipelines: [:browser, :protected]
[info] Sent 200 in 21ms
[info] CONNECTED TO Phoenix.LiveView.Socket in 122µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "ERATWDcAcRMQWV4GHVVXUFYZGiEeeDIQVdK9GS8xAjl4P0fb0QRYGUyX", "vsn" => "2.0.0"}
[error] an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.start_link/1
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/channel.ex:12: Phoenix.LiveView.Channel.start_link({EdxmlWeb.Endpoint, {#PID<0.625.0>, #Reference<0.603304013.3363045379.52719>}})
        (elixir 1.10.3) lib/dynamic_supervisor.ex:692: DynamicSupervisor.start_child/3
        (elixir 1.10.3) lib/dynamic_supervisor.ex:678: DynamicSupervisor.handle_start_child/2
        (stdlib 3.13) gen_server.erl:706: :gen_server.try_handle_call/4
        (stdlib 3.13) gen_server.erl:735: :gen_server.handle_msg/6
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

What am I doing wrong?

**Comment by danschultzer** [comment]
Hmm, sounds like an issue with LiveView. Can you try upgrade to 0.13.0?

**Comment by scorsi** [comment]
Hello 👋 
It's a known bug, `Phoenix 1.5.3` is incompatible with `LiveView 1.12.0`.
[Check here](https://elixirforum.com/t/newly-created-app-hangs-on-home-page-with-error-in-phoenix-liveview-channel-start-link-1/31738).
As @danschultzer sugests, you have to upgrade LiveView to `1.13.0`.

**Comment by dimitarvp** [comment]
Since `phoenix_live_dashboard` requires `~> 0.12.0` I had to do this:

```elixir
      {:phoenix_live_view, "~> 0.13", override: true},
```

And the infinite loop is gone. Thanks guys.

**Comment by scorsi** [comment]
Does you use `phoenix_live_dashboard ~> 0.2.0` (the `phoenix_live_dashboard 0.2.4` support `phoenix_live_view 0.13.0` [Check out the `phoenix_live_dashboard mix.exs`](https://github.com/phoenixframework/phoenix_live_dashboard/blob/v0.2.4/mix.exs)) ? You should upgrade it if not the case and avoid using `override: true`.

**Comment by dimitarvp** [comment]
Tried to only use `~> 0.2` for the dashboard but it tried to fetch `0.2.3` which failed with the same problem (requiring liveview `~> 0.12.0`).

When I specifically wrote `~> 0.2.4` then it worked without the override. Thanks. 🙂
