### ISSUE TITLE
Sobelow review is throwing error  for ":erlang.binary_to_term" in PowRedisCache.

### ISSUE THREAD

**Issue by mohandass-pat** [danschultzer/pow#525]
Hi, Thanks for this wonderful library. We have finished the total Auth system with pow in our Product.

And we are doing so below security review for our Phoenix code base. While doing that pow is throwing error for ":erlang.binary_to_term" in PowRedisCache. How to go about this issue. Should I need to ignore this or are there any fixes for this?

Thanks in advance.
`##############################################
#                                            #
#          Running Sobelow - v0.10.2         #
#  Created by Griffin Byatt - @griffinbyatt  #
#     NCC Group - https://nccgroup.trust     #
#                                            #
##############################################

Config.HTTPS: HTTPS Not Enabled - High Confidence

-----------------------------------------------

Misc.BinToTerm: Unsafe `binary_to_term` - High Confidence
File: lib/auth/redis_cache.ex
Line: 157
Function: from_binary_redis_key:150
Variable: Elixir.Base

-----------------------------------------------

Misc.BinToTerm: Unsafe `binary_to_term` - High Confidence
File: lib/auth/redis_cache.ex
Line: 112
Function: populate_values:107
Variable: &1

-----------------------------------------------

Misc.BinToTerm: Unsafe `binary_to_term` - High Confidence
File: lib/auth/redis_cache.ex
Line: 54
Function: get:43
Variable: value

-----------------------------------------------

... SCAN COMPLETE ...`

**Comment by danschultzer** [comment]
Yeah, this is a limitation of sobelow, so you can safely ignore it.

If implemented incorrectly, `:binary_to_term` can be used in DoS attacks to bring down an erlang node as atoms are not garbage collected, and by default the max is 1M. In the Redis cache the terms are stored with  `term_to_binary/1` first, so the only attack vector would be if there was some way for the end-user to store binaries directly in the redis cache.

**Comment by mohandass-pat** [comment]
Thank you
