### ISSUE TITLE
Limit user login by devices

### ISSUE THREAD

**Issue by sezaru** [danschultzer/pow#526]
Hello there,

I have a system that can be used from multiple devices (mobile, web browser, and desktop). This means that the user can be logged in their cellphone, and at the same time, they can log in from a browser and/or desktop app.

I want to limit these multiple logins to a number of devices, for example, only 1 cellphone for mobile, max of 2 web browsers, and 1 desktop.

To do that, I'm guessing that the way to go is sending a metadata during the login API call with the device type, and at the backend level retrieve all current user sessions via [Pow.Store.CredentialsCache](https://github.com/danschultzer/pow/blob/master/lib/pow/store/credentials_cache.ex#L66).

What is not clear to me is if I can store some metadata in the CredentialsCache session (to know for what device type each login session is handling) and how can I get the older session and invalidate that, so the newer one takes place.

Example:
User is already connected via cellphone `A` and via web too, for some reason he tries to login now from cellphone `B`, in that case, I want to invalidate cellphone `A` session and create a new one for cellphone `B` and at the same time keep the web session alone.

Is this the best way to handle it? Does Pow have some better way or some code or documentation about it?

Thanks!

**Comment by danschultzer** [comment]
> What is not clear to me is if I can store some metadata in the CredentialsCache session (to know for what device type each login session is handling) and how can I get the older session and invalidate that, so the newer one takes place.

Yeah, you should store the device type in the metadata for the session. It's straight forward using `Pow.Plug.Session`: https://hexdocs.pm/pow/1.0.20/Pow.Plug.Session.html#module-custom-metadata

You mentioned an API call, so if you are not using the `Pow.Plug.Session` then you are probably directly interacting with `Pow.Store.CredentialsCache`, and you will just pass in the metadata along with the user using the `put/3` method.

You are correct that using [`Pow.Store.CredentialsCache.sessions/2`](https://hexdocs.pm/pow/1.0.20/Pow.Store.CredentialsCache.html#sessions/2) is the right approach. To give you an idea here's an example from the top of my head for how to fetch and delete sessions based on metadata attribute:

```elixir
defmodule MyAppWeb.AuthHelper do
  alias Pow.{Config, Store.CredentialsCache}

  @spec delete_sessions([binary()], Config.t()) :: :ok
  def delete_sessions(sessions, config) do
    store_config = store_config(config)

    Enum.each(sessions, &CredentialsCache.delete(&1, store_config))
  end

  @spec device_sessions_for_user(map(), Config.t()) :: [{binary(), binary()}]
  def device_sessions_for_user(user, config) do
    store_config = store_config(config)

    store_config
    |> CredentialsCache.sessions(user)
    |> Enum.map(&{&1, CredentialsCache.get(store_config, &1)})
    |> Enum.map(fn
      {_session_id, {_user, metadata}} ->
        {session_id, metadata[:device]}

      {session_id, :not_found} ->
        IO.warn("Session #{session_id} not found")
        nil
    end)
    |> Enum.reject(&is_nil/1)
  end

  defp store_config(config) do
    backend = Config.get(config, :cache_store_backend, Pow.Store.Backend.EtsCache)

    [backend: backend]
  end
end
```

During the auth flow you can call the above to invalidate all other sessions for this device:

```elixir
config = Pow.Plug.fetch_config(conn)
current_device = # ...

user
|> MyAppWeb.AuthHelper.device_sessions_for_user(config)
|> Enum.filter(fn {_session_id, device} -> device == current_device end)
|> Enum.each(fn {session_id, _device} -> delete_sessions(session_id) end)
```

The above wouldn't invalidate the new session (if you are using `Pow.Plug.Session`) as it's first created during the plug before_send callback, while the above would likely be called in a plug or controller action.

**Comment by sezaru** [comment]
Thanks! This worked like a charm.

I am indeed using an API, so I added your second code to my `APIAuthPlug` in the `create/3` function right before the new session creation.

The only thing that I noticed is that this only deletes the access_token, not the renewal one, I think this would be a problem since the app will, after some time, find out that it is not logged anymore and will then use the renewal token to re-login, making both the logins compete since both will keep using the renewal token to re-login when they detect an invalid access_token.

So I changed the code a little bit to fix that:

```elixir
defmodule ApiWeb.APIAuthPlug.Helper do
  alias Pow.{Config, Store.CredentialsCache}
  alias PowPersistentSession.Store.PersistentSessionCache

  @spec device_sessions_for_user(map, Config.t()) :: [{binary, binary}]
  def device_sessions_for_user(user, config) do
    store_config = store_config(config)

    store_config
    |> CredentialsCache.sessions(user)
    |> Enum.map(&{&1, CredentialsCache.get(store_config, &1)})
    |> Enum.map(fn
      {session_id, {_user, metadata}} ->
        {session_id, metadata[:renewal_token], metadata[:device]}

      {session_id, :not_found} ->
        IO.warn("Session #{session_id} not found")
        nil
    end)
    |> Enum.reject(&is_nil/1)
  end

  @spec delete_sessions([{binary, binary, atom}], Config.t()) :: :ok
  def delete_sessions(sessions, config) do
    store_config = store_config(config)

    Enum.each(sessions, fn {access_session_id, renewal_session_id, _} ->
      PersistentSessionCache.delete(store_config, renewal_session_id)
      CredentialsCache.delete(store_config, access_session_id)
    end)
  end

  defp store_config(config) do
    backend = Config.get(config, :cache_store_backend, Pow.Store.Backend.EtsCache)

    [backend: backend]
  end
end
```

```elixir
    user
    |> Helper.device_sessions_for_user(config)
    |> Enum.filter(fn {_, _, device} -> device == current_device end)
    |> Helper.delete_sessions(config)
```

Thanks again for the help!

**Comment by danschultzer** [comment]
Good call @sezaru, that's much better! I've updated the example accordingly.
