### ISSUE TITLE
Adding more tables to Mnesia

### ISSUE THREAD

**Issue by rootkc** [danschultzer/pow#527]
I have been trying to figure out the correct approach for extending the POW mnesia implementation.

I want to add some more tables to Mnesia for persisting state in a multi-page form. How would i achieve this in the best way while using Mnesia and POW for authentication?

I would prefer not having to handle netsplit etc. since it's already handled by POW.

**Comment by rootkc** [comment]
No because it is just multi page form data, potential data loss is fine for the sake of simplicity!

The Pow store logic is just key/value stor right? So it would be possible to put a map/changeset inside Mnesia?

In the above example should i put `MyAppWeb.FormStateCache` or  `MyAppWeb.StateManager`  in my supervision tree or would that be handled by your `Pow.Store.Backend.MnesiaCache`?

**Comment by danschultzer** [comment]
> So it would be possible to put a map/changeset inside Mnesia?

Yup.

> In the above example should i put `MyAppWeb.FormStateCache` or `MyAppWeb.StateManager` in my supervision tree or would that be handled by your `Pow.Store.Backend.MnesiaCache`?

Yeah, no need. Only the MnesiaCache has to be started.

**Comment by rootkc** [comment]
Awesome ill give it a go - would you like me

**Comment by danschultzer** [comment]
> would you like me to add something to the documentation about extending the store

Sure, not sure where the abstraction (MyAppWeb.StateManager) fits but if you find a good place please do. There's docs for the `Pow.Store.Base` here: https://hexdocs.pm/pow/Pow.Store.Base.html#content
