### ISSUE TITLE
Config applied inconsistently

### ISSUE THREAD

**Issue by heydtn** [danschultzer/pow#528]
I recently ran into [issue 445](https://github.com/danschultzer/pow/issues/445), which led me to implement the suggested fixes in [this response](https://github.com/danschultzer/pow/issues/445#issuecomment-597297499), but noticed that `get_by/1` in my custom Users context was never being called (it looks like the user in that thread also ran into this issue as well).

After doing a bunch of tracing, I found that `Operations.get_by/2` checks the passed in config for :users_context, and dispatches if possible. The config that ends up getting passed to `Operations.get_by` is `@pow_config` in `Pow.Ecto.Context`, which only contains the arguments passed to `use Pow.Ecto.Context` and doesn't get merged with the global config, so even though my global config contains:
```
config :my_app, :pow,
  user: MyApp.Users.User,
  users_context: MyApp.Users,
  repo: MyApp.Repo,
  web_module: MyAppWeb
```

The config passed to `Operations.get_by/2` only specifies `user` and `repo`.  Which means that `Operations.get_by/2` falls back to the default Context `get_by/1` handler.

Providing these arguments to `use` fixes the issue:
```
defmodule MyApp.Users do
  use Pow.Ecto.Context,
    repo: MyApp.Repo,
    user: MyApp.Users.User,
    users_context: __MODULE__
  ...
```

Should this macro be merging user provided values into the global config?

Hope this makes sense, please let me know if there's anything I can clarify!

**Comment by danschultzer** [comment]
Sorry for super late reply, missed this issue and time went by fast.

You are correct, this is a bug in Pow. I believe this was introduced with https://github.com/danschultzer/pow/pull/343. The macro should add the `:users_context` to the config automatically to ensure that it calls the custom context. I'll set up a PR, thanks for letting me know!

**Comment by danschultzer** [comment]
Fixed in master 😄
