### ISSUE TITLE
Change field validation message

### ISSUE THREAD

**Issue by tporto** [danschultzer/pow#531]
How to change the default validation message for email and password fields? I need to switch to pt-br.
I tried it this way:

`

def changeset(user, attrs) do
    user
    |> pow_changeset(attrs)
    |> cast(attrs, [:name])
    |> validate_required([:name, :email], message: "Campo Obrigatório.")
    |> validate_required([:password], message: "Informe sua senha.")
    |> validate_length(:password, min: 8, max: 100, message: "Senha deve conter no mímino 8 caracteres.")
    |> validate_format(:email, ~r/@/, message: "E-mail inválido.")
    |> validate_confirmation(:password, message: "Senhas não conferem.")
    |> unique_constraint(:email, message: "Já existe um registro com o mesmo e-mail.")
  end

`

**Comment by danschultzer** [comment]
Pow uses generic Ecto error messages, so you should translate them the same way you translate the default Ecto errors using gettext. With standard Phoenix installation you would find all the default error messages in `priv/gettext/errors.pot`.

Plataformatec wrote an article on it: http://blog.plataformatec.com.br/2016/03/using-gettext-to-internationalize-a-phoenix-application/
