### ISSUE TITLE
Pow emits redundant warnings for custom typed User schema fields

### ISSUE THREAD

**Issue by heydtn** [danschultzer/pow#533]
I was working on a similar use case to [issue 455](https://github.com/danschultzer/pow/issues/445), using Cloak to encrypt User schema fields.

I managed to get everything up and running as expected thanks to the behavior implemented in [Now emits warning instead of raising during compilation #455](https://github.com/danschultzer/pow/pull/455).

Unfortunately this is still causing some issues, though.  Usually, in the CI process, I enable `--warnings-as-errors` in order to help catch bugs, and reject builds which do not pass.

As Pow is emitting this warning even though I’ve provided a valid `:email` field (albeit with a Cloak Encrypted type which Pow is operating properly with), I’m unable to use `--warnings-as-errors` in CI as there’s no way to silence/disable the Pow attribute warning even though it’s not a concern.  Encrypting user data is very common case in web applications, so there may be some flexibility issues here if warnings/errors are thrown for field types other than `:string`.  In the meantime, I've removed `--warnings-as-errors`, though I would really like to add it back into my build process!

As a side note, related to this warning, there’s a few other issues I ran into with the api, usually regarding the assumption that the `:user_id_field` is `:string`, or has the same properties as one and supports both lookup and storage.  This isn’t true when you’re using an encrypted column paired with a hashed lookup column of the data.  Setting the `:user_id_field` to either the `:email` field or the `:email_hash` field both cause different issues with data rendering / user creation / user updating.  Also the unique constraint is automatically placed on the :user_id_field.  In this application, the `:user_id_field` is best set as the encrypted `:email` field, while the unique constraint is to be placed on the `:email_hash` field.

Hope this makes sense!  Let me know if there's anything I can clarify =)

**Comment by danschultzer** [comment]
> In the meantime, I've removed `--warnings-as-errors`, though I would really like to add it back into my build process!

Yeah, I see your point, it definitely needs to be possible to eliminate the warning for cases like this. Maybe field type check is unnecessary in these cases. Let me see what I can do to resolve it.

> This isn’t true when you’re using an encrypted column paired with a hashed lookup column of the data. Setting the `:user_id_field` to either the `:email` field or the `:email_hash` field both cause different issues with data rendering / user creation / user updating.

True, but I'm unsure what is the best way to make this work in a simple way. Ideally Pow only knows about the `:email` field with encrypt/decrypt being transparent.

> Also the unique constraint is automatically placed on the :user_id_field. In this application, the `:user_id_field` is best set as the encrypted `:email` field, while the unique constraint is to be placed on the `:email_hash` field.

The unique constraint is a DB constraint so in this case all that's necessary is to update the migration to set the constraint for the appropriate field. To make sure that Pow/Ecto catches the constraint it has to be named `users_email_index` though (assuming the table is called `users`).

**Comment by heydtn** [comment]
> True, but I'm unsure what is the best way to make this work in a simple way. Ideally Pow only knows about the :email field with encrypt/decrypt being transparent.

I don't have any ideas off the top of my head =(.  I can however provide some info on how I ended up setting this up, which may help others looking for a similar set up, though! https://gist.github.com/heydtn/7638c70b6248c184afce16beb2ec7191

> The unique constraint is a DB constraint so in this case all that's necessary is to update the migration to set the constraint for the appropriate field. To make sure that Pow/Ecto catches the constraint it has to be named users_email_index though (assuming the table is called users).

I hadn't thought of renaming the index!  I ended up providing just the email_hash unique index in the migration, and in the changeset adding on an ecto changeset unique constraint specifically for  `:email_hash`.  There's a redundant unique constraint on the :email field from the default changeset which is a minor efficiency hit, but because of how AES.GCM works, it wouldn't cause any issues.

**Comment by danschultzer** [comment]
I'm working on two ideas to resolve the warning:

1. Add an `:ignore_missing_fields` boolean option to the macro that will bypass the missing fields check
2. Ignore type check for custom types, and only keep in the check for base Ecto types match

I prefer the second option as I feel the developer always know what they are doing if they are setting a custom type for a field. In this case Pow should only check that the field exists.

**Comment by danschultzer** [comment]
I've resolved it in master @heydtn, please try it out and let me know if it works (`{:pow, github: "danschultzer/pow"}`). Also sorry for the long wait, the last few months have been brutal for me and I had little to no time to follow up on a lot on Pow stuff, hopefully getting back to regular schedule now.
