### ISSUE TITLE
Sig in validation does not show up 

### ISSUE THREAD

**Issue by caonUlisses** [danschultzer/pow#539]
### What did I do?
Started a new phoenix app and added pow as suggested on the docs.

### What went right?
If I try to register a new user and type 'asdf' into the e-mail field, when I hit submit, the correct errors appear on the screen.

### What went wrong?
On sing in, if I do the same, nothing happens. Neither if I put the wrong password or e-mail.
I inspected the DOM and it's not CSS related, there is no alert or anything besides the form itself.

**Comment by danschultzer** [comment]
An errof lash message will show if the credentials are invalid. Make sure that you got this in `layout/app.html.eex`:

```
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
```

**Comment by caonUlisses** [comment]
Yeah, how dum on my part! That was the exact case.
Guess I removed accidentaly when applying a theme. Thanks!
