### ISSUE TITLE
Redis cache PUT failures

### ISSUE THREAD

**Issue by dfalling** [danschultzer/pow#546]
Took me a bit to figure this out and I thought I'd share in case anyone else runs into it.  I'm using the PowRedisCache and my sessions started failing yesterday.  I could login successfully, but immediately any API calls would fail due to Redis cache misses.  Monitoring my Redis server just showed lots of SCAN and GET calls, but not a single SET.  I finally figured out that my Redis server's full, and returning the following error on PUTs: `"OOM command not allowed when used memory > 'maxmemory'."`.  PowRedisCache understandably ignores responses for efficiency, but this meant I had no way of knowing this was the cause of the problem.

I'm trying to decide how to fix this on my Redis server, but leaning towards switching from `maxmemory-policy volatile-lru` to `maxmemory-policy allkeys-lru` so all keys will be recycled not just ones with expiry's.

Hope this saves someone else some time!

**Comment by danschultzer** [comment]
Ugh, yeah that's no good. Thanks for letting me know! This error should definitely be raised in Elixir. One way could be to send off `Redix.pipeline(@redix_instance_name, commands)` in an async task and raise there if there's a non OK response.

**Comment by dfalling** [comment]
Yeah, switching to a regular pipeline is how I spotted it (though I just did it synchronously, not in a task).  Here's the error response if that helps:
```elixir
{:ok, [
  %Redix.Error{message: "OOM command not allowed when used memory > 'maxmemory'."},
  %Redix.Error{message: "OOM command not allowed when used memory > 'maxmemory'."}, 
  %Redix.Error{message: "OOM command not allowed when used memory > 'maxmemory'."}
  ]
}
```

**Comment by danschultzer** [comment]
Ok, got a PR in process here: https://github.com/danschultzer/pow/pull/549

Wdyt? In this PR I keep everything as it is and just making sure that an error is raised in an async process. An alternative could be a GenServer to match how the ETS and Mnesia cache works. But it could also be that we should just run the commands synchronously. Not really sure what's the better option here.

**Comment by danschultzer** [comment]
Yeah, that's much better. I've updated the guide. Decided to just use `command!` to raise the Redix errors. They are unexpected errors, so I think it makes sense to just raise if there are any problems with Redis.

**Comment by dfalling** [comment]
Perfect- catching those sooner is a big help.
