### ISSUE TITLE
Getting 'no match of right hand side value: {:error, :nofile}' error with MnesiaCach

### ISSUE THREAD

**Issue by mpwassler** [danschultzer/pow#551]
Hey, first of all thanks for this awesome library. Most of what I've tried to do so far has gone well but I ran into one issue I can't quite figure out.

Im trying to convert from ETS to Mnesia for the session store but I every time I do I receive a `no match of right hand side value: {:error, :nofile}` error from `lib/pow/store/base.ex:155`

This is my config.ex
```
config :myapp, :pow,
  user: MyApp.Users.User,
  repo: MyApp.Repo,
  web_module: MyAppWeb,
  web_mailer_module: MyAppWeb,
  mailer_backend: MyAppWeb.Pow.Mailer,
  extensions: [PowResetPassword, PowPersistentSession, PowInvitation],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  cache_store_backend: Pow.Store.Backend.MnesiaCach
```

and then in `application.ex`

```
def start(_type, _args) do
  topologies = Application.get_env(:libcluster, :topologies) || []

  children = [
    MyApp.Repo,
    MyAppWeb.Telemetry,
    {Phoenix.PubSub, name: MyApp.PubSub},
    {Cluster.Supervisor, [topologies, [name: MyApp.ClusterSupervisor]]},
    {Pow.Store.Backend.MnesiaCache, extra_db_nodes: Node.list()},
    Pow.Store.Backend.MnesiaCache.Unsplit,
    MyAppWeb.Endpoint,
    MyApp.Scheduler
  ]

  opts = [strategy: :one_for_one, name: MyApp.Supervisor]
  Supervisor.start_link(children, opts)
end
```

I also have this pow related code in my `endpoint.ex`

```
@session_options [
    store: :cookie,
    key: "a_key",
    signing_salt: "a_salt"
  ]

  plug Plug.Session, @session_options
  plug Pow.Plug.Session, otp_app: :myapp
  plug PowPersistentSession.Plug.Cookie
```

Im using libcluster but I still get the error even if I remove it. I feel like i'm probably missing something really obvious here.  Like maybe I need to specify `cache_store_backend` somewhere else. But I've tried adding it anywhere I can find.

I'll admit i'm not extremely knowledgeable about mnesia but it seems like its writing files successfully at least.

**Comment by mpwassler** [comment]
Ok. Wow. Not my day today. In typing this up I realized I spelled ` cache_store_backend: Pow.Store.Backend.MnesiaCach` wrong. And it should be ` cache_store_backend: Pow.Store.Backend.MnesiaCache`.

**Comment by danschultzer** [comment]
I'm glad you figured it out, don't hesitate to write again if something else doesn't work as expected!
