### ISSUE TITLE
Question: Is it possible to override the mail templates for Pow extensions?

### ISSUE THREAD

**Issue by mtyeh411** [danschultzer/pow#558]
As the title implies, I'm trying to override the email templates (specifically, the EmailConfirmation & Invitation extensions).  Is this possible?  am i reading the code correctly and seeing that they are based on the module names?

**Comment by Schultzer** [comment]
Yes, https://github.com/danschultzer/pow#modify-templates

**Comment by mtyeh411** [comment]
oh thank you ... i apparently didn't do a good enough job RTFM
