### ISSUE TITLE
Help in understanding custom contexts/purpose of `get_by/1`

### ISSUE THREAD

**Issue by jesselathamdev** [danschultzer/pow#559]
Hi Dan and folks.  I'm wondering if you could help shed some light on when `get_by/1` is called with use for with custom Contexts (such as with `users_context` in config).

My thinking is that with this being added into my custom context, it would be called anytime Pow performs the DB lookup on the user, such as the initial Session creation?  The only thing is I haven't seen get_by called at all when I throw something simple like IO.inspect into it.  It's making me think that I'm misusing it or it's tied to some other flow?

Why am I looking into get_by?  When a session is created, I don't want the entire User record to be loaded into current user.  I just don't need all of it - consider any bloby fields that may be needed for other use uses.  I could certainly separate profile-like fields out of the user but wanted to experiment with Pow as it is.  Another case would be that I'd like to perform database checking when creating a new session for fields like Active and Deleted At rather than handling those at the app level with code.

Interesting thing is that I've been able to work with a custom context and provide an `authenticate/1` method and perform the checking there, but it doesn't feel right when I just want to treat inactives and soft deleted records as if they were not available.

Any chance you or others here could shed some light on when get_by/1 is actually called and how can I tap into it?

My code as it currently works correctly with `authenticate/1`, but not with `get_by/1`

```elixir
defmodule App.Repo.Authentication do
  use Pow.Ecto.Context,
    repo: App.Repo,
    user: App.Repo.Schemas.User

  def authenticate(params) do
    user = pow_authenticate(params)

    # Test to filter out active/deleted_at cases, treat as records to do exist for obfuscation purposes 
    # with simple "does not exist"
    # This would be better served if we could provide a custom `get_by/1` and have this happen at the 
    # database level during session creation (and then use a plug for each request thereafter).
    if user != nil && user.active && user.deleted_at == nil do
      user
    end
  end

  # Not sure how/where `get_by/1` is used yet.
  def get_by(clauses) do
    IO.puts("====================================")
    IO.puts("inside get_by(clauses), can't see it it firing in the logs")
    IO.puts("====================================")

    clauses
    |> pow_get_by()
  end
end
```

**Comment by danschultzer** [comment]
Great catch! This is subtle, but I imagine it's because you need to set `users_context: __MODULE__` in the config, so it looks like this:

```elixir
defmodule App.Repo.Authentication do
  use Pow.Ecto.Context,
    repo: App.Repo,
    user: App.Repo.Schemas.User,
    users_context: __MODULE__

  def authenticate(params) do
    user = pow_authenticate(params)

    # Test to filter out active/deleted_at cases, treat as records to do exist for obfuscation purposes 
    # with simple "does not exist"
    # This would be better served if we could provide a custom `get_by/1` and have this happen at the 
    # database level during session creation (and then use a plug for each request thereafter).
    if user != nil && user.active && user.deleted_at == nil do
      user
    end
  end

  # Not sure how/where `get_by/1` is used yet.
  def get_by(clauses) do
    IO.puts("====================================")
    IO.puts("inside get_by(clauses), can't see it it firing in the logs")
    IO.puts("====================================")

    clauses
    |> pow_get_by()
  end
end
```

This is something the `Pow.Ecto.Context` macro should do though. I'll open a PR to fix this.

**Comment by danschultzer** [comment]
This was resolved in https://github.com/danschultzer/pow/pull/537

I'll push a release asap! In the meanwhile, let me know if it works using the master branch.

**Comment by danschultzer** [comment]
`v1.0.21` released, should be working now!

**Comment by jesselathamdev** [comment]
Thanks @danschultzer! I had a look around and came across the ticket but was sticking to the pegged versions (hadn't given master a try yet).  Will give it a try out and let you know!

**Comment by jesselathamdev** [comment]
Nice - thanks @danschultzer I was able to provide my own query here which allowed me to push down the extra filters needed to the DB level instead of handling them at the app level.

All good to close out :)
