### ISSUE TITLE
Improve email validation

### ISSUE THREAD

**Issue by Schultzer** [danschultzer/pow#560]
https://elixirforum.com/t/ecto-commons-ecto-common-helper-functions-such-as-changeset-validators/34228/15?u=schultzer
> Seems that this is still not fully valid, as this do not allow [::1] as a domain part. Additionally it will allow .foo. as a domain, which is incorrect.

It seams like the current email validation is not correct when it comes to the domain part.

I think a better way to solve this is with a proper parser instead of regex.

**Comment by danschultzer** [comment]
I've used https://en.wikipedia.org/wiki/Email_address#Syntax to set up the rules, but it should conform to [RFC 3696](https://tools.ietf.org/html/rfc3696) validation. The domain validation is not up to par.

**Comment by Schultzer** [comment]
There is an improved version in https://github.com/achedeuzot/ecto_commons/commit/75ca493739a54b2f73b753c3d2623dc61781d91d
