### ISSUE TITLE
Example redis module searches ALL user sessions

### ISSUE THREAD

**Issue by axelson** [danschultzer/pow#561]
All endpoints that deal with sessions such as sign-in, profile update are taking 20 seconds in production because the `do_scan` function from https://hexdocs.pm/pow/redis_cache_store_backend.html is being executing 1000+ times per request (because it is iterating over every persistent_session entry in redis).

Is there documentation about what the `all/2` callback is supposed to return? I'd like to try to re-write the `all/2` call to be more performant.

**Comment by danschultzer** [comment]
Ugh, this is bad, good catch and thanks a lot for putting effort into resolving this.

> Is there documentation about what the `all/2` callback is supposed to return?

Yeah, no docs 😞 I need to update the docs.

In short this method takes in a `key_match` as the second argument, and will fetch all keys that matches it. It is used to fetch all keys within a namespace. In [`Pow.Store.CredentialsCache`](https://github.com/danschultzer/pow/blob/v1.0.20/lib/pow/store/credentials_cache.ex) you'll see that it's used to fetch all users using `[struct, :user, :_]` match spec and all sessions with `[struct, :user, id, :session, :_]` match spec. The latter is used when a new session is inserted in the credentials cache. Any sessions that has identical fingerprint will be deleted. So this is why you get the 20s slowdown.

MATCH is used for the SCAN in the [`RedisCache`](https://hexdocs.pm/pow/1.0.20/redis_cache_store_backend.html#content) to limit the number of keys to iterate through. But reading the [redis docs](https://redis.io/commands/scan) I realize it doesn't make the scan any more efficient, it's O(n) with n being all keys in the db(!!):

> It is important to note that the MATCH filter is applied after elements are retrieved from the collection, just before returning data to the client. 

It's probably better to use sets?
