### ISSUE TITLE
ttl is not changed.

### ISSUE THREAD

**Issue by alexsysm** [danschultzer/pow#566]
I set configs into endpoint.ex and router.ex
```
  pipeline :api do
    plug :accepts, ["json"]
    plug AbsWeb.Plugs.Authorization, otp_app: :app_abs,
      session_ttl_renewal: 60_000,
      credentials_cache_store: {Pow.Store.CredentialsCache, ttl: 60_000}
  end
```

```
  plug Pow.Plug.Session, otp_app: : app_abs,
    session_ttl_renewal: 60_000,
    credentials_cache_store: {Pow.Store.CredentialsCache, ttl: 60_000}

```

two plugs are called because of router and endpoint.
so I did set up both.

below is the logs in Pow.Plug.Session

```
[warn] [mod: Pow.Plug.Session, plug: Pow.Plug.Session, otp_app: : app_abs, session_ttl_renewal: 60000, credentials_cache_store: {Pow.Store.CredentialsCache, [ttl: 60000]}]
[warn] fetch start!!!
[warn] [backend: Pow.Store.Backend.EtsCache, ttl: 60000]
```

and Pow.Store.CredentialsCache

```
[error] ========= [backend: Pow.Store.Backend.EtsCache]
[error] ========= [renewal_token: "d872824a-e620-4a5b-96af-79529284c6b0"]
[error] ========= [ttl: 1800000, namespace: "credentials"]
```

point is...
no matter what i set ttl, store fetch 30mins somewhere in configs.

do i have to create custom controllers or something?

it's working only If i set ttl in the Pow.Store.CredentialsCache just like below
```
  use Base,
    ttl: :timer.minutes(1),
    namespace: "credentials"
```

**Comment by Schultzer** [comment]
It seams like something gets overridden, I would just try to remove all the configs, and then place them in `config.exs`.

**Comment by alexsysm** [comment]
in credential_cache.ex
```
def create(conn, user, config) do
    store_config  = store_config(config)
    access_token  = Pow.UUID.generate()
    renewal_token = Pow.UUID.generate()
    conn          =
      conn
      |> Conn.put_private(:api_access_token, sign_token(conn, access_token, config))
      |> Conn.put_private(:api_renewal_token, sign_token(conn, renewal_token, config))

    t**tl = Keyword.fetch!(Application.fetch_env!(:hippo_abs, :pow), :ttl)
    store_config = store_config |> Keyword.put_new(:ttl, ttl)**

    CredentialsCache.put(store_config, access_token, {user, [renewal_token: renewal_token]})
    PersistentSessionCache.put(store_config, renewal_token, {[id: user.id], [access_token: access_token]})

    {conn, user}
  end
```

what i did is insert 2 line above with bold.
put ttl value into store_config. cause CredentialsCache.put uses default ttl value inside itself.

I am not sure this is the proper solution.
it's just work-arround, i guess.

**Comment by danschultzer** [comment]
`:ttl` gets overridden by the config: https://github.com/danschultzer/pow/blob/v1.0.21/lib/pow/store/base.ex#L56-L62

So it's because the `:ttl` doesn't get set, or is overridden elsewhere.

I believe the issue is the `AbsWeb.Plugs.Authorization` module. Is this taken from [the API guide](https://github.com/danschultzer/pow/blob/v1.0.21/guides/api.md)? The `:credentials_cache_store` and `:session_ttl_renewal` is only used for `Pow.Plug.Session`. The API guide directly interacts with the CredentialsCache so you need to manually pass in the value when setting it:

```elixir
    CredentialsCache.put(Keyword.put(store_config, :ttl, 60_000), access_token, {user, [renewal_token: renewal_token]})
```

Maybe the API guide should be rewritten to use the same `credentials_cache_store` setting to avoid this confusion?

**Comment by alexsysm** [comment]
@danschultzer 
Thanks for your comments.

for newbies just like me, It would be nice to put more comments or documents in case of API mode.
for example,

```
you have to set :ttl in the config while API mode or you should set up ttl manually when you create new token.
just like below

CredentialsCache.put(Keyword.put(store_config, :ttl, 60_000), access_token, {user, [renewal_token: renewal_token]})
```

couple of guys had the same experience on this case when I googled.


and again .. Thank you.

**Comment by danschultzer** [comment]
Yeah that makes sense. I've opened #569 that adds a small comment to the authorization plug module.

**Comment by alexsysm** [comment]
@danschultzer 😃
