### ISSUE TITLE
update user failed with error current_password  can't  be  blank

### ISSUE THREAD

**Issue by ray-sh** [danschultzer/pow#570]
I am trying  to update an user's field but failed with  the following error.
{"error":{"errors":{"current_password":["can't be blank"]},"message":"Couldn't create user","status":500}}

Could I skip this check?
In my case, I am using an admin user to  change  the normal user's  fields. 
The  first  step is query user from db then call this  from user context
def update(user, params) do
    user
    |> User.changeset(params)
    |> Cdc.Repo.update()
  end

The admin user don't  know normal user's password in this  case. 

Any workaround  about  this?

Thanks

**Comment by Schultzer** [comment]
You can just make a different changeset function.

```elixir
def admin_changeset(user, params) do
Do your thing! 
end
```
