### ISSUE TITLE
mix pow.extension.ecto.gen.migrations silently fails

### ISSUE THREAD

**Issue by axelclark** [danschultzer/pow#58]
When I run `mix pow.extension.ecto.gen.migrations --extension PowResetPassword` or just `mix pow.extension.ecto.gen.migrations` with the following in `config/config.exs`, my project compiles, but then the Ecto migrations aren't generated. 

```elixir
# config/config.exs
...
config :golf, :pow,
  user: Golf.Accounts.User,
  repo: Golf.Repo,
  extensions: [PowResetPassword, PowPersistentSession]
```

Here is my branch:  https://github.com/axelclark/golf/tree/pow

I'm using 
```elixir
{:ecto_sql, "~> 3.0"},
{:pow, "~> 1.0.0"}
```

**Comment by danschultzer** [comment]
There's no migrations for reset password and persistent session, only email confirmation so you're fine. It would probably be good to have the mix task output a notice when there's no migration for an extension to prevent confusion.

**Comment by axelclark** [comment]
Got it, thanks!
