### ISSUE TITLE
How to  extend  token automatically?

### ISSUE THREAD

**Issue by ray-sh** [danschultzer/pow#582]
Hi,
My frontend will get 401 after 30 mins. I am keeping  operate the  UI within 30 mins and I expected the  token will be extended automatically when there is  API call. 

Anything am I missing in the config?

Thanks

**Comment by danschultzer** [comment]
Sessions have a timeout of 30 minutes to prevent session fixation. You have to enable renewal. Do you use a plug like in [the API guide](https://hexdocs.pm/pow/1.0.21/api.html) or the [`Pow.Plug.Session`](https://hexdocs.pm/pow/1.0.21/Pow.Plug.Session.html)? If the latter then you should enable [`PowPersistentSession`](https://hexdocs.pm/pow/1.0.21/pow_persistent_session.html).

**Comment by ray-sh** [comment]
I  am using the  plug  fellow the  API guide. How to enable renewal in this situation? 
Should the front-end  call renew(conn, _params) in session controller? If this way,  I may need  handle 401  in  all rest  call in the  GUI code.
Is there  any way to make paw to extend the ttl of the token when there  are  api call? That means if user keep operate the GUI, the  token will never expire.

**Comment by danschultzer** [comment]
Yeah, the front end should handle renewal. When a request no longer works, your logic need to generate a new access token with the returned `renewal_token`, and retry the request with that access token (or otherwise fail). If the API call happens within the client browser, then you could just rely on the session cookies with `Pow.Plug.Session` and `PowPersistentSession.Plug.Cookie` instead. Extending TTL of a token indefinitely would be a great security risk.

**Comment by ray-sh** [comment]
Thanks, 
Is there any way to config the  ttl? I may need to reduce the  ttl, I tried this but  seems not  work.
config :app, :pow,
  ttl: time_out

**Comment by danschultzer** [comment]
Yeah, you just need to update the `:ttl` in the store config, e.g:

```elixir
CredentialsCache.delete(Keyword.put(store_config, :ttl, :timer.minutes(15)), metadata[:access_token])
```

The API authorization plug doesn't automatically carry over the config. If you are using the Pow.Plug.Session, then you just need to do this: https://hexdocs.pm/pow/1.0.21/Pow.Plug.Session.html#module-session-expiration

**Comment by ray-sh** [comment]
Thanks for the help, that worked.
