### ISSUE TITLE
Can't start Mnesia with Pow in production via releases

### ISSUE THREAD

**Issue by vadimshvetsov** [danschultzer/pow#586]
Hey, thanks again for awesome work and great library.

I've got stucked with configuring Mnesia for using in production with releases.

I assume that I misconfigured some options and would appreciate if somebody will point me out where exactly.

I have Umbrella Phoenix app with Pow which I would like to deploy via releases.

My main :pow config is:
```ex
config :myapp_web, :pow,
  repo: MyApp.Repo,
  user: MyApp.Identity.User,
  users_context: MyApp.Identity,
  mailer_backend: MyAppWeb.Mailer,
  web_mailer_module: MyAppWeb,
  cache_store_backend: Pow.Store.Backend.MnesiaCache,
  extensions: [PowResetPassword, PowEmailConfirmation],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks
```

And here is MyAppWeb application:
```ex
defmodule MyAppWeb.Application do
  use Application

  def start(_type, _args) do
    # Ensure that the elixir nodes are connected for running distributed mnesia
    connect_nodes()

    # List all child processes to be supervised
    children = [
      MyAppWeb.Endpoint,
      {Phoenix.PubSub, name: MyAppWeb.PubSub},
      # Starts a worker by calling: MyAppWeb.Worker.start_link(arg)
      # {MyAppWeb.Worker, arg},
      {Absinthe.Subscription, MyAppWeb.Endpoint},
      # Run distributed MnesiaCache
      {Pow.Store.Backend.MnesiaCache, extra_db_nodes: Node.list()},
      # Recover MnesiaCache for all nodes from oldest node after network splits
      # Use Unsplit after adding nodes
      Pow.Store.Backend.MnesiaCache.Unsplit
    ]

    opts = [strategy: :one_for_one, name: MyAppWeb.Supervisor]
    Supervisor.start_link(children, opts)
  end

  def config_change(changed, _new, removed) do
    MyAppWeb.Endpoint.config_change(changed, removed)
    :ok
  end

  defp connect_nodes() do
    Enum.each(nodes(), fn node ->
      Node.connect(node)
    end)
  end

  defp nodes() do
    {:ok, hostname} = :inet.gethostname()
    # Name nodes as "a" and "b"
    for sname <- ["a", "b"], do: :"#{sname}@#{hostname}"
  end
end
```

Release config in umbrella root `mix.exs`:
```ex
      releases: [
        myapp: [
          applications: [
            myapp: :permanent,
            myapp_web: :permanent
          ],
          version: {:from_app, :myapp_web}
        ]
      ]
```

When I do `MIX_ENV=prod mix release myapp` everything is fine but when I start server with `_build/prod/rel/myapp/bin/myapp start` I've got:
```
10:42:37.250 [info] Running MyAppWeb.Endpoint with cowboy 2.8.0 at :::4001 (http)
10:42:37.251 [info] Access MyAppWeb.Endpoint at http://api.myapp.com
10:42:37.258 [info] Application myapp_web exited: MyAppWeb.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pow.Store.Backend.MnesiaCache
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:aborted, {:badarg, :schema, :unknown}}
            (pow 1.0.21) lib/pow/store/backend/mnesia_cache.ex:352: Pow.Store.Backend.MnesiaCache.change_table_copy_type/1
            (pow 1.0.21) lib/pow/store/backend/mnesia_cache.ex:300: Pow.Store.Backend.MnesiaCache.init_cluster/1
            (pow 1.0.21) lib/pow/store/backend/mnesia_cache.ex:136: Pow.Store.Backend.MnesiaCache.init/1
            (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

I suppose that problem is with nodes/distributed system, because when I remove this lines in application code it doesn't fail:
```ex
      # connect_nodes()
      # {Pow.Store.Backend.MnesiaCache, extra_db_nodes: Node.list()},
      # Pow.Store.Backend.MnesiaCache.Unsplit
```

But when I do login it's not working and in logs I see this error:
```
11:00:59.514 [error] #PID<0.4840.0> running MyAppWeb.Endpoint (connection #PID<0.4834.0>, stream id 6) terminated
Server: localhost:4001 (http)
Request: POST /api
** (exit) {:aborted, {:no_exists, [Pow.Store.Backend.MnesiaCache, ["credentials", "fd6d8249-4f45-4e7c-acaf-c333d3086941"]]}}
```

What I'm doing wrong?

**Comment by danschultzer** [comment]
It looks correct. Does this work in local? As wonderful as Mnesia is, it's a pain to debug, so we'll just have to figure it out by elimination. My first though would be to wipe any existing Mnesia data files on your server in case it was set up incorrectly.

**Comment by vadimshvetsov** [comment]
Thanks a lot. It looks strange, but right now it works in container but not in local env. Sorry for open issue with that, of course it's not a Pow issue.

**Comment by Schultzer** [comment]
> but not in local env
As Dan mentioned try to delete the Mnesia data, there should be a mnesia directory in your application root.

**Comment by cheerfulstoic** [comment]
I'm currently struggling with this, did you eventually figure out the issue?

I'm using Google Cloud Platform and I have a volume mapped to `/mnesia`.  It was working before, but when I started using Elixir releases it broke with the same error as you.

```
# mix.exs
  def application do
    [
      mod: {MyApp.Application, []},
      extra_applications: [:mnesia, :logger, :runtime_tools]
    ]
  end

# config/config.exs
config :mnesia, dir: '/mnesia'

# Setup the endpoint in `prod.secret.exs` for my release
config :fb_scrape_db, MyAppWeb.Endpoint, server: true

# Added to my children in `application.ex`
Pow.Store.Backend.MnesiaCache,

# In my `APIAuthPlug` copied from the documentation
  defp store_config(config) do
    # backend = Config.get(config, :cache_store_backend, Pow.Store.Backend.EtsCache)
    backend = Config.get(config, :cache_store_backend, Pow.Store.Backend.MnesiaCache)

    [backend: backend]
  end
```

Built with the docker image: `elixir:1.11.3-alpine`

**Comment by danschultzer** [comment]
@cheerfulstoic finally got around to test it, works well with a `elixir:1.11.3-alpine` docker release. You might have had a build that unexpectedly quit which caused the mnesia data to be malformed. You should remove everything inside `/mnesia` and start it up again. Let me know if clearing the directory works.

**Comment by cheerfulstoic** [comment]
I actually don't know how to clear the directory on GCP 🙈 

But I don't think it's malformed because I rolled back to my old docker image which wasn't using Elixir releases and the sessions started working again (no need to login again)

**Comment by danschultzer** [comment]
> But I don't think it's malformed because I rolled back to my old docker image which wasn't using Elixir releases and the sessions started working again (no need to login again)

I believe this is it. Does the new docker image have a new OTP version? Might have internal changes to mnesia. Could also just be simple permissions change with the OS. In any case, it's definitely working with a cleared volume for me (I tested with a failed start up sequence just to be sure I could trigger the `:no_exists` error)

**Comment by cheerfulstoic** [comment]
Hrmm, good point... It looks like I went from using the image `elixir:1.10.3` to the image `elixir:1.11.3-alpine`.  Best as I can tell those use OTP 22 and 23 respectively.  I think I'll give it a try again a bit later without changing the elixir version number and see if that works (if for no other reason than to debug the issue)

**Comment by danschultzer** [comment]
You can try switch the volume or the mnesia directory (`config :mnesia, :dir, '/new/path/to/dir') for the new release to ensure it initiates from blank state. Be aware that this means all users currently logged in will have to log in again. This should resolve the issue though. Not sure if there's any way to migrate if it's because of OTP changes.
