### ISSUE TITLE
Error on trying to add pow to a existing app

### ISSUE THREAD

**Issue by Mdsp9070** [danschultzer/pow#588]
I'm adding `pow` to a existing phoenix app, add added some extensions (reset password and email confirmation!), added some configurations, generated all migrations and templates. However, when I try to access any route, I get this error:

```
ArgumentError at GET /
cannot fetch session without a configured session plug
```

I made a gist where I put all my modifications:
https://gist.github.com/Mdsp9070/6aeb8b4cdbdde83e4db5dd54160367f3

screenshot:
![2020-12-28-16-24-42](https://user-images.githubusercontent.com/44469426/103238378-47adee80-4929-11eb-816b-f675da6385cd.png)

Could anyone help me?

**Comment by Mdsp9070** [comment]
The error was the order of plug...

this is the correct order:

```elixir
  plug Plug.Session, @session_options

  # Pow
  plug Pow.Plug.Session, otp_app: :app

  plug AppWeb.Router
```

**Comment by danschultzer** [comment]
Thanks for posting what was the issue!
