### ISSUE TITLE
Invitations and required validation when user_id_field is not email?

### ISSUE THREAD

**Issue by jakeva** [danschultzer/pow#594]
I want the `user_id_field` to be `username`, but it seems like because the id field is required on the changeset the user created at the time of an invitation needs to have the username set by the inviter. Ideally for my application the username would be chosen by the invitee at the time they accept the invitation. I'm wondering if there's an easy way to address this, otherwise I'd be happy to dig into the source more and discuss more. I have a few thoughts, but I want to make sure I haven't missed something first. 

Thanks!

**Comment by danschultzer** [comment]
The user is created when invited, so you'll have to make sure that username field can be nil. I believe you just have to set up a custom `invite_changeset/2` method in your user schema module:

```elixir
def invite_changeset(user_or_changeset, invited_by, attrs) do
    user_or_changeset
    |> cast(attrs, [:email])
    |> validate_required([:email])
    |> put_change(:invitation_token, Pow.UUID.generate())
    |> unique_constraint(:invitation_token)
    |> put_assoc(:invited_by, invited_by)
    |> assoc_constraint(:invited_by)
  end
```

The above is untested, so please let me know if this works.

**Comment by jakeva** [comment]
Yes, that works! Thanks for the brilliant framework by the way, I'll submit a PR with this added to the docs :)
