### ISSUE TITLE
Handle changeset error on register new user.

### ISSUE THREAD

**Issue by alvnrapada** [danschultzer/pow#595]
Got this changeset with a unique constraint. I am expecting a changeset error (registering existing user email) once you submit the form and renders the error on the html but it is not catching it. pow automatically triggers the `after_sign_in_path` on pow routes. how do you properly setup changeset on pow, am i missing something? or is there a better way to handle this (existing email registration) on pow? Thanks!!

```elixir
  def changeset(user, attrs) do
    user
    |> ....
    |> unique_constraint(:email, name: :users_email_index)
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
  end
```

Update: 

I tried creating a new phoenix app and integrate pow into it. But It works perfectly fine, when registering an existing user:

![Screen Shot 2021-01-30 at 9 07 50 PM](https://user-images.githubusercontent.com/62341430/106357143-3d737b80-633f-11eb-9bfa-d7fa794ee0d8.png)

**Comment by danschultzer** [comment]
> I am expecting a changeset error (registering existing user email) once you submit the form and renders the error on the html but it is not catching it.

It's the default behavior in Pow. You won't have to add `|> unique_constraint(:email, name: :users_email_index)` as the `pow_changeset/2` has `unique_constraint` check on the user id field (which by default is email).

**Comment by alvnrapada** [comment]
> > I am expecting a changeset error (registering existing user email) once you submit the form and renders the error on the html but it is not catching it.
> 
> It's the default behavior in Pow. You won't have to add `|> unique_constraint(:email, name: :users_email_index)` as the `pow_changeset/2` has `unique_constraint` check on the user id field (which by default is email).

Yeah, Thats my problem, It should be a default behavior but It doesnt work on the other project that Im working with. 

even with the error, it still triggers the pow routes' after_sign_in_path that causes an error because current user is nil.

**Comment by danschultzer** [comment]
You should check if you got a unique constrain on the email column in the db. Sounds like there is none, and you need to add it to migrations.

**Comment by alvnrapada** [comment]
> You should check if you got a unique constrain on the email column in the db. Sounds like there is none, and you need to add it to migrations.

Already checked,  and it has a unique constraint on the migration.

**Comment by danschultzer** [comment]
That's weird, because being redirected means that the insert was succesful. Can you check the DB to see if there are duplicate users?

**Comment by alvnrapada** [comment]
> That's weird, because being redirected means that the insert was succesful. Can you check the DB to see if there are duplicate users?

The user is not being created, that's the reason why after_sign_in_path is getting an error because it got some logic that is getting the current_user details, but current_user is nil.

**Comment by danschultzer** [comment]
Sorry for getting back to this so late, had too many things coming up the last two weeks. It might no longer be relevant for you, but do you have `PowEmailConfirmation` enabled?

If you do, I'm pretty sure that this is because of the user enumeration protection as described here: https://hexdocs.pm/pow/1.0.22/pow_email_confirmation.html#content

If you add `pow_prevent_user_enumeration: true` to `conn.private` (e.g. calling `Plug.Conn.put_private(conn, :pow_prevent_user_enumeration, false)`) before the controller is called then it should bypass the security step.

**Comment by alvnrapada** [comment]
Sorry for the late reply, but we're able to fix this through the `after_registration_path`. Thanks !
