### ISSUE TITLE
Pow extensions in API mode

### ISSUE THREAD

**Issue by christophweegen** [danschultzer/pow#599]
Hello, 

is it possible to use pow [extensions](https://github.com/danschultzer/pow#extensions) in API mode?

My first attempts to implement them (email confirmation and password reset) in an API (umbrella) app weren't successful so I'm wondering if it's already possible at all, since docs only talk about a browser pipeline and failure messages were revolving around flash messages.

In case it should already work, I can provide more detailed error messages.

Thanks a lot!

**Comment by danschultzer** [comment]
You can use parts of them, but you'll have to set it up manually just like general API auth. I've planned a full guide at some point: https://github.com/pow-auth/pow_site/issues/14

There are two examples by @mreishus in the linked issue that shows how it's achieved.

**Comment by christophweegen** [comment]
Oh great, I will go through them.

Thanks a lot to you @danschultzer and @mreishus.

**Comment by christophweegen** [comment]
By the way is it planned to have guides for this in the near future?

For me having pow extensions work in an API app would be really useful, @danschultzer and @mreishus maybe we can coordinate efforts on this, so can I somehow help out?

Greetings
