### ISSUE TITLE
Switch to :crypto.mac/4 from :crypto.hmac/3

### ISSUE THREAD

**Issue by rmayhue** [danschultzer/pow#601]
While testing one of my apps with Erlang OTP master, pow fails with `(UndefinedFunctionError) function :crypto.hmac/3 is undefined or private`.

I'm guessing that `:crypto.hmac/3` is being removed in OTP 24 which is the reason for the error. Do you have plans to switch out `:crypto.hmac/3` with `:crypto.mac/4`?

It would be a fairly simple change:

https://github.com/danschultzer/pow/blob/84d6cfe44a6e2f69ef60e3374a72ada6645f83b4/lib/pow/ecto/schema/password/pbkdf2.ex#L70

```elixir
&:crypto.mac(:hmac, digest, secret, &1) 
```

All tests should pass as the output is exactly the same. The caveat is that OTP 22.1 would be required after the change.

**Comment by danschultzer** [comment]
Thanks! The module has been updated to support OTP 24, if you pull from master it should be working, I'll prepare a new release soon 😄
