### ISSUE TITLE
Reset Password Changeset Error (current password needed?)

### ISSUE THREAD

**Issue by alexsysm** [danschultzer/pow#614]
{:error, #Ecto.Changeset<action: :update, changes: %{password: "34343434", password_confirmation: "34343434"}, errors: [current_password: {"can't be blank", [validation: :required]}], data: #Database.Account.User<>, valid?: false>}

# controller
```
conn
      |> Pow.Plug.put_config(otp_app: :public_api)
      |> PowResetPassword.Plug.load_user_by_token(token)
      |> case do
        {:ok, conn} ->
          {:ok, user, _conn} = PowResetPassword.Plug.update_user_password(conn, pasword)
          %{user: user}
        {:error, _conn} -> %{error: %{message: "Expired Token"}}
      end
```

# schema
```
  def reset_password_changeset(user_struct, attrs) do
    user_struct
    |> pow_changeset(attrs)
    |> cast(attrs, [:password, :password_confirmation])
    |> validate_required([:password, :password_confirmation])
    |> validate_confirmation(:password_confirmation)
  end
```

# rest api
```
PUT: {{url}}/reset-password/{{token}}
{
    "user": {
        "password": "34343434",
        "password_confirmation": "34343434"
    }
}

```

# error message
```
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{password: "34343434", password_confirmation: "34343434"}, errors: [current_password: {"can't be blank", [validation: :required]}], data: #Database.Account.User<>, valid?: false>, 
```

I am trying to reset password by using pow.
Do I have to put a current password into params in order to reset password?
I thought that i would reset password when I forgot my password so i couldn't put current password in it.

maybe i am down the rabbit hole. ^^;;

**Comment by alexsysm** [comment]
resolved?

change pow_changeset  in schema to pow_password_changeset.
is it ok?

**Comment by danschultzer** [comment]
Yup, that's correct. You should just use `pow_password_changeset`: https://github.com/danschultzer/pow/blob/v1.0.23/lib/extensions/reset_password/ecto/schema.ex#L25-L30

I would recommend you to just use that changeset directly though:

```elixir
def reset_password_changeset(user, attrs) do
  PowResetPassword.Ecto.Schema.reset_password_changeset(user, attrs)
end
```

Or not overriding the changeset method at all if you don't do anything different. There should already be a `reset_password_changeset/2` defined by the macro, which does the above.

**Comment by alexsysm** [comment]
Thanks Dan.
This POW thing is WOW, no cap!!!
