### ISSUE TITLE
Consider trimming user_id_field_value

### ISSUE THREAD

**Issue by axelclark** [danschultzer/pow#62]
https://github.com/danschultzer/pow/blob/fcc6d45b4fce6ec8093514a71ca68abae0536ea9/lib/pow/ecto/schema.ex#L176

When a new user adds a space at the end of their email, they will get a format error in the form.  The error isn't obvious and may cause confusion.  

Consider adding `String.trim/1` in addition to `String.downcase/1` to the `Pow.Ecto.Schema.normalize_user_id_field_value/1` function.

**Comment by danschultzer** [comment]
Thanks! I've opened #64 to fix this. It makes a lot of sense to trim the user id field.

**Comment by danschultzer** [comment]
`v1.0.1` has been released with this fix :rocket:
