### ISSUE TITLE
function BookstoreWeb.Pow.Mailer.path_for/5 is undefined or private

### ISSUE THREAD

**Issue by Kapeusz** [danschultzer/pow#627]
Hello, I have added extensions (PowPersistentSession, PowResetPassword, PowEmailConfirmation) following docs and when I want to register/sign in I see errors:
`function BookstoreWeb.Pow.Mailer.path_for/5 is undefined or private` - when I go to `http://localhost:4000/session/new` and `function BookstoreWeb.Pow.Mailer.path_for/3 is undefined or private` when I go to `http://localhost:4000/registration/new`. Do you have any idea what could go wrong here? I am going through each file trying to figure out what I could have messed up but I don't see anything. 
My mailer.ex in lib/bookstore_web/pow/
```
defmodule BookstoreWeb.Pow.Mailer do
  use Pow.Phoenix.Mailer
  use Swoosh.Mailer, otp_app: :boookstore

  import Swoosh.Email

  require Logger

  @impl true
  def cast(%{user: user, subject: subject, text: text, html: html}) do
    %Swoosh.Email{}
    |> to({"", user.email})
    |> from({"Bookstore", "km@bookstore.com"})
    |> subject(subject)
    |> html_body(html)
    |> text_body(text)
  end

  @impl true
  def process(email) do
    email
    |> deliver()
    |> log_warnings()
  end

  defp log_warnings({:error, reason}) do
    Logger.warn("Mailer backend failed with: #{inspect(reason)}")
  end

  defp log_warnings({:ok, response}), do: {:ok, response}
end
```

**Comment by danschultzer** [comment]
What's in your Pow config? Sounds like you have `:routes_backend` set to `BookstoreWeb.Pow.Mailer`. Either remove it or use `BookstoreWeb.Router`.
