### ISSUE TITLE
Email confirmation/password reset token does not work

### ISSUE THREAD

**Issue by Kapeusz** [danschultzer/pow#628]
Hello, whenever I click on the confirmation link/reset password link and got redirected to my website I see a message that the token is invalid/expired. I have not been messing with any Pow options. This is the trace: 
`[info] GET /reset-password/SFMyNTY.ODlhODA2NzQtYzIyMC00ZTlhLThkMWQtNGEwZGJjNjA1MGZk.7ead3zSq1WMHR4IhwXhMWTv3Tw_Q4IN67AQ-qa_26RI
[debug] Processing with PowResetPassword.Phoenix.ResetPasswordController.edit/2
  Parameters: %{"id" => "sfmynty.odlhoda2nzqtyziymc00ztlhlthkmwqtngewzgjjnja1mgzk.7ead3zsq1wmhr4ihwxhmwtv3tw_q4in67aq-qa_26ri"}
  Pipelines: [:browser]
[info] Sent 302 in 5ms
[debug] PowResetPassword.Phoenix.ResetPasswordController halted in :load_user_from_reset_token/2
`
Could you please help me with this one?

**Comment by Kapeusz** [comment]
I tried to config Pow again from the scratch but still getting the same message.

**Comment by danschultzer** [comment]
There was a change in 1.0.24 with https://github.com/danschultzer/pow/pull/618

Now instead of returning the message that `The email address couldn't be confirmed.` it instead return a better error message of `The confirmation token is invalid or has expired.`. This resolves the issue in #583. If you downgrade `1.0.23` do you see the previous error message?

I'm curious why you also see this error for reset password though, there has been no changes to it. Did it use to work before upgrading?

**Comment by Kapeusz** [comment]
I downgraded to `1.0.23` and these are the messages and trace for each scenario.
Password reset message: `The reset token has expired.` and trace:
`[info] GET /reset-password/SFMyNTY.MmNlMGY4NTYtOGVkMC00YTBjLWEyMzYtZjY3ZjE2ZTJmM2Yx.ncEVhPqaE4dtI1rh0EuaizgWOQcMv3aZ71oQ9XlBxUA
[debug] Processing with PowResetPassword.Phoenix.ResetPasswordController.edit/2
  Parameters: %{"id" => "sfmynty.mmnlmgy4ntytogvkmc00ytbjlweymzytzjy3zje2ztjmm2yx.ncevhpqae4dti1rh0euaizgwoqcmv3az71oq9xlbxua"}
  Pipelines: [:browser]
[info] Sent 302 in 11ms
[debug] PowResetPassword.Phoenix.ResetPasswordController halted in :load_user_from_reset_token/2`
And for email confirmation. Message: The email address couldn't be confirmed.
Trace:
`[info] GET /confirm-email/SFMyNTY.NzYwY2UwNTEtNWU4Ny00MGJlLWFjNGUtNDhhNjkxNzUyNmY3.RUbIWCXiHYTcHcmgdYZ5uVd6Ci6Zrfx14GLyaTaqxaA
[debug] Processing with PowEmailConfirmation.Phoenix.ConfirmationController.show/2
  Parameters: %{"id" => "sfmynty.nzywy2uwntetnwu4ny00mgjllwfjngutndhhnjkxnzuynmy3.rubiwcxihytchcmgdyz5uvd6ci6zrfx14glyataqxaa"}
  Pipelines: [:browser]
[info] Sent 302 in 10ms
[debug] PowEmailConfirmation.Phoenix.ConfirmationController halted in :load_user_from_confirmation_token/2
[info] GET /session/new`

**Comment by danschultzer** [comment]
Can you share the Pow config you are using? Does this fail every single time, or does it work e.g. when you test it locally?

Since `v1.0.19` all tokens are signed and verified. It may be that `secret_key_base` is being rotated in the `conn`.

**Comment by Kapeusz** [comment]
Sure. Here are the code snippets:
config.exs
```
config(:bookstore, :pow,
  user: Bookstore.Users.User,
  repo: Bookstore.Repo,
  web_module: BookstoreWeb,
  extensions: [PowEmailConfirmation, PowResetPassword, PowPersistentSession],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks,
  mailer_backend: BookstoreWeb.Pow.Mailer,
  messages_backend: BookstoreWeb.Pow.Messages
)
```
endpoint.ex
```
  @session_options [
    store: :cookie,
    key: "_bookstore_key",
    signing_salt: "/uVdH/rU"
  ]
###
  plug(Plug.Session, @session_options)
  # enable Pow session based authentication
  plug(Pow.Plug.Session, otp_app: :bookstore)
  # enable Pow persistent sessions
  plug(PowPersistentSession.Plug.Cookie)
  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(BookstoreWeb.Plugs.RoutesPlug)
  plug(BookstoreWeb.Router)

```
user.ex
```
defmodule Bookstore.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  use Pow.Extension.Ecto.Schema,
    extensions: [PowEmailConfirmation, PowPersistentSession, PowResetPassword]

  schema "users" do
    field(:first_name, :string)
    field(:last_name, :string)
    field(:address1, :string, default: nil)
    field(:address2, :string, default: nil)
    field(:address3, :string, default: nil)
    field(:city, :string)
    field(:region, :string)
    field(:zip_code, :string)
    field(:role, :string, default: "customer")
    pow_user_fields()
    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
### Other validations
```
routers.ex
```
 use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    otp_app: :bookstore

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(BookstoreWeb.Plugs.RoutesPlug)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :protected do
    plug(Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
    )
  end

  scope "/" do
    pipe_through(:browser)

    pow_routes()
    pow_extension_routes()
  end
```

**Comment by danschultzer** [comment]
Everything looks good, what does `BookstoreWeb.Plugs.RoutesPlug` do?

Only thing is that the endpoint usually has the session stuff last:

```elixir
      plug Plug.RequestId
      plug Plug.Logger

      plug Plug.Parsers,
        parsers: [:urlencoded, :multipart, :json],
        pass: ["*/*"],
        json_decoder: Phoenix.json_library()

      plug Plug.MethodOverride
      plug Plug.Head

      plug Plug.Session, @session_options
      plug Pow.Plug.Session, otp_app: :my_app
      
      plug MyAppWeb.Router
```

But I don't think that should cause any issue.

**Comment by Kapeusz** [comment]
The whole endpoint looks like that: 
```
defmodule BookstoreWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :bookstore

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_bookstore_key",
    signing_salt: "/uVdH/rU"
  ]

  socket("/socket", BookstoreWeb.UserSocket,
    websocket: true,
    longpoll: false
  )

  socket("/live", Phoenix.LiveView.Socket, websocket: [connect_info: [session: @session_options]])

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phx.digest
  # when deploying your static files in production.
  plug(Plug.Static,
    at: "/",
    from: :bookstore,
    gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :bookstore)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, {:multipart, length: 200_000_000}, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.Session, @session_options)
  # enable Pow session based authentication
  plug(Pow.Plug.Session, otp_app: :bookstore)
  # enable Pow persistent sessions
  plug(PowPersistentSession.Plug.Cookie)
  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(BookstoreWeb.Plugs.RoutesPlug)
  plug(BookstoreWeb.Router)
end
```
Actually, I have not changed many things in the router yet so I guess it was autogenerated with the app (Phoenix 1.5.3 and 
```
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.0 (compiled with Erlang/OTP 23)
```

**Comment by danschultzer** [comment]
Yeah, it looks fine. What does `BookstoreWeb.Plugs.RoutesPlug` do?

Do you update the `secret_key_base` anywhere? I suspect it's the signing and verification of the token that doesn't work for some reason. If you want to confirm that you can try downgrade to `1.0.18` and see if it's working.

**Comment by Kapeusz** [comment]
I downgraded to 1.0.18 and now the email verification and password reset work! Ohhh, guess we now found out what is going on and it is totally my fault. I forgot about that plug cause I have not been working on that app for a while... Thank you for the help!

`defmodule BookstoreWeb.Plugs.RoutesPlug do
  import Plug.Conn

  # make URLs case insensitive
  def init(opts) do
      opts
  end
  def call(conn, _params) do
    conn
    |> Map.put(:path_info, Enum.map(conn.path_info, &String.downcase(&1)))
    |> Map.put(:request_path, String.downcase(conn.request_path))
  end
end`

**Comment by danschultzer** [comment]
Happy to help! So the issue happens because the token is case sensitive, but with the `String.downcase/1` call it will change the token. I recommend removing this plug, and only downcase `path_info` and `request_path` at the point it's needed instead of in the conn. You will be able to use `1.0.24` when it has been removed.
