### ISSUE TITLE
Possible race condition between saving user data in Pow's cache and reading it

### ISSUE THREAD

**Issue by ivan-rivera** [danschultzer/pow#635]
The API authorization plug for Pow [described here](https://hexdocs.pm/pow/api.html#api-authorization-plug-for-pow) seems to be creating problems, however, the underlying issue is probably further upstream.

When I run tests, I get intermittent failures that can be fixed by adding the following logic into the fetch function:

```
  def fetch(conn, config, tries \\ 0) do
    with {:ok, signed_token} <- fetch_access_token(conn),
         {:ok, token}        <- verify_token(conn, signed_token, config),
         {user, _metadata}   <- CredentialsCache.get(store_config(config), token) do
      {conn, user}
    else
      # THIS WAS ADDED
      :not_found ->
        if tries <= 5 do
          fetch(conn, config, tries + 1)
        else
          {conn, nil}
        end
      # -------------------
      _any -> {conn, nil}
    end
  end
```

If you'd like to be able to reproduce the problem itself, you can try it out on [this repo](https://github.com/ivan-rivera/sleep_rescue_api) -- the tests are failing due to this bug alone (the above fetch code is not committed).
For more information, please see this thread on the [Elixir Forum](https://elixirforum.com/t/mix-test-fails-while-individual-test-files-succeed/41046/3?u=ivr).

The bug might not be limited to the test environment only, but the underlying cause of this problem is still unknown.

**Comment by johns10** [comment]
If you read the issues (especially the one about testing in live view), you'll find a workaround that involves posting the data directly to the endpoint, then waiting 100ms while pow completes its transaction with the cache (in my case I use Mnesia). @danschultzer has a recommended ETS Cache Mock you can put in place that will remove this necessity.

**Comment by danschultzer** [comment]
I've decided to make the write calls synchronous with #650. It's easy to enable asynchronous writes if it ever becomes a bottle neck, and this should make it simple to test and prevent this race condition. I'll release `v1.0.25` ASAP, let me know if you experience any issues with it!
