### ISSUE TITLE
How to customize create_user query

### ISSUE THREAD

**Issue by johns10** [danschultzer/pow#644]
I'm using the `:current_user` on my plug for building context in an absinthe API, and I need some preloads. Can I customize this query? I've tracked it down to here (I think)

https://github.com/danschultzer/pow/blob/master/lib/pow/operations.ex#L54

**Comment by danschultzer** [comment]
Yes! With a custom context module you can add preloads: https://github.com/danschultzer/pow/issues/308#issuecomment-545475332

Let me know if this answers your question, if not I'll reopen this issue!
