### ISSUE TITLE
Auto-joining Nodes with Mnesia Backend

### ISSUE THREAD

**Issue by djthread** [danschultzer/pow#653]
Hello, Dan & company! I've been happy with Pow in my application, so thank you so much for this great library!

As I work to put my nodes into clustered mode, I've switched to the mnesia backend and I have a couple questions.

First, when my application supervisor starts up, `Pow.Store.Backend.MnesiaCache` gets `Node.list()` which doesn't include my peers yet -- libcluster connects them seconds after. To verify, I added a `Process.sleep/1` before listing peers and starting MnesiaCache in my application supervisor startup. Is there a mechanism to have the new node automatically added to mnesia when libcluster connects with it? It would be nice to avoid needing the sleep and also to generally know that new nodes which join the cluster are connected via mnesia as well, but I didn't quite see anything about this when I looked.

My other question is about this error I'm getting when I use Process.sleep and the other node (I have two at the moment) _is_ included in the `:extra_db_nodes` option on start. I notice that everything seems connected and operating normally after this, so I'm thinking it may be expected and safe to ignore.

Thank you!

```
17:42:46.634 [info] Starting pow mnesia backend with nodes: [:"my_app@xxx.xxx.xxx.24"]
17:42:46.636 [info] Application mnesia exited: :stopped
17:42:46.662 [error] Couldn't join mnesia cluster because: {:add_table_copy, {:aborted, {:no_exists, {Pow.Store.Backend.MnesiaCache, :cstruct}}}}
17:42:46.662 [info] Application my_app exited: exited in: MyApp.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Error starting {Pow.Store.Backend.MnesiaCache, [extra_db_nodes: [:"my_app@xxx.xxx.xxx.24"]]}: {:error, {{:add_table_copy, {:aborted, {:no_exists, {Pow.Store.Backend.MnesiaCache, :cstruct}}}}, {:child, :undefined, Pow.Store.Backend.MnesiaCache, {Pow.Store.Backend.MnesiaCache, :start_link, [[extra_db_nodes: [:"my_app@xxx.xxx.xxx.24"]]]}, :permanent, false, 5000, :worker, [Pow.Store.Backend.MnesiaCache]}}}
            (my_app 0.2.0) lib/my_app/application.ex:36: anonymous fn/1 in MyApp.Application.start/2
            (elixir 1.12.1) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
            (my_app 0.2.0) lib/my_app/application.ex:32: MyApp.Application.start/2
            (kernel 8.0.1) application_master.erl:293: :application_master.start_it_old/4
```

**Comment by djthread** [comment]
Thank you, Dan! At the moment my application start function currently looks more or less like this. (30 seconds might be a bit longer than I need.)

```
  def start(_type, _args) do
    children =
      libcluster_child_specs() ++
        [
          MyApp.Repo,
          MyAppWeb.Telemetry,
          {Phoenix.PubSub, name: MyApp.PubSub},
          @endpoint,
          {Absinthe.Subscription, @endpoint}
        ]

    opts = [strategy: :one_for_one, name: @sup]
    {:ok, pid} = Supervisor.start_link(children, opts)

    Process.sleep(30_000)

    Enum.each(session_cache_child_specs(), fn spec ->
      case Supervisor.start_child(@sup, spec) do
        {:ok, _} -> :ok
        {:ok, _, _} -> :ok
        other -> raise("Error starting #{inspect(spec)}: #{inspect(other)}")
      end
    end)

    {:ok, pid}
  end

  # If mnesia is the configured session store, add some procs to start.
  @spec session_cache_child_specs :: [module | {module, keyword}]
  defp session_cache_child_specs do
    if Pow.Store.Backend.MnesiaCache ==
         Application.get_env(:my_app, :pow, [])[:cache_store_backend] do
      nodes = Node.list()
      Logger.info("Starting pow mnesia backend with nodes: #{inspect(nodes)}")

      [
        {Pow.Store.Backend.MnesiaCache, extra_db_nodes: nodes},
        Pow.Store.Backend.MnesiaCache.Unsplit
      ]
    else
      []
    end
  end
```

**Comment by djthread** [comment]
Oh, sorry I forgot to include that in my last reply! The libcluster strategy is `Cluster.Strategy.Kubernetes.DNS`.

And what you suggest seems to work except that using `{Node, :list, []}` or `Node.list()` before libcluster settles down and connects the nodes, they don't get added. This leads to some weirdness on the frontend, I'd imagine due to different servers being hit for each request. After login, some requests work and sometimes the server thinks I haven't authenticated.

I'm also curious if libcluster will be able to add and remove nodes over time with the mnesia config following along.

Thank you so much for the help here!

**Comment by danschultzer** [comment]
Didn't mean to keep you waiting, but I unfortunately got held up by intense work the last two days. Thank for your patience.

You should definitely use `{Node, :list, []}` instead of calling `Node.list()`, so the node list gets pulled after libcluster have spin up not before. The issue in this case is that `Cluster.Strategy.Kubernetes.DNS` indeed doesn't join any nodes for a while which will make it so all MnesiaCache nodes will start up individually instead of connecting to the cluster.

There are a number of ways to handle this. But first, instead of starting up two supervisors in parallel, you should start up all the children one by one with the same supervisor. So this is the correct flow:

```elixir
 def start(_type, _args) do
    children =
        [
          {Cluster.Supervisor, [topologies, [name: MyApp.ClusterSupervisor]]},
          MyApp.Repo,
          MyAppWeb.Telemetry,
          {Phoenix.PubSub, name: MyApp.PubSub},
          @endpoint,
          {Absinthe.Subscription, @endpoint},
          {Pow.Store.Backend.MnesiaCache, extra_db_nodes: {Node, :list, []}},
          Pow.Store.Backend.MnesiaCache.Unsplit
        ]

    opts = [strategy: :one_for_one, name: @sup]
    {:ok, pid} = Supervisor.start_link(children, opts)
  end
```

What we want to happen is to wait with spinning up Mnesia till we're sure that the kubernetes strategy can resolve the DNS. There are many ways to achieve this.

We could add that logic to `MyApp.Application` but we could also move our MnesiaCache into a supervisor. Instead of just adding `:timer.sleep/1` to this supervisor we can continuously check if DNS gets resolved and let the startup fail if it doesn't.

Here's an example:

```elixir
defmodule MyApp.MnesiaClusterSupervisor do
  use Supervisor

  def start_link(opts) do
    # You could do the same here running `:timer.sleep(30_0000)`
    # But it might be better to delay until we got DNS resolving:
    wait_for_kubernetes(opts)

    Supervisor.start_link(__MODULE__, opts, name: __MODULE__)
  end

  def init(_opts) do
    children = [
      {Pow.Store.Backend.MnesiaCache, extra_db_nodes: {Node, :list, []}},
      Pow.Store.Backend.MnesiaCache.Unsplit
    ]

    Supervisor.init(children, strategy: :one_for_one)
  end
  
  defp wait_for_kubernetes(opts) do
    timeout = Keyword.get(opts, :timeout, 30_000)
    
    task =
      Task.async(fn ->
        check_kubernetes_dns(opts)
      end)
      
    task
    |> Task.yield(timeout)
    |> Kernel.||(Task.shutdown(task))
    |> case do
      :ok -> :ok
      nil -> raise "Couldn't resolve DNS in #{timeout}ms"
    end
  end

  defp check_kubernetes_dns(opts) do
    :timer.sleep(5_000) # Matching the libcluster polling
    
    service = Keyword.fetch!(opts, :dns_service)

    case :inet_res.getbyname(to_charlist(service), :a) do
      {:ok, {:hostent, _fqdn, [], :inet, _value, _}} ->
        # To prevent race condition the libcluster genserver should probably be triggered to load the DNS records here
        :ok

      _any ->
        check_kubernetes_dns(opts)
    end
  end
end
```

```elixir
 def start(_type, _args) do
    children =
        [
          {Cluster.Supervisor, [topologies, [name: MyApp.ClusterSupervisor]]},
          MyApp.Repo,
          MyAppWeb.Telemetry,
          {Phoenix.PubSub, name: MyApp.PubSub},
          @endpoint,
          {Absinthe.Subscription, @endpoint},
          {MyApp.MnesiaClusterSupervisor, dns_service: topologies[:my_strategy][:config][: service]}
        ]

    opts = [strategy: :one_for_one, name: @sup]
    {:ok, pid} = Supervisor.start_link(children, opts)
  end
````

I wanted to test this out to make sure this works with the Kubernetes DNS strategy, but I don't have to time atm. Please let me know if this works for you.

A better approach than the above probably would be to create a custom libcluster module based on `Cluster.Strategy.Kubernetes.DNS` that waits with startup until DNS is resolved rather than letting the startup sequence in the supervision tree continue.

> Are many people going this route? Any particular pitfalls or things to look out for?

I don't know how many, but I do know people are running it successfully in production. Many end up using redis, postgres, or similar if they don't have persistent disk. Mnesia is used in pretty large systems, and works very well. Debugging used to be painful but I think the improved error messages in OTP 24 makes it much easier.

**Comment by djthread** [comment]
So I'm not the only one baffled by this, then. It totally also seemed to me that adding the mnesia supervisor next to libcache shouldn't affect libcache's ability to join the cluster. But I've seriously found that clustering happens and the app starts up properly without the mnesia supervisor, but as soon as I add it, I get these errors until the 30 seconds point where startup fails.

I added the Node.list info line right after the 5 second sleep.

To be honest, I'm not really sure what I would try next. Maybe I'll look into the libcluster strategy wrap method sooner rather than later. Thank you again for the help!

```
16:52:48.577 [info] Node.list(): []
16:52:48.577 [warn] DNS not available yet: {:error, :formerr}
16:52:48.581 [error] [libcluster:my_app] lookup against phoenix-app-srv-headless failed: :nxdomain
16:52:48.585 [error] [libcluster:my_app] lookup against phoenix-app-srv-headless failed: :nxdomain
16:52:53.578 [info] Node.list(): []
16:52:53.578 [warn] DNS not available yet: {:error, :formerr}
16:52:53.592 [error] [libcluster:my_app] lookup against phoenix-app-srv-headless failed: :nxdomain
16:52:53.595 [error] [libcluster:my_app] lookup against phoenix-app-srv-headless failed: :nxdomain
```

**Comment by djthread** [comment]
It looks like my mysterious issue is related to the containers waiting until DNS is ready to bring up the endpoint so they can pass the Kubernetes health check. The tricky thing is that it is this very health check is what puts the node in the pool returned via DNS! My teammate is going to look into possibly setting up two different health checks so we can get into DNS but wait until the pool is established and MnesiaClusterSupervisor starts before actually being deemed healthy enough to accept web requests.

In the meantime, I did notice that my sessions do not persist when new containers with an application update roll in. I'd prefer to avoid adding Redis as a new dependency... Is there perhaps some existing code somewhere which would allow me to use Postgres to persist the data in this case so my users don't get logged out? What would you recommend here?

**Comment by danschultzer** [comment]
And btw for the Mnesia cluster don't you also have an existing cluster running during deploy? It might be helpful to just connect to the existing cluster. And then tear down after deploy succeeded. You would still need to deal with situation where you have nothing running but this might help you think of the right strategy for your setup.

**Comment by djthread** [comment]
Yeah! Is that possible? There might be a few seconds (maybe we could tune it) where the old servers are still up when the data could be migrated over to the new cluster? Wouldn't the new servers need to actually join the old ones via libcluster _and_ mnesiacluster? I'm not sure what exactly needs doing to get there, but if you recommend that over the other options, I do like the sound of it.

Otherwise, I think I'd look closer at ZennerIoT's library there. It ldoes appear that this would be the cache store backend *instead* of mnesia, right? I had thought mnesia was nice because it's all on the cluster and it sounds faster than calling the db every time a session needs to be loaded or stored, right?

**Comment by djthread** [comment]
libcluster and mnesia are now joining together without without issue or any sleep needed thanks to my teammate's discovery: adding `publishNotReadyAddresses: true` on the Kubernetes service spec. This seems to make the DNS available immediately.

^ THIS IS THE ANSWER to the original question :)

And I'm not sure what it would take exactly to get the new servers' MnesiaCaches to connect to the outbound ones to copy down the existing database. Might need to tweak things to get them to stick around longer etc... Is this something you'd recommend? Surely other teams doing something similar have encountered this one?

Thank you, Dan!!

**Comment by danschultzer** [comment]
Hi @djthread, I've worked on #655 that should solve this issue by initializing the Mnesia cluster whenever a new node is connected. It'll be out in the next release and auto enabled 😄

**Comment by djthread** [comment]
Awesome! That feature seems to make a lot of sense.

Thank you very much, Dan!
