### ISSUE TITLE
Various ways of signing in a user? (ie., via email, phone_number, username)

### ISSUE THREAD

**Issue by 0xAvinash** [danschultzer/pow#662]
Hi @danschultzer I'm currently using Pow via `phone number` & `password` combo to login and create a session for my API. I would like to extend this behaviour to different kinds ie., the user could also use `email` or `username` & `password` combination to login.

What are the ways to achieve my use case? I would appreciate greatly if you could help.

**Comment by 0xAvinash** [comment]
@danschultzer could you please advice on this issue?
I've been stuck with it for a long time, at present this is how my `lib/my_app/users/user.ex` looks like
```
  use Pow.Ecto.Schema,
    user_id_field: :phone,
    password_hash_methods: {&Argon2.hash_pwd_salt/1, &Argon2.verify_pass/2}
```

How do I configure the above code also to allow user for using their `username` or `email` address instead of only `phone` number to sign in?

Thank you very much for your attention :)

**Comment by 0xAvinash** [comment]
@danschultzer I would appreciate a response.. I'm still stuck with my issue :(

**Comment by ravensiris** [comment]
There is no built in solution. `user_id_field` singular(noun) for a reason.

What you could do however is override the controller:
https://hexdocs.pm/pow/custom_controllers.html#controllers

```elixir
defmodule MyAppWeb.SessionController do
  use MyAppWeb, :controller

  def new(conn, _params) do
    changeset = Pow.Plug.change_user(conn)

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    # 1 Get the login value out of `user_params`
    # 2 Evaluate if the login value has a phone, email or username format
    # 3 Query your db for a user with that phone or email or username etc
    # 4 Put whatever `user_id_field`(the field you set in user.ex) you found from the query back into user_params
    conn
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, conn} ->
        changeset = Pow.Plug.change_user(conn, conn.params["user"])

        conn
        |> put_flash(:info, "Invalid email or password")
        |> render("new.html", changeset: changeset)
    end
  end
```
Hope that helps. 
If you already solved it please share your solution and close the issue.

**Comment by 0xAvinash** [comment]
@ravensiris thank you very much for taking the time to respond. 

How to do this 
```# 4 Put whatever `user_id_field`(the field you set in user.ex) you found from the query back into user_params```

I still couldn't find the solution unfortunately

**Comment by ravensiris** [comment]
@0xAvinash 
After you fetched your user from the db you should have a `User` struct with the relevant fields(email, phone, username).

Assuming you still have `user_id_field: :phone`.
Then you can do something like:
```elixir
def create(conn, %{"user" => user_params}) do
  user = %User{} # fetch your actual user into this var
  user_params = Map.put(user_params, :phone, user.phone)
  # rest of the controller code
```

**Comment by 0xAvinash** [comment]
@ravensiris thank you very much for your approach. Closing the issue :)
