### ISSUE TITLE
Disable registration routes

### ISSUE THREAD

**Issue by mrcasals** [danschultzer/pow#67]
Hi!

I'm looking for a way to disable registration routes, as the app I'm building won't need them. I couldn't find any configuration option, so what's the suggested approach for this?

I tried changing `pow_routes()` in my router to this:

```elixir
    scope "/", Pow.Phoenix, as: "pow" do
      resources "/session", SessionController, singleton: true, only: [:new, :create, :delete]
    end
```

But it forces me to import the session templates and overwrite them, as they use the registration path (which doesn't exist now).

Is there a better way to achieve this?

Thanks! 😄

**Comment by danschultzer** [comment]
It's not possible without custom templates currently, but maybe it could be possible if a conditional check is made on the registration link: https://github.com/danschultzer/pow/blob/80e1dc03725552a319e81e8448cd84566d9786ec/lib/pow/phoenix/templates/session_template.ex#L15

I think your approach is great, I really like the idea of disabling registration by just removing the registration paths :smile: Let me give it some thoughts to figure out how this could work well.

**Comment by mrcasals** [comment]
Maybe we could add it as a configuration option? Then when defining the `pow_routes()` macro we could check the configuration and add the registration paths if needed. Then add a view helper to check that, and use it on the link you posted.

I also disabled the `registration#edit` route because I don't need it and wanted to use a different layout for sign in and profile edition pages, and couldn't find a way to achieve it (but I might be missing something, I'm quite new to Elixir/Phoenix)

**Comment by mrcasals** [comment]
Ah yes, I thought about something like `pow_routes(registration: false)`, but then I didn't know how to check whether the `registration_path` existed or not, that's why I mentioned a config option. But again, I'm barely starting with Elixir/Phoenix, so there might be a way I'm not aware of.

> I assume you'll use a custom controller for profile edit?

Yes, that was the idea, but I haven't started this section. I'll keep your idea in mind in case it comes handy!

**Comment by danschultzer** [comment]
So I would love Pow to be smart enough to just detect what kind of template it should generate, but after doing a few different solutions for this, I think it's clashing too much with the goal of Pow being as explicit as possible. It's better to let the responsibility be on the developer, and require them to generate the templates.

Ideally all customization of Pow would be done by the developer by extracting the individual parts they want to customize. So in this case I would recommend to make the custom routes, and [generate the templates](https://github.com/danschultzer/pow#modify-templates), and then delete the registration templates/views since they are not needed.

I'm thinking about [writing a guide](https://github.com/danschultzer/pow/tree/master/guides) on how to disable registration.

**Comment by danschultzer** [comment]
(Also I checked for the routes existence with the `__routes__/0` method in the router module, but it's not meant to be a public API method)

**Comment by mrcasals** [comment]
> So in this case I would recommend to make the custom routes, and generate the templates, and then delete the registration templates/views since they are not needed.

@danschultzer yup, that's what I ended up doing. I'm 👍 on this solution, the only issue I had was that I had to look at the internals of `pow` to see what the `pow_routes()` macro expanded to. What about separating the content of `pow_routes()` in different macros so that devs can use `pow_session_routes()` or `pow_routes()` as they need to, without having to rely too much on the implementation of those macros? Whout that be fine?

**Comment by danschultzer** [comment]
It's something I did think about doing for quite some time. I've opened #71 that makes it possible.

**Comment by danschultzer** [comment]
Also added a guide for disabling registration 😄

**Comment by mrcasals** [comment]
Looks good, yay! Thanks for the time building this! :smile:
