### ISSUE TITLE
Feature Request: Apple Passkeys

### ISSUE THREAD

**Issue by nesimtunc** [danschultzer/pow#672]
Hi, 

This would be great to integrate with Apple's new Authentication System - [Passkeys](https://developer.apple.com/passkeys/).

Thank you

**Comment by danschultzer** [comment]
It’s been something I’ve wanted to add for a long time: #6 

I hope to get around to it soon, but it will require a larger refactor of how Pow works. This is definitely the future of auth, and Pow must support it.
