### ISSUE TITLE
Pow.Plug.authenticate_user/1 performance

### ISSUE THREAD

**Issue by deepak-sriram** [danschultzer/pow#676]
Hi, We are using Pow for authentication. While we checking on the execution time, we found that Pow.Plug.authenticate_user/1 takes around 617ms. Whether it will take that much of time to authenticate user inside pow or is there a way to optimize it?!

Thanks in advance!

**Comment by danschultzer** [comment]
Yeah that's very slow, I suspect it's either the hashing algorithm or db latency. I would need to know more about your setup. What's the Pow configuration like?

**Comment by danschultzer** [comment]
Yeah that's slow, but that's not a bad thing. I believe it's the hashing algorithm. Argon2 recommends that hashing should take 0.5s. Libsodium recommends one second. This is necessary to prevent brute force attack.

The configuration you want to use depends on your requirements for security balanced with user experience. It's a fair tradeoff to make the user wait a while to complete authentication if that makes it untenable to crack the password.

By default Pow runs with PBKDF2 of 100,000 iterations. Depending on the hardware you run it on that should make the hashing take at least several hundred miliseconds.

**Comment by deepak-sriram** [comment]
Ohh Okay. Then we will plan with the hardware for authentication. 

Thanks for the help! @danschultzer
