### ISSUE TITLE
Phoenix 1.7 compilers warning

### ISSUE THREAD

**Issue by charlottemoche** [danschultzer/pow#683]
I am running into a warning from: https://github.com/danschultzer/pow/blob/master/mix.exs#L13

1.7 has this line removed, and apparently it's throwing the warning from having the line in this file, too.
Is it possible to create a separate branch for 1.7 with this line removed? Making the assumption that others running > 1.7 will still need the line.

```
warning: the :phoenix compiler is no longer required in your mix.exs.

Please find the following line in your mix.exs and remove the :phoenix entry:

    compilers: [..., :phoenix, ...] ++ Mix.compilers(),

  (phoenix 1.7.0-rc.1) lib/mix/tasks/compile.phoenix.ex:8: Mix.Tasks.Compile.Phoenix.run/1
  (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
  (mix 1.14.0) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1

==> pow
```

See: https://github.com/phoenixframework/phoenix/issues/5201

**Comment by danschultzer** [comment]
Thanks! I realized that the compiler wasn't necessary since Elixir 1.11. I have removed it in #684. Will work on full Phoenix 1.7 support and make a release.
