### ISSUE TITLE
Including user details in email templates

### ISSUE THREAD

**Issue by dhruvbhatia** [danschultzer/pow#69]
By default, `reset_password.html.eex` only exposes the `@url` assigns variable.

How would I go about also having the `@user` variable exposed so that I can customise my email templates? For example, I want to open my emails with `Hi {user},` as opposed to just a generic `Hi,`?

Guidance appreciated.

**Comment by danschultzer** [comment]
Yeah, it makes sense that the user is also available in the assigns. I've opened #70 to add both @conn and @user to the assigns.

**Comment by danschultzer** [comment]
Ok, it's in master. A new release will be up within a few days.

**Comment by dhruvbhatia** [comment]
@danschultzer thanks so much! 👍

**Comment by danschultzer** [comment]
`v1.0.1` has been released :rocket:
