### ISSUE TITLE
Manually create session?

### ISSUE THREAD

**Issue by kidbombay** [danschultzer/pow#72]
How do we manually create a session given a user?

**Comment by danschultzer** [comment]
You can create a plug session with authenticated user by calling `Pow.Plug.Session.create(conn, user, otp_app: :my_app)`:

https://github.com/danschultzer/pow/blob/caa55743fac533cfdbed72b09bb34041adc8697c/lib/pow/plug/session.ex#L66-L94

**Comment by kidbombay** [comment]
Great thanks, and closing one out?

**Comment by danschultzer** [comment]
Just below:

https://github.com/danschultzer/pow/blob/caa55743fac533cfdbed72b09bb34041adc8697c/lib/pow/plug/session.ex#L96-L113

Pow.Plug.Session.delete(conn, otp_app: :my_app)
