### ISSUE TITLE
Make current password optional when editing user?

### ISSUE THREAD

**Issue by kidbombay** [danschultzer/pow#74]
Is there a way to make current password optional when riding user?

**Comment by danschultzer** [comment]
Yeah, you just have to override [the changeset](https://github.com/danschultzer/pow/blob/c8fc244887336bf633a75a0ba71a9e29622351bc/lib/pow/ecto/schema.ex#L108-L114):

```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  # ...

  def changeset(user_or_changeset, attrs) do
      user_or_changeset
      |> pow_user_id_field_changeset(attrs)
      |> pow_password_changeset(attrs)
  end
end
```

**Comment by danschultzer** [comment]
Obviously this makes the current password irrelevant, as it should be if users can edit their information without the current password, but if you want to make it actually optional (so if used it has to be the correct password) you would need to add it as a custom changeset method:

```elixir
  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> maybe_validate_current_password(attrs)
    |> pow_user_id_field_changeset(attrs)
    |> pow_password_changeset(attrs)
  end

  defp maybe_validate_current_password(user_or_changeset, attrs) do
    case current_password_entered?(attrs) do
      false -> user_or_changeset
      true  -> pow_current_password_changeset(user_or_changeset, attrs)
    end
  end 
```

**Comment by kidbombay** [comment]
Thank you!
