### ISSUE TITLE
Use Redis for session cache?

### ISSUE THREAD

**Issue by kidbombay** [danschultzer/pow#75]
We are deploying to Heroku which as I understand doesn't support mnesia?
Can you use redis with pow for session storage?

**Comment by danschultzer** [comment]
Yeah, but you have to write a custom cache store module. Take a look at the current ETS and Mnesia modules for an idea how it works (they are based on `GenServer`, which you won't need for a Redis integration): https://github.com/danschultzer/pow/tree/master/lib/pow/store/backend

You'll need to implement the following methods:

https://github.com/danschultzer/pow/blob/8fcc82627ecd3e3c2cc9b5854d116442a5a4201b/lib/pow/store/base.ex#L15-L18

Also you have to make sure that it uses the TTL and namespace configuration, but with Redis that would be easy. Remember to set the config:

```elixir
cache_store_backend: MyApp.PowRedisCache
```

As a quick n dirty example to get you started using Redix:

```elixir
defmodule MyApp.PowRedisCache do
  @behaviour Pow.Store.Base

  alias Pow.Config

  def put(config, key, value) do
    key = redis_key(config, key)
    ttl = Config.get(config, :ttl)

    {:ok, "OK"} = Redix.command(conn, ["SET", key, value])
    if ttl, do: {:ok, "OK"} = Redix.command(conn, ["PTTL", key, ttl])

   :ok   
  end

  defp redis_key(config, key) do
    namespace = Config.get(config, :namespace, "cache")

    "#{namespace}:#{key}"
  end
end
```

You'll probably need to serialize the value too in the above example.

**Comment by kidbombay** [comment]
Thank you, will take a look.

**Comment by danschultzer** [comment]
I've added a completely guide on how to set up Redis backend cache (#88): https://github.com/danschultzer/pow/blob/3c116af73d140ee524ac3028fda766a46a0d536a/guides/REDIS_CACHE_STORE_BACKEND.md

Let me know if this works for you!

**Comment by kidbombay** [comment]
Amazing!!

**Comment by kidbombay** [comment]
This is great! Will it work if we use a custom controller? That’s been our issue.

**Comment by danschultzer** [comment]
Yeah, custom controller shouldn't affect the cache store backend. It's the plug methods that communicates with the store.

**Comment by minibikini** [comment]
Hi @danschultzer, thanks for the great library! I use it multiple projects. May I ask why not to include the Redis implementation from your guide to the library?

**Comment by danschultzer** [comment]
Thanks, great to hear @minibikini!

I don't include it in Pow because there's no native support for Redis in erlang/elixir. I try to keep Pow at near zero dependencies.

**Comment by minibikini** [comment]
I see, thanks!
