### ISSUE TITLE
example of Pow, Pow Assent and Phoenix Outh Provider project?

### ISSUE THREAD

**Issue by niccolox** [danschultzer/pow#77]
have you got an example project, a reference project, of Pow, Pow Assent and Phoenix Oauth2 Provider working together?

I am interested in an umbrella app scenario

**Comment by danschultzer** [comment]
I don’t have a demo app with all three together, but you should be able to get it running in 5 minutes. There isn’t really much to it other than running through the setup instructions for each library.

I would recommend setting up Pow and PowAssent first, and test it out. The the OAuth2 provider as you’ll need the user schema module as resource owner.

I assume that you’ll have regular user registration web interface with Pow/PowAssent and an API with the OAuth2 provider.

**Comment by niccolox** [comment]
ok, I just tried it, and hit trivial errors

I'd encourage a reference implementation

will try again soon (I hope)

**Comment by niccolox** [comment]
ok, I am working from a fresh install outside of my umbrella and backfilling into the umbrella

making progress I guess, will post other issues if they come up

**Comment by danschultzer** [comment]
Great, please do post if you find any issues with Pow or PowAssent!

**Comment by danschultzer** [comment]
FYI I've updated the tutorial for PhoenixOauth2Provider with Pow example now:

https://dreamconception.com/tech/phoenix-full-fledged-api-in-five-minutes/
https://github.com/danschultzer/phoenix_ex_oauth2_provider_demo

**Comment by niccolox** [comment]
(Thumbsup)

**Comment by niccolox** [comment]
what I want to be able to do is use this provider to authenticate between apps in umbrella

having a single app provide and authenticate itself is not so useful

if I had the time I would try again to starting with this demo, perhaps simply add a second app in the umbrella with an oauth client (pow)? 

glad you updated this and very hopeful development

**Comment by danschultzer** [comment]
It's outside the scope of the tutorial, but you should definitely be able to do that. Requires two separate phoenix apps in your umbrella project with one having the oauth2 provider, and the other having PowAssent. I do recommend following the guide to get started with the first app, that is Pow + PhoenixOauth2Provider. From there you can set up the second app by just following the guide in PowAssent.
