### ISSUE TITLE
How to make Pow to send user's password by confirmation email

### ISSUE THREAD

**Issue by igormisha** [danschultzer/pow#81]
It would be great (for my project at least) if we could configure Pow to not give password and confirm password fields to the registration form but to let the user provide his email, generate and send the password for him automatically.

If that's not configurable and there is no plan to implement it, then how easy to make it, what steps should be done in order to achive this?

I've already installed Pow and EmailConfirmation extension for now.

**Comment by danschultzer** [comment]
I would go for [a custom controller](https://github.com/danschultzer/pow/blob/1616fd507d28c7dca732680fee0c991f2f98994e/guides/CUSTOM_CONTROLLERS.md) setup to modify the flow completely. This way you can generate the password in the controller action, and pass it to both the create changeset, and to e-mail generation (e-mail should be part of the controller/view layer unless it's separated to an independent app). You may also want to force users to enter a new password when signing in.

It's best to have this as a custom controller rather than configuration option is that you keep the code explicit, and force to test your code to ensure that things works as you expect.

**Comment by danschultzer** [comment]
Also, you will probably need to combine the generated password with email confirmation e-mail too, so this way you'll have full control over the flow and can just extract the various parts from Pow as needed.

**Comment by igormisha** [comment]
Ok, I see. So I need not to use the registration routes provided by Pow. Instead of it I should make my own routes leading to my own controller. After user submits registration form the submitted email gets into my registration controller create function.  Is there some api function in EmailConfirmation extension which I can provide with generated password and call it to send email to new user?

**Comment by danschultzer** [comment]
There's no password generator in Pow, only hashing/validation. But it's very simple to auto generate password, like this:

```elixir
length
|> :crypto.strong_rand_bytes()
|> Base.url_encode64()
|> binary_part(0, length)
```

I would just fill it out as the passwords in the controller:

```elixir
defmodule MyAppWeb.RegistrationController do
  use MyAppWeb, :controller

  def create(conn, %{"user" => user_params}) do
    password = gen_password()
    user_params = Map.merge(user_params, %{"password" => password, "confirm_password" => password})

    conn
    |> Pow.Plug.create_user(user_params)
    |> case do
      {:ok, user, conn} ->
        send_registration_email(conn, user, password)

        conn
        |> Pow.Plug.clear_authenticated_user()
        |> put_flash(:info, "Please check your e-mail for your auto generated password!")
        |> redirect(to: Routes.session_path(conn, :new))

      {:error, changeset, conn} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  defp gen_password(), do: # gen password
  defp send_registration_email(conn, user, password), do: # Generate and send e-amil
end
```

**Comment by danschultzer** [comment]
Cool, please feel free to post the controllers here for others to see how Pow can be customized 😄

**Comment by igormisha** [comment]
Hi, I'm working on the custom controller and your example already contains most of the logic for password generation and user creation using 
`Pow.Plug.create_user(user_params)`
but I also need to confirm the user's email, so I installed PowEmailConfirmation extension which is responsible for generation confirmation token for user but how to tie it's logic into my controller? What function do I need to call or is it made automatically by Pow.Plug.create_user(user_params) function call?

**Comment by danschultzer** [comment]
I've written about how extensions [should be built into custom controllers in the guide](https://github.com/danschultzer/pow/blob/master/guides/CUSTOM_CONTROLLERS.md#further-customization). It's best if you take full control, so you also add tests and makes sure everything runs as expected. The [above example](
https://github.com/danschultzer/pow/issues/81#issuecomment-461596979) should also give an idea for a setup of the RegistrationController with EmailConfirmation. The actual e-mail delivery can be found here:

https://github.com/danschultzer/pow/blob/6518aaad2f1cbb680ac8ff8e8760021f00011717/lib/extensions/email_confirmation/phoenix/controllers/controller_callbacks.ex#L53-L60

You should combine the email confirmation, and generated password e-mail.

However, I've got an idea for how you can add generated password with  no custom controllers! This may help simplify a lot of things for you. Instead you generate a custom `MyApp.Users` module:

```elixir
defmodule MyApp.Users do
  use Pow.Ecto.Context
  
  def create(params) do
    password = gen_password(10)

    params
    |> Map.put("password", password)
    |> Map.put("confirm_password", password)
    |> pow_create()
    |> case do
      {:ok, user}     -> {:ok, %{user | password: password}}
      {:error, error} -> {:error, error}
    end
  end

  def gen_password(length) do
    length
    |> :crypto.strong_rand_bytes()
    |> Base.url_encode64()
    |> binary_part(0, length)
  end
end
```

```elixir
config :my_app, :pow,
  # ...
  users_context: MyApp.Users
```

This setup will add the generated password to the virtual `:password` field in the user when created, so in the e-mail confirmation template you can access the password in e-mail with `@user.password`. I haven't tested this, but I think it should work.

**Comment by igormisha** [comment]
Sounds great but I want to clarify. Do I have to implement other functions like authenticate, update, delete, get_by in that module or just create function?

**Comment by danschultzer** [comment]
Nope, they are already there with the `use Pow.Ecto.Context` macro.

**Comment by igormisha** [comment]
Awesome, thanks!

**Comment by igormisha** [comment]
Hi, I tried to add custom users context by your advise but got error:
`** (Pow.Config.ConfigError) No :user configuration option found for user schema module.`
Something is wrong with calling pow_create() function.

**Comment by danschultzer** [comment]
Oh forgot the config. Update the use macro with the `:otp_app` config:

```elixir
use Pow.Ecto.Context, otp_app: :my_app
```

Or more explicit, add the user/repo directly there:

```elixir
use Pow.Ecto.Context,
  user: MyApp.Users.User,
  repo: MyApp.Repo
```

**Comment by igormisha** [comment]
Now it works! Thanks!

**Comment by igormisha** [comment]
I'll put here my final implementation in case it can help anyone else.
So I ended up with creating both custom context module and custom registration controller.
Custom registration controller is not really necessary now but it will be later because I'll need more than one user types with different data put into different database tables, so there will be more than one registration form. Besides that my site is going to be multilingual, so I've put all routes into the :locale scope in the router and in the modules below you can see that I needed to take it into account and redirect user to the right path, I also had to modify forms action properties in forms.

My custom Users context module looks like this:

```elixir
defmodule Jp.Users do
  use Pow.Ecto.Context, otp_app: :jp

  def create(params) do
    params = if params["password"] == nil do
      password = gen_password(10)
      params
        |> Map.put("password", password)
        |> Map.put("confirm_password", password)
    else
      params
    end
    params
    |> pow_create()
    |> case do
      {:ok, user}     -> {:ok, %{user | password: params["password"]}}
      {:error, error} -> {:error, error}
    end
  end

  def gen_password(length) do
    length
    |> :crypto.strong_rand_bytes()
    |> Base.url_encode64()
    |> binary_part(0, length)
  end
end
```

and my custom registration controller:
```elixir
defmodule JpWeb.RegistrationController do
  use JpWeb, :controller
  alias Jp.Users
  alias PowEmailConfirmation.Phoenix.ControllerCallbacks, as: EmailConfirmation

  def new(conn, params) do
    changeset = Pow.Plug.change_user(conn, params)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Users.create user_params do
      {:ok, user} ->
        EmailConfirmation.send_confirmation_email(user, conn)
        conn
        |> put_flash(:info, "Please confirm your email!")
        |> redirect(to: Routes.locale_pow_session_path(conn, :new, conn.assigns.locale))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

end
```

Big Thanks, to @danschultzer for your library, help and support!

**Comment by danschultzer** [comment]
Looks great!

I definitely prefer developers take full charge of the controllers with customization because it enforces to test the controllers, and give full flow control.

However, do note that you can use multiple different User structs with the default Pow controllers if you override config, or use different endpoints (this was the purpose of Pow when I built it):

## Different endpoints

```elixir
# Global config
config :my_app, :pow,
  repo: MyApp.Repo,
  # ...
```

```elixir
# Phoenix Endpoint app A

  plug Pow.Plug.Session,
    user: MyApp.UserA,
    otp_app: :my_app # The rest is defaults

# Phoenix Endpoint app B

  plug Pow.Plug.Session,
    user: MyApp.UserB,
    otp_app: :my_app # The rest is defaults
```

## Override config (same phoenix app)

```elixir
# Phoenix router
  pipeline :pow_config_b do
    plug :pow_config_b
  end

  def pow_config_b(conn, _opts) do
    new_config =
      conn
      |> Pow.Plug.fetch_config()
      |> Pow.Config.merge(user: MyApp.UserB)

    Pow.Plug.put_config(conn, new_config)
  end

  scope "/a" do
    pipe_through :browser

    pow_routes()
  end

  scope "/b" do
    pipe_through [:browser, :pow_config_b]

    pow_routes()
  end
```

This is off the top of my head, but there are a multitude ways of doing this since Pow is super modular 😄
