### ISSUE TITLE
Cannot login as user migrated from Coherence

### ISSUE THREAD

**Issue by jaimeiniesta** [danschultzer/pow#83]
Hello! I'm migrating an app from Coherence to Pow, I've followed the guide but when I try to log in I get the error message:

```elixir 
ArgumentError at POST /session
cannot load `<<158, (...) , 200>>` as type :id for field `id` in schema MyApp.User
```

This is the migration that created the users table using Coherence:

```
defmodule MyApp.Repo.Migrations.CreateUser do
  use Ecto.Migration

  def change do
    create table(:users, primary_key: false) do
      add(:id, :uuid, primary_key: true)
      add(:name, :string, null: false)
      add(:email, :string, null: false)
      add(:password_hash, :string, null: false)
      add(:role, :string, default: "user", null: false)
      add(:confirmed_at, :datetime)
      add(:confirmation_token, :string)
      add(:confirmation_sent_at, :datetime)
      add(:reset_token, :string)
      add(:reset_sent_at, :datetime)

      timestamps()
    end

    create(unique_index(:users, [:email]))
  end
end
```

And in the `User` model it's specified that:

```
@primary_key {:id, :binary_id, autogenerate: true}
```

What am I doing wrong here? Does Pow use `uuid` as Coherence does?

Thanks!

**Comment by jaimeiniesta** [comment]
This is on Elixir 1.8.1, Phoenix 1.4.0, EctoSql 3.0, Comeonin 3.0.

**Comment by danschultzer** [comment]
Yeah, Pow has binary id support, and it should be working out of the box. Pow doesn't have any expectations for the id type and let's ecto handle it.

For some reason your app expects the id field to an `:id` integer type. Can you show how `MyApp.User` module is set up? Did you put the `@primary_key` before `schema`?

Also, remember that you'll need to add `@foreign_key_type :binary_id` to the user schema for relations.

**Comment by jaimeiniesta** [comment]
Thanks, I must have some issue with UUIDs and Ecto 3 then, this doesn't seem a Pow-related issue.
