### ISSUE TITLE
Coherence Migration - Required to add Email Confirmation migrations?

### ISSUE THREAD

**Issue by axelclark** [danschultzer/pow#84]
This may be obvious, but if I don't intend to use the PowEmailConfirmation extension, can I skip the [migration](https://github.com/danschultzer/pow/blob/master/guides/COHERENCE_MIGRATION.md#add-pow-to-your-ecto-schema) in the Coherence migration guide?

Also, are the only `User` fields required for POW, `email` and `password_hash`?  Can I remove all of the other authentication-related Coherence `User` fields?  
```elixir
      # rememberable      
      add :remember_created_at, :utc_datetime
      # recoverable
      add :reset_password_token, :string
      add :reset_password_sent_at, :utc_datetime
      # lockable
      add :failed_attempts, :integer, default: 0
      add :locked_at, :utc_datetime
      # trackable
      add :sign_in_count, :integer, default: 0
      add :current_sign_in_at, :utc_datetime
      add :last_sign_in_at, :utc_datetime
      add :current_sign_in_ip, :string
      add :last_sign_in_ip, :string
      # unlockable_with_token
      add :unlock_token, :string
```

Finally, I'm assuming I can drop my `rememberables` table (created by coherence) because it is not used by the POW PersistentSession extension?

**Comment by danschultzer** [comment]
Yeah, you are correct, you can ignore all that and drop the columns. If you don't need any extensions at all you can just ignore all extension macro/method calls, and the mailer section. You will be required is to set up [bcrypt hashing](https://github.com/danschultzer/pow/blob/284433766de5c969185d09bbdc4095d802f49fd7/guides/COHERENCE_MIGRATION.md#continue-with-bcrypt-hashing) to continue using bcrypt with existing users, and that's pretty much it.
