### ISSUE TITLE
Make confirm_password optional?

### ISSUE THREAD

**Issue by jaimeiniesta** [danschultzer/pow#86]
The sign up form contains both `password` and `confirm_password` fields.

I think that this password confirmation field is unnecessary and in fact a UX antipattern that leads to less sign ups, and most of the time is just bypassed by copy-pasting it from the password field. More about that here:

https://uxmovement.com/forms/why-the-confirm-password-field-must-die/

In Coherence this field is optional, and will only be validated if present. Is there any way to do this also in Pow?

**Comment by danschultzer** [comment]
There are several ways you can solve it. If you just wish to make it optional the best way would be to update the ecto changeset method to override the `confirm_password` param when needed.

Could look like this:

```elixir
defmodule MyApp.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  # ...

  def changeset(user_or_changeset, attrs) do
    attrs = put_confirm_password(attrs)

    pow_changeset(user_or_changeset , attrs)
  end

  defp put_confirm_password(attrs) do
    case has_confirm_password?(attrs) do
      true  -> attrs
      false -> Map.put(attrs, "confirm_password", attrs["password"])
    end
  end

  defp has_confirm_password?(%{"confirm_password" => confirm_password}) when is_binary(confirm_password) and confirm_password != "", do: true
  defp has_confirm_password?(_attrs), do: false
end
```

As for password confirmation being unnecessary, I definitely see your point. I've been building both apps with and without password confirmation, and it's not always an anti-pattern. It depends on what type of app you are building.

Two things come to mind right away with Pow:

  * If you have a non-email user id field, or you don't enable reset password extension, there's no way to recover.
  * By default, Phoenix don't have any show/hide JS included for password fields, so passwords can't be verified before submitting.

Maybe I should add a guide on how to disable the password confirmation, or making it optional.

**Comment by jaimeiniesta** [comment]
Thanks, you're right that this is not always an anti-pattern, but it can be often desirable to disable password confirmation.

It would be great to be able to make this optional in Pow, but the changeset trick can work for me now.

Thanks!

**Comment by danschultzer** [comment]
I've given this some more thought. I think it makes most sense to keep the confirm password by default even though the majority of apps probably won't need it:

- The login and registration pages are extremely simple, only user id and password
- It helps differentiate login and registration pages
- It forces developers take control of their flow when removing confirm password, and helps them understand flexibility of Pow

What I think of doing instead is to make the changeset more flexible so you can do something like this to remove confirm password validation:

```elixir
def pow_changeset(user_or_changeset, attrs) do
  user_or_changeset
  |> pow_user_id_field_changeset(attrs)
  |> pow_current_password_changeset(attrs)
  |> pow_new_password_changeset(attrs)
  # |> pow_confirm_new_password_changeset(attrs)
end
```

And the default `pow_password_changeset` calls both `pow_new_password_changeset` and `pow_confirm_new_password_changeset`. I'll give this some more thought, but for now I think this is the best solution to keep Pow easy to work with.

**Comment by jaimeiniesta** [comment]
I agree, leaving it by default is a good safe choice, and the solution to make the changeset more flexible sounds good also.

**Comment by danschultzer** [comment]
I've pushed #91 PR. I'll just review docs to see if there's a place where it fits, and then merge it in.

**Comment by danschultzer** [comment]
Master has the fix so you can now just do the following:

```elixir
import Pow.Ecto.Schema.Changeset, only: [new_password_changeset: 3]

# ...

def changeset(user_or_changeset, attrs) do
  user_or_changeset
  |> pow_user_id_field_changeset(attrs)
  |> pow_current_password_changeset(attrs)
  |> new_password_changeset(attrs, @pow_config)
end
```

This will ignore the `confirm_password_changeset/3` method.

**Comment by jaimeiniesta** [comment]
Thanks, just tried that but I get this error:

```elixir
➔ iex -S mix phx.server
Erlang/OTP 20 [erts-9.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Compiling 14 files (.ex)

== Compilation error in file lib/pow_demo/users/user.ex ==
** (CompileError) lib/pow_demo/users/user.ex:17: undefined function new_password_changeset/3
    (elixir) src/elixir_locals.erl:107: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
    (elixir) src/elixir_locals.erl:107: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

This is my user module:

```elixir
defmodule PowDemo.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  @pow_config Application.get_env(:pow_demo, :pow)

  schema "users" do
    pow_user_fields()

    timestamps()
  end

  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_user_id_field_changeset(attrs)
    |> pow_current_password_changeset(attrs)
    |> new_password_changeset(attrs, @pow_config)
  end
end
```

Also note that I defined `@pow_config` - not sure if that's needed but it fails anyway with and without it.

**Comment by danschultzer** [comment]
You shouldn't add `@pow_config`. `use Pow.Ecto.Schema` sets the variable. You just need to add `import Pow.Ecto.Schema.Changeset, only: [new_password_changeset: 3]` after `use Pow.Ecto.Schema`.
