### ISSUE TITLE
URLs in mailers include internal port

### ISSUE THREAD

**Issue by jaimeiniesta** [danschultzer/pow#89]
When running a Phoenix app in Heroku, it's started in a random port like this:

```
Running MyAppWeb.Endpoint with cowboy 2.6.1 at http://myapp.herokuapp.com:49327
```

Links in Pow mailers (email confirmation and password resets) are wrongly taking this port into account - making the links unusable as the ports are not for public requests, they're internal:

```
Hi,

Please use the following link to reset your password:

http://myapp.herokuapp.com:49327/reset-password/05bb8a01-116d-45c3-98b3-8e4c872ec5aa

You can disregard this email if you didn't request a password reset.
```

**Comment by danschultzer** [comment]
This is Phoenix related. You need to [configure the url for path generation](https://hexdocs.pm/phoenix/1.4.1/Phoenix.Endpoint.html#module-runtime-configuration):

```elixir
config :my_app_web, MyAppWeb.Endpoint,
  # ..,
  url: [scheme: "https", host: "example.com", port: 443]
```

Or as env variable:

```elixir
config :my_app_web, MyAppWeb.Endpoint,
  # ..,
  url: [scheme: "https", host: {:system, "HOST"}, port: 443]
```
