### ISSUE TITLE
Better message when updating email address

### ISSUE THREAD

**Issue by jaimeiniesta** [danschultzer/pow#90]
When updating a user email we get this message:

```
Your account has been updated.
```

Instead if the email has changed and a confirmation link has been sent, I think it would be better to instruct the user to check the inbox to confirm it.

Also, on the Registration Edit form the old email address is still shown in the form, which may lead to think that the update has not succeeded.

I think that just explaining this a bit more would be enough, the user needs to understand that a confirmation email has been sent and that the update will not be effective until that link is clicked.

**Comment by danschultzer** [comment]
There's instructions in [the PowEmailConfirmation README](https://github.com/danschultzer/pow/blob/a3e43e37b827793b6f3f92392eb79c91d69e6cf1/lib/extensions/email_confirmation/README.md#configuration) for how to update the templates to have better UX.

The flash message can be [overridden manually](https://github.com/danschultzer/pow/blob/1d059d97be1eb38a39cfb5e1482e1d36764d4cbe/lib/pow/phoenix/messages.ex#L5-L15), but it may make sense to override the message automatically when the email confirmation extension is triggered. I'll look into that.

**Comment by danschultzer** [comment]
Ok, I've added an error flash for when e-mail is updated. I don't know if it makes sense, so it would be great if you could test it out in your flow.

To try out the branch:

```elixir
{:pow, github: "danschultzer/pow", branch: "email-confirmation-error-flash-on-update"}
```

**Comment by jaimeiniesta** [comment]
Thank you, I just tried it but I don't get why it's an error flash instead of an info? Now I see 2 flashes:

![captura de pantalla 2019-02-27 23 28 23](https://user-images.githubusercontent.com/2629/53527630-c8aabd80-3ae7-11e9-8e71-7403a157064b.png)

I think it would be better to show just one of them, probably an `info` with 

> Your account has been updated, but you'll need to confirm the e-mail before it's updated. An e-mail confirmation link has been sent to you.

**Comment by danschultzer** [comment]
Yeah, it reflects how RegistrationController and SessionController works by showing `:error` flash when email hasn't been confirmed (even when registration was successful), and I also like that the original `:info` message is still shown.

It's much more difficult to override or manage the `:info` flash flow (what I tried initially) in the current controller callbacks setup. Ideally multiple `:info` messages can be combined, but this is not how Phoenix Controller works, and I agree it makes sense to have it as a `:info` flash. I'll dig deeper and see what I can come up with 😄

**Comment by jaimeiniesta** [comment]
Hey I don't know, maybe having both messages also makes sense, it looked a bit weird at first but it can also be a good solution anyway.

**Comment by danschultzer** [comment]
Yeah, after thinking a bit more, I think this compromise works. I'll merge this into master. It'll be redone if I find a way to manage flash flow better.
