### ISSUE TITLE
How to refresh session cache?

### ISSUE THREAD

**Issue by jaimeiniesta** [danschultzer/pow#93]
In my application, the `User` module holds some data apart from email and password, and these columns can be updated outside of the user registration / edit flow. In my case, these are counters for actions made by the user that are updated by other modules in the background.

As the user is cached in the Session cache (Redis in my case), `@current_user` will not reflect updates on those fields.

What is the proper way to force an update on the cache? I've found that I need to log out and log in again to have this refreshed, but maybe there's a better way to ask Pow to reload the user info from the database so that its cache is refreshed.

**Comment by danschultzer** [comment]
There's several ways of doing this. I would recommend just resetting the session on each update action, if you have access to the conn.

### 1. Update user for action in controller

This creates a new session id on each action:

```elixir
config = Pow.Plug.fetch_config(conn)

Pow.Plug.Session.do_create(conn, user, config)
```

### 2. Reload the user in a plug

This will reload on every single page request:

```elixir
plug :reload_user
```

```elixir
  defp reload_user(conn, _opts) do
    config = Pow.Plug.fetch_config(conn)
    user = Pow.Plug.current_user(conn, config)
    reloaded_user = Repo.get(MyApp.User, user.id)

    Pow.Plug.assign_current_user(conn, reloaded_user, config)
  end
```

### 3. Update user directly in CredentialsCache

Finally, you could refresh the struct in the `CredentialsCache` directly if you wish. However, I recommend against it as it's pretty involved. In short, you'll need to load the update the map for `"#{Macro.underscore(struct)}_sessions_#{id}"`, updating the `:user` key. You can see the action here: https://github.com/danschultzer/pow/blob/master/lib/pow/store/credentials_cache.ex#L110-L116

**Comment by danschultzer** [comment]
I think this is maybe something that should be mentioned in a guide.

**Comment by jaimeiniesta** [comment]
👍 Solution 2 was perfect in my case, thanks!

**Comment by danschultzer** [comment]
Great, I've added a note to the readme in #97 about potential out of sync user structs if affected by actions outside Pow.

**Comment by s-stepien** [comment]
Is this method (also description: https://hexdocs.pm/pow/sync_user.html) possible for non current user? In my example: if admin set role of other user to 'super' I would like to refresh the state of the other not the admin.

**Comment by danschultzer** [comment]
@s-stepien you can do that, but it's not practical (since it creates a new session) neither advisable. For any authorization check it's better to load the user any request where you want to check permissions, so just add a plug that loads the user (or the permissions for the user) from the DB to ensure they have the right permission level.
