### ISSUE TITLE
JWT support

### ISSUE THREAD

**Issue by sobolevn** [danschultzer/pow#98]
Hi @danschultzer!
Thanks for the awesome library.

Is it possible to use `jwt` based auth together with `pow`?

**Comment by danschultzer** [comment]
Thanks! Yeah, you can take a look at [the authorization plug section](
https://github.com/danschultzer/pow#authorization-plug) for an example using Guardian instead of the default session based auth:

```elixir
defmodule MyAppWeb.Pow.Plug do
  use Pow.Plug.Base

  def fetch(conn, config) do
    user = MyApp.Guardian.Plug.current_resource(conn)

    {conn, user}
  end

  def create(conn, user, config) do
    conn = MyApp.Guardian.Plug.sign_in(conn, user)

    {conn, user}
  end

  def delete(conn, config) do
    MyApp.Guardian.Plug.signout(conn)
  end
end

defmodule MyAppWeb.Endpoint do
  # ...

  plug MyAppWeb.Pow.Plug, otp_app: :my_app
end
```

I haven’t had any need to use JWT myself, but I would love to hear how well Pow works with JWT.

**Comment by sobolevn** [comment]
So, it might be a plugin, right?

**Comment by danschultzer** [comment]
Sure, but I would probably advice against making an individual library if the code will be as simple as the above example 😀
